### ISSUE TITLE
move netlify account for website knative.dev from google owned to cncf owned

### ISSUE THREAD

**Issue by csantanapr** [knative/community#1002]
Currently, the website https://knative.dev is hosted on netlify using Pro account (retail $19/month) this is currently funded by Google.

CNCF offers netlify funding and we should move the knative account from Google to CNCF, to avoid complexity this should be done after the DNS registry and service is moved to CNCF

**Comment by csantanapr** [comment]
Currently Google paying 25k minutes pro plan (retail $19/month)
We currently use from 300 to 1000 minutes
Need to request a netlify account thru CNCF and see how to switch over with minimum downtime (ie domain, TLS Certs)

**Comment by csantanapr** [comment]
Opened CNCF [ticket](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1291)

They created a site under the CNCF account and assignme owner, but I don't see it. I posted a message to add me using my github login

>I invited you as an owner to https://app.netlify.com/teams/knativedev  - work with @Nate Waddington but since you’re on netlify already, you can just xfer your site over to the knativedev team that CNCF owns and you should be all set

**Comment by csantanapr** [comment]
I was able to get access tot he `knativedev` site under the CNCF netlify account and I'm one of the owners along side with @nate-double-u

Netlify has a feature to transfer a site from one account to another account https://answers.netlify.com/t/support-guide-how-to-transfer-a-netlify-site-to-a-new-owner/3866

For me to do it I would need to be the owner of the current netlify account that is owned by Google. 
I will reach out to @RichieEscarez and @thisisnotapril to see if they would make me owner or have @thisisnotapril be owner of both accounts and do the transfer

**Comment by RichieEscarez** [comment]
Hi @csantanapr, sorry for the delayed response. After chatting with @thisisnotapril we made you an owner of the Google owned Netlify account so that you can perform the transfer.

**Comment by csantanapr** [comment]
netlify website is now moved to CNCF owned account, @dprotaso and @psschwei have access to the account. 
/close
