### ISSUE TITLE
Add the donation checklist to the repo guidelines

### ISSUE THREAD

**Issue by rgregg** [knative/community#102]
There's a nice [donation checklist](https://github.com/knative/community/issues/81) that a few people have used in their Issues to donate code to the Knative project. However, this template and the actions required by it are not spelled out anywhere in the repo guidelines.

We should clean that up into a documented process, instead of a shared knowledge thing.

**Comment by mattmoor** [comment]
So...  This actually is spelled out (as we discovered Thursday), and it's not that list :)

https://github.com/knative/community/blob/master/REPOSITORY-GUIDELINES.md#requirements-for-repository-donation

**Comment by mattmoor** [comment]
I think it's worth leaving this open to make it more discoverable, but it exists.

**Comment by rgregg** [comment]
I think the guidelines are insufficient, and hence why that checklist grew organically out of previous requests. E.g. there's nothing in the documented guidelines about Steering having a voice about a fit to project scope. The documented steps are a very tactical "do this than that" kind of thing, without the strategic/project elements included, which are more visible in the checklist.

I'd like to see us combine elements of the checklist into what we've documented, and ideally give that checklist in markdown that people can include in their request. Perhaps an Issue template?

**Comment by rgregg** [comment]
Also, we shouldn't leave issues open to fix discoverability problems.

**Comment by mattmoor** [comment]
I meant leave it open to track FIXING the discoverability issues 😉

**Comment by pmorie** [comment]
I think we are close to having this closed by #151
