### ISSUE TITLE
ROLES.md does not reflect the roles that actually exist within Knative

### ISSUE THREAD

**Issue by geekygirldawn** [knative/community#1049]
During a discussion about a TOC candidate in PR #1039, it was mentioned that we don't really have a clear path to becoming an approver, which lead me to do a review of the existing [ROLES.md](https://github.com/knative/community/blob/main/ROLES.md) file, which has members and approvers, but not reviewers. In looking at [knative.yaml](https://github.com/knative/community/blob/main/peribolos/knative.yaml), we also have a reviewers role in between member and approver that is undocumented. I think we should add the reviewer role to ROLES.md.

I also think that we should improve the ROLES.md file to more clearly describe the process required to move from member to reviewer to maintainer using a contributor ladder approach. We have a [CNCF template for the contributor ladder](https://github.com/cncf/project-template/blob/main/CONTRIBUTOR_LADDER.md), and I think we could merge some things from that template into your existing ROLES.md file to make the process of moving into leadership roles easier and more clear.

I'm happy to help someone with this, but I don't have the bandwidth to take this on right now.

cc: @lance @csantanapr @jberkus @vaikas

**Comment by skonto** [comment]
I have been thinking about this and I am wondering (may have been discussed before):
a) major contributors in an area shouldnt be approvers anyway? For example someone may not reach the required reviews but has written most parts of the code. The guy who reviews the PRs becomes the approver without righting any code?
b) in project with low traffic it must take for ages to become an approver. Any alternative paths there? 
c) Other skills matter for PR reviews beyond technical matters and code quality, to make sure community goals are reached.
Shouldnt be these listed too?

**Comment by evankanderson** [comment]
Just for clarification -- "reviewers" is a way to get Prow to assign issues to you automatically so you get a stream of PRs to review without needing to watch for them.  I think the requirements are equal to the "member" role, but it's a means to help indicate that you're looking to get the review requirements completed to get to "approver".

**Comment by geekygirldawn** [comment]
@lance Are you still working on this or would you like for me to draft something?

**Comment by lance** [comment]
@geekygirldawn "still" 🤣 - I put it on the back burner for months, but am now about halfway through an update to the document. I'm using the CNCF template that you referenced in the issue description, and adding a "Contributor" role to our doc. I should be able to open a PR today and your feedback/commentary would be most welcome.
