### ISSUE TITLE
Upgrade Elekto to 0.6.0

### ISSUE THREAD

**Issue by jberkus** [knative/community#1119]
Knative SC/TOC:

[Elekto 0.6.0](https://github.com/elekto-io/elekto/releases/tag/0.6.0) has been released.  This version improves voter privacy and allows ballot review.  We'd like to upgrade the instance used for Knative elections.

All we need here is permission from the SC; once we have that, the Red Hat OSPO Infra team can handle the rest.

**Comment by csantanapr** [comment]
@jberkus is ok by SC to go ahead and do the upgrade.
