### ISSUE TITLE
duplicate WORKING-GROUPS files

### ISSUE THREAD

**Issue by richterdavid** [knative/community#112]
https://github.com/knative/community/blob/762911a8659a1b91b7b23cfc8cf432d19b496a00/working-groups/WORKING-GROUPS.md
and
https://github.com/knative/community/blob/466425c8fddcc69d5d1dbb471099ed346ec793a6/WORKING-GROUPS.md

are near-duplicates. The Client WG meeting schedule appears to be fresher in the former though, and there may be other differences.

At a very minimum, those duplicates should be eliminated. I'd recommend, though, eliminating one of the pages, perhaps leaving behind a redirection to the other, and looking for references to the eliminated one to update them.

**Comment by mpetason** [comment]
It looks like the file is getting moved under working-groups instead of top level. I think when that cuts over we can remove the duplicate links. Right now they are there so both links work? Not sure.

**Comment by evankanderson** [comment]
Fixed in #123
