### ISSUE TITLE
PROCESS CHANGE: Post Zoom meeting recordings to slack.

### ISSUE THREAD

**Issue by vaikas** [knative/community#1125]
Currently it's a bit cumbersome to get the Zoom recording URLs. We should write a job that goes through and fetches the recordings for a day and post them to our slack so that folks can have a single place to get notices for them and then they can be added to relevant documents.

API reference here:
https://marketplace.zoom.us/docs/api-reference/zoom-api/methods/#tag/Cloud-Recording/operation/recordingsList

**Comment by csantanapr** [comment]
I looked into zoom apps, and the account that we got from CNCF doesn't allow to create  a [Server-to-Server OAuth App](https://marketplace.zoom.us/docs/guides/build/server-to-server-oauth-app/) 

_A Server-to-Server OAuth app enables you to securely integrate with Zoom APIs and get your account owner access token without user interaction. This is different from the [OAuth app type](https://marketplace.zoom.us/docs/guides/build/oauth-app), which requires user authentication. See [Using OAuth 2.0](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#using-oauth-20) for details._

Notice
>The [JWT app type will be deprecated in June, 2023](https://marketplace.zoom.us/docs/guides/build/jwt-app/jwt-faq). We recommend that you create [Server-to-Server OAuth](https://marketplace.zoom.us/docs/guides/build/server-to-server-oauth-app) or [OAuth](https://marketplace.zoom.us/docs/guides/build/oauth-app) apps to replace the functionality of a JWT app in your account.

If you go to https://marketplace.zoom.us/develop/create
I used my personal free zoom account, and I'm able to create this type of app.
On the left is the Knative Account, and on the right is my personal account, as you can see I can create a server to server app
![image](https://user-images.githubusercontent.com/1094878/181648269-363fa521-d462-4d16-9984-bf94c20cb561.png)

Not sure if we can use a JWT app to be able to achieve our goal @vaikas

**Comment by lance** [comment]
Closing for now - as long as WG leads have access to zoom credentials we should be good with manual updates on meeting notes docs.
