### ISSUE TITLE
Viability and scope of Knative Catalog FT

### ISSUE THREAD

**Issue by dsimansk** [knative/community#1127]
**Knative Calatog**

This feature track is about defining a central repository for Knative addons and the kind of meta-data that it should contain. It is not about the usage of this meta-data, like generating an searchable website, including it into knative.dev or how a kn plugin can leverage this data.

The metadata syntax that is suggested is supposed to be only a start and it should be possible to extend the meta-data schema in the future, also depending on how the data is consumed.

FT doc: https://docs.google.com/document/d/1nxbHXydqqLGldC2pkyNv4RERVqEdxKwzgJIv7mk2Ghs/edit#

The idea of Knative Catalog was introduced as a solution to `kn` plugin discoverability. However, the extended scope might be beneficial for other part of project, e.g. Eventing Sources. 

Therefore this is a question and an discussion tracker to define the scope of Knative Catalog FT. 

/cc @rhuss

**Comment by evankanderson** [comment]
Don’t currently have a specific UI attached, just to collect the metadata.

We used to have something like this for eventing sources, and it got torn out in https://github.com/knative/docs/pull/2680

Do we enforce schema / categorization? probably yes?

Next steps: ask Eventing WG (Lionel) / Networking WG (Kenjiro) if they are interested

For integration with Docs, think about the ergonomics of how this gets into the docs.

**Comment by abrennan89** [comment]
Not even close to being an expert on this, but in general, have we ever looked at using something like Swagger for API and plugin docs, rather than manually needing to create markdown files and then figure out what to do with them?

**Comment by rhuss** [comment]
@abrennan89 Swagger actually is really connected to REST Apis and their Schemas, but the idea here is the same: Provide a catalog of Meta-data that then is used to create automatically other artefacts out of it (markdown doc, searchable website, single descriptor usable by a CLI plugin ...)

**Comment by evankanderson** [comment]
It seems like Tekton and other projects are building off https://artifacthub.io/, including:

* KEDA scalers
* Helm charts
* Tekton tasks and pipelines (two separate categories)
* krew plugins

**Comment by evankanderson** [comment]
(Discussed at TOC meeting, Nov 10)

Might be good to start with one category, like CLI plugins, and report back

**Comment by dsimansk** [comment]
This can be closed now. The initial proposal was completed through publishing plugins to Artifact Hub. 

/close
