### ISSUE TITLE
knative With Traefik Ingress Setup In Cluster

### ISSUE THREAD

**Issue by ecda909** [knative/community#1159]
Hi everyone, in my project I use Traefik to handle all of my ingress functionality and I'm looking to use knative to make all of my deployments serverless. My question is do I have to switch to Istio as my ingress solution or is there a way I can still pull-off the setup using Traefik?

Thanks!

**Comment by psschwei** [comment]
We don't currently support Traefik, but that doesn't mean you can't use it if you really, really want to (but you'd need to write some kind of [KIngress](https://github.com/knative/networking/#knative-ingress-aka-kingress) implemention for it, which is most likely not super practical). That said, you don't have to use Istio -- we also support Kourier and Contour as networking layers (you can find more details on our [website](https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#install-a-networking-layer)).

(cc @nak3 to double-check I didn't misstate any of the above)

**Comment by nak3** [comment]
Yes, Paul's comment is correct.

Also, we plan to support Gateway API, which [Traefix will also support it](https://gateway-api.sigs.k8s.io/implementations/) via our controller https://github.com/knative-sandbox/net-gateway-api. If it becomes stable, we hope that users can use any Ingress which supports Gateway API.

**Comment by dprotaso** [comment]
Going to close this out - although we don't test net-gateway-api with traefik if you want to do that yourself and provide some feedback please do so @ https://github.com/knative-sandbox/net-gateway-api
