### ISSUE TITLE
Moving trademark charter under Steering supervision and rename it to "conformance commitee"

### ISSUE THREAD

**Issue by nainaz** [knative/community#1161]
Things to include with your process proposal (delete this text):
Since knative is now under CNCF, there is little to no benefit to keep a separate Trademark charter and rights. As CNCF own the trademark rights and has a dedicated process.
In new process we should
* Rename the Knative TM commitee to "Knative conformance commitee"
* Moving this charter under Steering supervision. 
* This task "may" need TM member to approve it. 
* Benefits: More inline with CNCF guidelines and process
* Before the Year End 2022

**Comment by lance** [comment]
@nainaz any update here?

**Comment by nainaz** [comment]
Sent multiple emails to folks. Still working on this.

**Comment by nainaz** [comment]
Turns out getting votes on issue was not enough. 
Needed to get votes during official TM meeting. 
Oct 5th got necessary votes. Now need to create PR to close it 
Attach the meeting recording to PR

**Comment by aliok** [comment]
Possible duplicate: #1399

@nainaz although I didn't get a confirmation, I think my comment here might help with proceeding with the closing PR: https://github.com/knative/community/issues/1399#issuecomment-1714192708

**Comment by aliok** [comment]
Recording of TM committee dissolving itself: https://zoom.us/rec/play/HNRYazP5M4rpvwgjxG9axsSayl5zvMyCSOr5zLG7t5DwpF32wbkLfpseJzcRnrxinVZ9TMZSHBrAAV7M.X7QPrUUoBHSyvJ-i?canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fzoom.us%2Frec%2Fshare%2FSQdqoQVUlYjE4Q4KYSOgPzfq2aP5Hs1A0F6SN-zm8SynkOhnp6h_3KpXTyrEJuhH.uSIcatWGYOwNnFk4

**Comment by aliok** [comment]
Closing in favor of #1399
