### ISSUE TITLE
New Repo: `func` (move from knative-sandbox/kn-plugin-func)

### ISSUE THREAD

**Issue by salaboy** [knative/community#1169]
## Repo information

Org: `knative`

Repo: `func`

Purpose (Description): 
Moving Knative Functions from `knative-sandbox`/`kn-plugin-func` to `knative`/`func`. The reasons behind this request to move are: 
- The project is now aligned with the main Knative release train
- We are working towards making the project to reach the "usable" maturity level
- We want to announce this new branding `func` during KubeCon NA / KnativeCon NA 2022

Sponsoring WG: Knative Functions Working Group

## Actions to fulfill

This area is used to track the [repo creation process](https://github.com/knative/community/blob/main/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review. You are responsible for moving your entry on the board to "Needs Discussion" or "In Progress" as you move forward in this checklist.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [x] Send a PR adding entries for this repo in [`/peribolos/knative-sandbox.yaml`](https://github.com/knative/community/blob/main/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  ~- [ ] Grant the sponsoring WG the `write` privilege.~

Note that for repos moving from knative-sandbox, it is necessary to move these entries from knative-sandbox.yaml to knative.yaml

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [x] Ask Steering to add the repo to EasyCLA in [Slack](https://knative.slack.com/archives/CU9DGL4FM).

- [x] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/docs/pull/4160)).

~~- [ ] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an~~
  ~appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),~
  ~[sample-controller](https://github.com/knative-sandbox/sample-controller),~
  ~[sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as~
  ~a git remote.  For example:~

Unnecessary for a move

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo main
  ```

- [x] Add your GitHub ID to the `OWNERS` file for your repo.

- [x] [Set up](https://github.com/knative/test-infra/blob/main/guides/prow_knative_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge) prow for a new repo

- [ ] Bootstrap your CI jobs using [hack](https://github.com/knative/hack) project (look at other sandbox repos for reference)

- [x] Create a sample PR to verify Prow (e.g., edit the boilerplate README)

- [x] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

- [x] (optional) Send a PR adding the repo to [knobots](https://github.com/knative-sandbox/knobots).

**Comment by psschwei** [comment]
+1 for me. I can take on whatever work is needed from the TOC side to do the move, etc.

**Comment by evankanderson** [comment]
:+1:

I can help with this tomorrow if we agree on it. I think the current progress on `func` matches the guidelines in [Migration to Core] (https://github.com/knative/community/blob/main/mechanics/MATURITY-LEVELS.md#migration-to-core).

In particular, the abstractions are user-facing, developer-friendly, and the underlying language addition process is pluggable outside the core.

**Comment by psschwei** [comment]
> A stable project may apply to the SC and TOC to be admitted to the Knative core ...

Reading the migration guidelines, does Steering also need to approve? cc @lance

**Comment by psschwei** [comment]
> Reading the migration guidelines, does Steering also need to approve? 

As discussed on Steering call today, migration to core was already approve, this is just moving the repo, so disregard the above

**Comment by csantanapr** [comment]
👍

**Comment by lance** [comment]
* [x]  (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/docs/pull/4160)).

https://github.com/knative/docs/pull/5257

**Comment by lance** [comment]
> * [ ]  [Set up](https://github.com/knative/test-infra/blob/main/guides/prow_knative_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge) prow for a new repo

This will need to be a modification to the existing prow configuration for knative-sandbox/kn-plugin-func

**Comment by lance** [comment]
> * [x]  Send a PR adding entries for this repo in [`/peribolos/knative-sandbox.yaml`](https://github.com/knative/community/blob/main/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
>   
>   * [x]  Add the repository and a description.
>   * [x]  Grant `Knative Admin` the `admin` privilege.
>     ~- [ ] Grant the sponsoring WG the `write` privilege.~
> 
> Note that for repos moving from knative-sandbox, it is necessary to move these entries from knative-sandbox.yaml to knative.yaml

See: https://github.com/knative/community/pull/1170

**Comment by salaboy** [comment]
I've created this PR for `knobots`. I am trying to figure out what other configuration changes do we need in there: https://github.com/knative-sandbox/knobots/pull/240

**Comment by salaboy** [comment]
Ask to steering in Slack done: https://knative.slack.com/archives/CU9DGL4FM/p1664956526130389

**Comment by salaboy** [comment]
I think the missing tasks in the checklist can be done after moving the repo. @evankanderson @psschwei @csantanapr It will be great to get the steering committee's blessing so @lance can move the repository, and we can complete the tasks.

**Comment by csantanapr** [comment]
@salaboy this is a technical topic that is under TOC purview

TOC is already aware of this work, and @lance has the access to move the repo on the admin panel.

**Comment by lance** [comment]
Just a heads up to the @knative/technical-oversight-committee that we hope to do this move tomorrow, October 6.

**Comment by zroubalik** [comment]
+1 from me as well, I was off last week

**Comment by salaboy** [comment]
can we close this issue now? and track new problems if they arise in a separate issue?
