### ISSUE TITLE
Update and maintain CNCF project summary

### ISSUE THREAD

**Issue by dsimansk** [knative/community#1187]
At the KubeCon NA I met Catherine Paganini on behalf CNCF to check and update landscape metadata and information about Knative. They're trying to make sure there's enough details for filtering and description of what the projects are for. 

https://github.com/cncf/landscape/blob/master/readme_summary.md

/cc @knative/steering-committee @knative/technical-oversight-committee

**Comment by evankanderson** [comment]
This may relate to the work to introduce the project to the CNCF Ambassadors

**Comment by evankanderson** [comment]
(TOC thinks this is probably more of a Steering responsibility)

**Comment by csantanapr** [comment]
Also the info that shows up here https://landscape.cncf.io/summary

**Comment by evankanderson** [comment]
Is steering going to take this on, or does TOC need to do this?

**Comment by lance** [comment]
Fixed in https://github.com/cncf/landscape/pull/3110
