### ISSUE TITLE
Develop vendor-neutral training materials

### ISSUE THREAD

**Issue by pmorie** [knative/community#120]
There should be vendor-neutral training materials for use by people learning Knative.

This is important for the growth of our community and has been a request to steering / TOC.

**Comment by vaikas** [comment]
Let's see if we can at least add some pointers to some of the documentation on the vendor / blogs, etc. for now that is not vendor specific, but where the content is applicable to Knative proper.
More help is coming right about.

**Comment by vaikas** [comment]
@omerbensaadon @csantanapr 
I think much of the work you've been doing has been touching on some of these, just wanted to raise it to your attention.

**Comment by omerbensaadon** [comment]
oh sweet, yeah we can close this once we ship the Getting Started guide as part of 0.24
