### ISSUE TITLE
[SC] Add new members to steering committee

### ISSUE THREAD

**Issue by csantanapr** [knative/community#1219]
The following updates need to be done 

- Add @salaboy and @nainaz as new members
- Remove @vaikas, @pmorie and @thisisnotapril 

- [x] [peribolos](https://github.com/knative/community/tree/main/peribolos) for both knative and knative-sandbox 
- [x] groups for mailing lists
  - https://github.com/knative/community/blob/main/groups/committee-steering/groups.yaml
  - https://github.com/knative/community/blob/main/groups/groups.yaml#L60
- [x] [CNCF Project maintainers](https://github.com/cncf/foundation/blob/main/project-maintainers.csv)
- [x] CNCF Knative Project JIRA access
- [x] CNCF Knative maintainers group list

**Comment by csantanapr** [comment]
@lance 
Please see if there are other places need to be updated

**Comment by lance** [comment]
> @lance Should we do small blog post in knative.dev like the one from last year [2021](https://knative.dev/blog/steering/2021-12-14-steering-elections-results/) Maybe we do the blog once we select the new end user representative to the steering committee

Yes - that's a good idea, and I agree... let's wait until the end-user seat is filled.

**Comment by csantanapr** [comment]
Opened PR for cncf https://github.com/cncf/foundation/pull/475

**Comment by csantanapr** [comment]
I opened two CNCF Service Desk JIRA tickets @lance 

- [Please add/remove moderators to cncf-maintainers@lists.cncf.io](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1525)
- [Remove and Add members to Knative CNCF Service Desk for Knative](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1524)

cc @salaboy @nainaz

**Comment by csantanapr** [comment]
PR merged https://github.com/cncf/foundation/pull/475

**Comment by csantanapr** [comment]
>CNCF Knative maintainers group list
Resolved

**Comment by csantanapr** [comment]
> CNCF Knative Project JIRA access
Resolved
