### ISSUE TITLE
Do we keep the Google Allstar Prod bot?

### ISSUE THREAD

**Issue by psschwei** [knative/community#1234]
We had a couple of issues opened today by a Google bot:

https://github.com/knative/docs/issues/5365
https://github.com/knative-sandbox/func-tastic/issues/20

This triggered a discussion about whether we should keep it or not?

**Comment by evankanderson** [comment]
I'm not sure where the policy is defined, but I tend to agree that we shouldn't be keeping binaries checked in to our source control:

* It's hard to review / audit these commits
* They will tend to bloat the repo (hard to undo what's done, but at least avoid adding more and possibly remove the ones already there.
* We'd need to build new automation for publishing these into the repo (vs using GitHub releases or our existing publish-to-GCS mechanisms)

**Comment by csantanapr** [comment]
>but I tend to agree that we shouldn't be keeping binaries checked in to our source control
+1 on this.

The repo should not have any binary files, for the examples shared with `*.jar` this can be downloaded by user actions very common for maven wrapper jars

**Comment by psschwei** [comment]
Docs fix: https://github.com/knative/docs/pull/5366

**Comment by evankanderson** [comment]
This seems to have configuration in https://github.com/knative/.allstar

**Comment by thisisnotapril** [comment]
I sent a follow-up today to our Github team to get this org delisted as a Google-owned org so that the bot shouldn't be doing its thing. I will keep you posted! In the meantime you are welcome to delete and ignore as needed.

**Comment by thisisnotapril** [comment]
Apologies for the delay; things got a little hectic here. :) 
If you remove the google-admin user and Googlebot, this should do the trick and remove the others. We prefer the org owners to do this since it is not our org anymore. If you run into any issues with this, please let me know!
