### ISSUE TITLE
./hack/update-codegen.sh doesn't do anything

### ISSUE THREAD

**Issue by kauana** [knative/community#1238]
After adding my github handle to both `peribolos/knative.yaml` and `peribolos/knative-sandbox.yaml`, when I run `./hack/update-codegen.sh`, it says that it has added me to both `peribolos/knative-OWNERS_ALIASES` and `peribolos/knative-sandbox-OWNERS_ALIASES`, but nothing changes.

Steps to reproduce:
1. Add a new github handle to `members` in `peribolos/knative.yaml` and `peribolos/knative-sandbox.yaml`
2. Run `./hack/update-codegen.sh`
 - You should see the following output:
```
➜ ./hack/update-codegen.sh
2022/12/16 09:20:10 Wrote peribolos/knative-OWNERS_ALIASES
2022/12/16 09:20:10 Wrote peribolos/knative-sandbox-OWNERS_ALIASES
```
 - Then, running `git status` repots that no files were changed. 
 - If you open the files and search for the new handle, you can confirm it hasn't been added.

**Comment by psschwei** [comment]
If you're just adding yourself as a member, I don't think there should be any update to the aliases files (those would only update if you were being added as a reviewer / approver / etc.)

**Comment by kauana** [comment]
Hmmm, I heard that we *do* need to run it [here](https://github.com/knative/community/pull/1232).

**Comment by psschwei** [comment]
There were no updates to the aliases files when you ran the script, which is expected when you're just adding yourself to the member list (see [here](https://github.com/knative/community/pull/1225) for a similar request that was merged).

The output of the script in this case is a bit misleading, saying that it wrote to the alias files when no change was actually made. Might be useful to update the script to say something like "no changes made" in this type of scenario...

**Comment by kvmware** [comment]
Also, documenting the ^ above explanation somewhere would be good.

**Comment by aliok** [comment]
/label "help wanted" 

Can somebody add "help wanted" label to this ticket please? So that it shows up in https://clotributor.dev/search?project=knative

**Comment by Bisht13** [comment]
@aliok Just confirming, I need to print something like, no changes made, if the file is not being updated right?

**Comment by kvmware** [comment]
@Bisht13 sometimes it will write to the files and thus should retain that message but other times when adding a member that does not change those files it should suppress those messages and just say "No changes needed for peribolos/knative-*-OWNERS_ALIASES".

**Comment by Bisht13** [comment]
> @Bisht13 sometimes it will write to the files and thus should retain that message but other times when adding a member that does not change those files it should suppress those messages and just say "No changes needed for peribolos/knative-*-OWNERS_ALIASES".

I made the requested changes and opened a PR ✨
