### ISSUE TITLE
We should promote Knative Adopters more & engage users to get listed

### ISSUE THREAD

**Issue by zroubalik** [knative/community#1251]
I believe that one of the most effective ways to attract new users to the Knative community is by highlighting the success and adoption of existing users. There are 2 things we can do:

1. I propose adding a page to our website that prominently features logos (and testimonials) from companies and organizations that have adopted Knative. This will not only showcase the diverse range of industries and use cases that Knative is applicable to, but also serve as a powerful endorsement to potential new users. 
 The current https://github.com/knative/community/blob/main/ADOPTERS.MD file is not enough and quite hidden. I have already opened an issue to track this: https://github.com/knative/docs/issues/5388
2. We (community) should encourage all current Knative users to reach out to us and provide their information to be featured on this page. Following issue is a good first step, I really like the template: https://github.com/knative/community/issues/696 
 Though we should be more proactive in this, for example if a person opens an issue, a PR, a discussion or just post a question on Slack, we should reach out to him and ask him to get listed on our website. The community should be more active here.
 The issue here is how do we communicate this within the community, so everybody is aware of this initiative?

**Comment by csantanapr** [comment]
Good initiative @zroubalik 

How about for item 2 we update the github templates (PR or Issue) anyone making a contribution (ie opening an issue or contributing code). Have a short question "Is your organization already listed in [ADOPTERS.md](https://github.com/knative/community/blob/main/ADOPTERS.MD)?"

**Comment by zroubalik** [comment]
> How about for item 2 we update the github templates (PR or Issue) anyone making a contribution (ie opening an issue or contributing code). Have a short question "Is your organization already listed in [ADOPTERS.md](https://github.com/knative/community/blob/main/ADOPTERS.MD)?"

I like this!

**Comment by dprotaso** [comment]
From ToC meeting - we could repurpose the 'About' section to include adopters etc.

https://knative.dev/docs/about/testimonials/

**Comment by aliok** [comment]
@knative/productivity-leads 

Is there a central place where we can push the issue templates to all repositories?

**Comment by aliok** [comment]
cc @kvmware @upodroid

**Comment by upodroid** [comment]
You should be able to create one in the knative/.github repo and it will appear on every repo that doesn't have an issue template.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by aliok** [comment]
I was looking for a way to give instructions to users on how to add themselves as adopters, but within repositories other than `knative/community`.

My [comment above](https://github.com/knative/community/issues/1251#issuecomment-1638489508) is confusing, sorry.

I don't think there's any other way than just having a text like following at the top of each template across all repositories:

"Are you using Knative? If you do, [we would love to know](https://github.com/knative/community/issues/new?assignees=&labels=kind%2Fdocumentation%2Csize%2FS&projects=&template=ADOPTERS.yaml&title=%5BADOPTERS%5D%3A+%24%7BCOMPANY+NAME+HERE%7D)!"

I will create manual PRs for this.

**Comment by aliok** [comment]
I've added some Markdown comments in issue+PR templates for the Eventing repo: https://github.com/knative/eventing/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug.md&title=

Unless anyone has any better ideas, I will do it for other repos too.

**Comment by aliok** [comment]
I go and check if automating this possible. Related: https://github.com/knative/community/issues/1251#issuecomment-1643559447

**Comment by aliok** [comment]
@upodroid I've created this one: https://github.com/knative-extensions/.github/pull/252

Let's get that one merged first, and then I will update some repositories' templates manually (like Serving) as they already have issue/pr templates and my understanding is that they won't be overwritten.

**Comment by aliok** [comment]
/close

Here's what's done:
- We have the adopter form
- We have links to the adopter form in issue/PR templates
- We do track potential adopters like we do here: https://github.com/knative/community/issues/1359
- We want to show rotating logos of adopters in the website, but it has a separate ticket: https://github.com/knative/community/issues/1416
- We (SC+TOC) will have a rolodex for contacts we made in a _private_ Google Sheet
