### ISSUE TITLE
New Repo: knative/.artifacthub

### ISSUE THREAD

**Issue by dsimansk** [knative/community#1258]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

~Org: knative-sandbox~
Org: knative

~Repo: catalog~
Repo: .artifacthub

Purpose (Description):

The `$REPO` repository should accommodate the metadata for publishing client's plugin to ArtifactHub. Currently we've asked for a new artifact type `Knative Client Plugin`. That can be extended in the future for other Knative resources e.g. `Knative Eventing Source`. 

https://github.com/artifacthub/hub/issues/2714

Sponsoring WG:
Client WG

## Actions to fulfill

This area is used to track the [repo creation process](https://github.com/knative/community/blob/main/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review. You are responsible for moving your entry on the board to "Needs Discussion" or "In Progress" as you move forward in this checklist.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [x] Send a PR adding entries for this repo in [`/peribolos/knative-sandbox.yaml`](https://github.com/knative/community/blob/main/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  - [x] Grant the sponsoring WG the `write` privilege.

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [x] Ask Steering to add the repo to EasyCLA in [Slack](https://knative.slack.com/archives/CU9DGL4FM).

- ~(golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/docs/pull/4160)).~

- [x] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo main
  ```

- [x] Add your GitHub ID to the `OWNERS` file for your repo.

- [x] [Set up](https://github.com/knative/test-infra/blob/main/guides/prow_knative_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge) prow for a new repo

- [x] Bootstrap your CI jobs using [hack](https://github.com/knative/hack) project (look at other sandbox repos for reference)

- [x] Create a sample PR to verify Prow (e.g., edit the boilerplate README)

- [x] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

- [ ] (optional) Send a PR adding the repo to [knobots](https://github.com/knative-sandbox/knobots).

**Comment by psschwei** [comment]
+1

**Comment by zroubalik** [comment]
+1

**Comment by dprotaso** [comment]
Some thoughts

1. Should we make this a top level repo
2. Should we make the repo name specific to artifact hub
3. Should we prefix the repo name with `.` to indicate it's more for metadata

ie. `knative/.artifacthub`

**Comment by dsimansk** [comment]
> ie. `knative/.artifacthub`

I like the idea of having it more prominent with main `knative` org and more specifically named. No strong preference to the `.` prefix.

/cc @rhuss any thoughts on the Catalog FT and consequences?

**Comment by psschwei** [comment]
I'm of the same opinion as @dsimansk on all three points.

**Comment by dsimansk** [comment]
`knative/.artifacthub`

@evankanderson @zroubalik wdyt about Dave's proposal?

**Comment by zroubalik** [comment]
> Some thoughts
> 
>     1. Should we make this a top level repo (ie. knative org)
> 
>     2. Should we make the repo name specific to artifact hub
> 
>     3. Should we prefix the repo name with `.` to indicate it's more for metadata
> 
> 
> ie. `knative/.artifacthub`

agree with 1. and 2. no strong preference on the point 3. The dot in the name is a little bit odd to me, but that might be just me 😄

**Comment by lance** [comment]
> > Some thoughts
> > ```
> > 1. Should we make this a top level repo (ie. knative org)
> > 
> > 2. Should we make the repo name specific to artifact hub
> > 
> > 3. Should we prefix the repo name with `.` to indicate it's more for metadata
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ie. `knative/.artifacthub`
> 
> agree with 1. and 2. no strong preference on the point 3. The dot in the name is a little bit odd to me, but that might be just me 😄

I agree with all three, given that we have precedent with the `knative/.github` repo.

**Comment by evankanderson** [comment]
I'm fine with either; I think the suggestion in the TOC meeting was that `.artifacthub` could avoid confusion as to whether the GitHub repo or the Artifacthub website was the official interface for APIs, etc.  (A bit like the `knative.dev` module names vs. `github.com/knative` repo paths -- it gives some freedom to move things later.)

**Comment by zroubalik** [comment]
https://twitter.com/cncfartifacthub/status/1622584452223275008

Is this somehow related?

**Comment by psschwei** [comment]
looks like it:  [issue](https://github.com/artifacthub/hub/issues/2714) and [PR](https://github.com/artifacthub/hub/pull/2730) for adding knative

**Comment by evankanderson** [comment]
The person who creates the repo gets to choose to dot or not to dot.

(approved for either case)

**Comment by rhuss** [comment]
I'm against a leading dot as this will hide your repository from `ls` on your local checked-out copy. Not sure even why people have even created `knative/.github` which has the same issue.
