### ISSUE TITLE
[SC] Add new member Adolfo to steering committee

### ISSUE THREAD

**Issue by csantanapr** [knative/community#1265]
The following tasks need to be done 

- Add @puerco as new member
- Remove @itsmurugappan 

- [x] Add new member in [STEERING-COMMITTEE.md](https://github.com/knative/community/blob/main/STEERING-COMMITTEE.md)
- [x] [peribolos](https://github.com/knative/community/tree/main/peribolos) for both knative and knative-sandbox 
- [x] groups for mailing lists
  - https://github.com/knative/community/blob/main/groups/committee-steering/groups.yaml
  - https://github.com/knative/community/blob/main/groups/groups.yaml#L60
- [x] [CNCF Project maintainers](https://github.com/cncf/foundation/blob/main/project-maintainers.csv)
- [x] CNCF Knative Project JIRA access (via [cncf service desk](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1) Jira ticket)
- [x] CNCF Knative maintainers group list (via [cncf service desk](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1) Jira ticket)
- [x] New Blog post welcoming recent members @nainaz @salaboy @puerco to Steering Committee (Use [Example](https://knative.dev/blog/steering/2021-12-14-steering-elections-results/))

**Comment by csantanapr** [comment]
@nainaz @salaboy I think this would be a good issue to work on as new members of steering to learn how to onboard a new member when the times come for me to step down and let other lead the way.

/assign @salaboy @nader-ziada

**Comment by salaboy** [comment]
Also this to CNCF: https://github.com/cncf/foundation/pull/509

**Comment by salaboy** [comment]
@csantanapr @nainaz do you folks have access to the Jira server? It looks like I don't have access with my salaboy at gmail account... which might maybe means that I also need to be added there :)

**Comment by csantanapr** [comment]
My bad @salaboy I included the wrong link, use this one [cncf jira service desk portal](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1)

**Comment by salaboy** [comment]
Jira issues created: 
- https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1678
- https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1677

**Comment by lance** [comment]
@csantanapr - I took a look at the items that were outstanding (issues in CNCF Jira and peribolos). It seems like things are good and this issue can be closed. WDYT?
