### ISSUE TITLE
Take ownership of `knative-samples` project

### ISSUE THREAD

**Issue by dprotaso** [knative/community#1288]
The community doesn't have control of the `knative-samples` project. I believe it's still owned by Google and it would be great to have this project transferred to the community. 

There's lots of documentation referencing these images - ie. https://github.com/knative/docs/issues/5440

And the images are big - so it would be nice to redo them

/assign @thisisnotapril

**Comment by dprotaso** [comment]
Bump @thisisnotapril is this something you can help with?

**Comment by evankanderson** [comment]
Should we rebuild these images and move them to `ghcr.io`?

**Comment by dprotaso** [comment]
> Where is it currently hosted?

gcr - but we don't have access to the project

**Comment by dprotaso** [comment]
Looks like `knative-samples` disappeared

> crane manifest gcr.io/knative-samples/helloworld-go
Error: fetching manifest gcr.io/knative-samples/helloworld-go: GET https://gcr.io/v2/knative-samples/helloworld-go/manifests/latest: DENIED: Permission denied for "latest" from request "/v2/knative-samples/helloworld-go/manifests/latest".
