### ISSUE TITLE
Create repo: `knative/toolbox`

### ISSUE THREAD

**Issue by cardil** [knative/community#1291]
## Repo information

Org: `knative`

Repo: `toolbox`

Golang module: `knative.dev/toolbox`

Purpose (Description): House the Knative tools used across the CI/CD and for other development purposes. Those tools are used in Knative, but may be helpful in other projects (for ex.: `buoy` may be useful in other projects as well).

Sponsoring WG: Productivity

More information: https://github.com/knative/test-infra/issues/3721

## Actions to fulfill

This area is used to track the [repo creation process](https://github.com/knative/community/blob/main/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/43) for review. You are responsible for moving your entry on the board to "Needs Discussion" or "In Progress" as you move forward in this checklist.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [x] Send a PR adding entries for this repo in [`/peribolos/knative.yaml`](https://github.com/knative/community/blob/main/peribolos/knative.yaml). Please mind the alphabetical order when adding to a list.
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  - [x] Grant the sponsoring WG the `write` privilege.

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [x] Ask Steering to add the repo to EasyCLA in [Slack](https://cloud-native.slack.com/archives/C04LQCW0C03/p1676466607624469).

- [x] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths (https://github.com/knative/docs/pull/5460).

- [x] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo main
  ```
  PR: https://github.com/knative/toolbox/pull/3

- [x] Add your GitHub ID to the `OWNERS` file for your repo.

- [x] [Set up](https://github.com/knative/test-infra/blob/main/guides/prow_knative_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge) prow for a new repo https://github.com/knative/test-infra/pull/3772

- [x] Bootstrap your CI jobs using [hack](https://github.com/knative/hack) project (look at other sandbox repos for reference)

- [x] Create a sample PR to verify Prow (e.g., edit the boilerplate README)

- [x] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

- [ ] (optional) Send a PR adding the repo to [knobots](https://github.com/knative-sandbox/knobots).

**Comment by cardil** [comment]
PR opened: https://github.com/knative/community/pull/1293

**Comment by evankanderson** [comment]
The goal is to separate the infrastructure _configuration_ (`infra`) and encapsulated command-line tools (`tools`).

Random bikeshed: not clear whether `tools`  or `dev-tools` would make it more clear that these tools are contributor-focused.

The goal is to archive the `test-infra` repository at the end of the process.  Dave suggests that we might prefer to migrate `test-infra` to `infra` instead of archiving `test-infra`.

👍  from Evan, Dave, Zbynek on `tools` repo.

**Comment by cardil** [comment]
@evankanderson regarding the proposed Go package `knative.dev/tool` (in singular).

I think it's doable, looking at this change: https://github.com/knative/docs/pull/4160

I also think it should be obvious `knative.dev/tool/*` refers to `knative/tools` repo. 

Furthermore, I proposed that, as it gives us nice paths when using those tools. For example:

```shell
$ go run knative.dev/tool/buoy@latest --help
```

**Comment by evankanderson** [comment]
I'm still not convinced that making the singular / plural name change is worth it.  This is colored by my experience with the Gatewaies API, I'll admit.

**Comment by dsimansk** [comment]
One other idea to the naming topic. What about `toolbox`. With such a name there's no need to distinguish singular / plural in the import path and repository name.

**Comment by cardil** [comment]
I changed the proposal to `knative/toolbox`, as discussed in TOC meeting.

**Comment by cardil** [comment]
Done
