### ISSUE TITLE
We should add more clear definition for the knative-sandbox 

### ISSUE THREAD

**Issue by vaikas** [knative/community#130]
A question has come up a few times about the role that knative-sandbox plays. I know it's been discussed but seems like we never produced a more comprehensive description for it's role, what goes there and why instead of knative org, what is the process for moving things from sandbox to knative, etc.. Or, I just missed it, in which case we should just make the document easier to discover. 
https://github.com/knative-sandbox

**Comment by evankanderson** [comment]
This is something for Steering to work out, but I think they'd be happy to see references to places where this has worked well in other communities.

**Comment by evankanderson** [comment]
Related: #131

**Comment by evankanderson** [comment]
There were questions at the last TOC meeting about the history of Knative-Sandbox, so I drafted a quick doc:

https://docs.google.com/document/d/1vmzL_DZ6oUr7x3hLq09H6tomeRPPccPdverdngFVJM8/edit#

Mostly, it summarizes what's already written at the start of #23 , but adds some additional "threading the needle" of historical context.

**Comment by evankanderson** [comment]
Paul, can we get this in as an interim step towards nirvana, rather than needing to make things perfect in one go?

**Comment by evankanderson** [comment]
More specifically, I'm asking about converting What to do with Knative-Sandbox](https://docs.google.com/document/d/1e0PpX4uUaaolF7k5p05ZK_ScjpS5VRiK5y8cCg4oH7Q/edit) to markdown and considering it current policy (which can always be amended further if needed).

**Comment by evankanderson** [comment]
Please take a look at the suggested text in #149
