### ISSUE TITLE
add Adobe to ADOPTERS.md

### ISSUE THREAD

**Issue by nainaz** [knative/community#1302]

**Comment by nainaz** [comment]
@puerco is working with @jrsapi.

**Comment by nainaz** [comment]
Need to find another contact person at Adobe for them to create the issue.

**Comment by puerco** [comment]
I'm following up with a couple of other Adobe folks as Joe is on sabbatical right now.

**Comment by satyampsoni** [comment]
can i get the Adobe link?

**Comment by nainaz** [comment]
We have lost contact and they are not using it. 
Closing the issue
