### ISSUE TITLE
Access to KnativeProject Twitter credentials

### ISSUE THREAD

**Issue by nainaz** [knative/community#1304]

**Comment by nainaz** [comment]
We should ask April Kyle Nessi.

**Comment by lance** [comment]
@nainaz I believe this can be closed as completed, right? Closing for now - reopen with details if necessary

**Comment by dprotaso** [comment]
Are the details in 1password?

**Comment by lance** [comment]
@dprotaso I did not add them, but they appear to be there.

![image](https://user-images.githubusercontent.com/15952/231891351-1c3c205a-d684-40d6-a6c2-9549e6594f37.png)
