### ISSUE TITLE
Create a video for CNCF kubecon March 30th

### ISSUE THREAD

**Issue by nainaz** [knative/community#1311]
The deadline to [submit interest](https://forms.gle/jUqt815mWsBxRpCg8) is Friday, March 24, and the deadline to [upload your project update recordings](https://drive.google.com/drive/folders/1eD3Dfl8dvFgc5xtczYMKG4Eem73IY_C1?usp=sharing) is Friday, March 31.
https://drive.google.com/file/d/1a6SKKNQxXa8Fck-yp_aneZVPTaLcwJVf/view?usp=share_link

**Comment by salaboy** [comment]
Ok I've submitted the request showing interest using my name. They requested an individual in the form: 

We need to upload the video here: 
https://drive.google.com/drive/folders/1eD3Dfl8dvFgc5xtczYMKG4Eem73IY_C1

**Comment by salaboy** [comment]
We should get max 5 slides for the end of next week.. so we have time for recording and editing
