### ISSUE TITLE
Find a way to show adopters on knative.dev main page

### ISSUE THREAD

**Issue by nainaz** [knative/community#1317]
Logos or names of adopters on knative.dev site.
Under Trusted By

Add adopters.md under About section on site.

**Comment by nainaz** [comment]
Adopters.md users displayed as projects on cncf website
https://www.cncf.io/

create this as a first issue on docs repo.

**Comment by aliok** [comment]
Should have "good first issue" and "help wanted" labels

**Comment by aliok** [comment]
/close

Duplicate of https://github.com/knative/community/issues/1416
