### ISSUE TITLE
Maintainers Track KubeCon EU 23 slides

### ISSUE THREAD

**Issue by nainaz** [knative/community#1329]
Draft slides: https://docs.google.com/presentation/d/1Z9o04gsDQk2DpeBqAI0PcKtf1wKSGrF0bLV289JrZqk/edit#slide=id.p
Functions:
Pipeline as code
Function scaffolding- compile func locally without doing containers
Demo-Dapr+function
Eventing:
Event mesh concept
Knative kafka components
knative-event plugin
Serving:

Mention other Knative sessions ??

**Comment by nainaz** [comment]
Done

**Comment by dprotaso** [comment]
Assuming you wanted to close this out
