### ISSUE TITLE
Telekom.de using Knative: Find the contact point and add them to Adopters.md

### ISSUE THREAD

**Issue by nainaz** [knative/community#1354]
https://www.telekom.de/start using Knative: The serving parts for their internal "rest services". Motivation was cost-saving, since the services just ran while some batches were executed, which feed data into those. The transition to Knative was easy, and they like it, since it does make things easier for them.

**Comment by dprotaso** [comment]
@nainaz just following up if you've received some contact info

**Comment by dprotaso** [comment]
I reached out to the author of the following blog post on LinkedIn - https://imagefactory.otc.t-systems.com/home/how-to-use-knative-to-deploy-a-serverless-application-on-kubernetes

Will circle back if we get a reply

**Comment by dprotaso** [comment]
Confirmed that they use it internally
