### ISSUE TITLE
Add Hadrian to Adopters.md file

### ISSUE THREAD

**Issue by nainaz** [knative/community#1359]

**Comment by nainaz** [comment]
@pierDipi who is the contact person for Hadrian?

**Comment by dprotaso** [comment]
@nainaz @pierDipi  just following up if you've received some contact info

**Comment by nainaz** [comment]
None. I did not find anyone
Thank you,
-N

**Comment by dprotaso** [comment]
I reached out to https://www.linkedin.com/in/prash7/ on linkedin

**Comment by dprotaso** [comment]
They have Knative in their job postings

**Comment by dprotaso** [comment]
Prash got back to me and confirmed they are using it
