### ISSUE TITLE
Gather information about graduation for Knative Project

### ISSUE THREAD

**Issue by nainaz** [knative/community#1367]
Requirements for Graduation of Knative Project
https://github.com/cncf/toc/blob/main/process/project_proposals.md#graduation-process

Example from Istio: PR: https://github.com/cncf/toc/pull/1000
DD: https://docs.google.com/document/d/1y0WANWSeeWDnF8NZ6NvteTCXxg932uHNBS7VwaD3WRM/edit?usp=sharing 

Example from KEDA: : [PR for KEDA to become a CNCF Graduated project](https://github.com/cncf/toc/pull/925#issuecomment-1559983868)

DD: [KEDA Graduation Due Diligence](https://docs.google.com/document/d/1SiGx5xT_z-mXbs88m4FivdxopdZopR4IWbXV9lX1ugM/edit). Adopter interviews are at the end of the DD document in an appendix.

**Comment by nainaz** [comment]
@aliok can you help us gather information and find us a sponsor?

**Comment by nainaz** [comment]
Ideas for showing Growth:
More case studies
More contributions
More usage
More orgs on adopters.md

**Comment by craigbox** [comment]
If there's anything I can do to help guide you based on my experience with Istio, please let me know.

**Comment by aliok** [comment]
I would want to help the SC with this work.

Can we rename this ticket to something like "gather information about Knative project graduation"? And later we can create an umbrella task for each of the requirements?

I started working on understanding the requirements.

**Comment by aliok** [comment]
@craigbox your help would be very much appreciated, thanks for offering that. We will reach out for sure, once we gather more information about the unknown unknowns :)

**Comment by nainaz** [comment]
@evankanderson know the status of Security Audit.

**Comment by evankanderson** [comment]
We had a meeting about 3 weeks ago with the LF administrators and the audit team, but I haven't heard further updates.

I'll check on it today or tomorrow.

**Comment by craigbox** [comment]
https://knative.dev/blog/events/fuzzing-audit-2023/ ?

**Comment by aliok** [comment]
Here's some content defining the process:

- [Graduation State Criteria](https://github.com/cncf/toc/blob/main/process/graduation-proposal-template.md#graduation-state-criteria)
  - [x] Have committers from at least two organizations.
  - [ ] Have achieved and maintained a Core Infrastructure Initiative Best Practices Badge.
  - [ ] Have completed an independent and third party security audit with results published of similar scope and quality as this example which includes all critical vulnerabilities and all critical vulnerabilities need to be addressed before graduation.
  - (governance)
    - [x] Explicitly define a project governance and committer process.
    - [ ] The committer process should cover the full committer lifecycle including onboarding and offboarding or emeritus criteria.
    - [x] This preferably is laid out in a GOVERNANCE.md file and references an OWNERS.md file showing the current and emeritus committers.
  - (governance)
    - [x] Explicitly define the criteria, process and offboarding or emeritus conditions for project maintainers (those who may interact with the CNCF on behalf of the project).
    - [ ] The list of maintainers should be preferably be stored in a MAINTAINERS.md file and audited at a minimum of an annual cadence.
  - [x] Have a public list of Project adopters for at least the primary repo (e.g., ADOPTERS.md or logos on the Project website). For a specification, have a list of adopters for the implementation(s) of the spec. Refer to FAQs for guidelines on identifying adopters.
  - [ ] Due diligence document


**Once we think we prepared everything above**, we need to start the graduation process by following the steps in:
- [General steps for moving levels: Incubation and Graduation](https://github.com/cncf/toc/blob/main/process/project_proposals.md#general-steps-for-moving-levels-incubation-and-graduation)
- [Graduation process](https://github.com/cncf/toc/blob/main/process/project_proposals.md#graduation-process)

References:
- [CNCF Project Proposal Process](https://github.com/cncf/toc/blob/main/process/project_proposals.md)
- [Graduation proposals from other CNCF projects](https://github.com/cncf/toc/tree/main/proposals/graduation)
- Istio [DD doc](https://docs.google.com/document/d/1y0WANWSeeWDnF8NZ6NvteTCXxg932uHNBS7VwaD3WRM/edit#heading=h.lpilflg9leev), [TOC proposal](https://github.com/cncf/toc/pull/1000/)
- KEDA [DD doc](https://docs.google.com/document/d/1SiGx5xT_z-mXbs88m4FivdxopdZopR4IWbXV9lX1ugM/edit#heading=h.mf5eoko9pfex), [TOC proposal](https://github.com/cncf/toc/pull/925)

**Comment by aliok** [comment]
I actually created a DD myself in the Knative Drive (SC directory) and put some content already: https://docs.google.com/document/d/1BOKa3Jls4w5gsEj5O4-Di0Mf1WCMeLdssG_PVPyF5do/edit

I have some questions in the doc as comments.

Once we answer these questions and reduce ambiguity, let's create separate tickets for each work item we need to do.

In summary, here are the missing parts:

### We need to apply for "Core Infrastructure Initiative Best Practices Badge"

@knative/steering-committee has anybody done anything around https://bestpractices.coreinfrastructure.org/en ?

---

### We need to have a independent and third party security audit

Not sure if the [*fuzzing* audit](https://knative.dev/blog/events/fuzzing-audit-2023/) is enough.

@craigbox, @evankanderson  any idea?

---

### We need to merge https://github.com/knative/community/pull/1390

This PR defines the process of offboarding contributors/approvers.

---

### We might need a process for annual reviewing of SC+TOC members

These members keep their seats for 2 years and then there's a new election. However:
- we might need to shorten the length to 1 year
- OR
- we might need to define an annual process to check if they're still doing their duties.

@jberkus any opinion?

---

### We need to resolve the issues from the [incubation due diligence](https://docs.google.com/document/d/1qPMyIBZ1tBk6WpEMPuLtTrjA6lvbrQ7DvCZb22S0llo/edit)

There's one comment, but I am not sure if there's an actual issue: https://docs.google.com/document/d/1qPMyIBZ1tBk6WpEMPuLtTrjA6lvbrQ7DvCZb22S0llo/edit?disco=AAAAUnuaVKA 

cc @evankanderson

**Comment by aliok** [comment]
cc @jberkus @craigbox 
Anything I missed above?

**Comment by jberkus** [comment]
I'd really like to eliminate the TMC before we apply for graduation.  That's not a CNCF requirement, but it is an internal goal.

Also, since both Ali and I are involved in the project, we'll need to wait for Dawn to come back for a governance review (August).

**Comment by craigbox** [comment]
Istio had already had a professional audit before joining the CNCF, but it was more than 18 months ago, and a second audit was recommended. Our second audit focused primarily on fuzzing. I would imagine that this audit should be fine, but your TOC sponsor can comment. (It looks like this audit was the result of [your CNCF engagement](https://github.com/knative/community/issues/964), so if they say it isn't general purpose enough, I would be asking the TOC to update the CNCF on requirements because it was commissioned in part to meet this requirement.)

Regarding your two-year cadence, I would note the language is _should_ and not _must_; you could say that by design your SC seats seat two year terms, and you're OK with that.

Other things like TAG Security self-assessments (from the incubation DD) governance reviews, etc, are nice-to-haves but I personally believe that the CNCF should codify them as requirements if they are to be so.

**Comment by aliok** [comment]
> Other things like TAG Security self-assessments (offered in the linked comment from the incubation DD), governance reviews, etc, are nice-to-haves, but I personally believe that the CNCF should codify them as requirements if they are to be so.

Are these required for graduation @jberkus ? They're not written in any of these **explicitly**:

- https://github.com/cncf/toc/blob/main/process/graduation-proposal-template.md#graduation-state-criteria
- [General steps for moving levels: Incubation and Graduation](https://github.com/cncf/toc/blob/main/process/project_proposals.md#general-steps-for-moving-levels-incubation-and-graduation)
- [Graduation process](https://github.com/cncf/toc/blob/main/process/project_proposals.md#graduation-process)

**Comment by craigbox** [comment]
> Are these required for graduation @jberkus ? They're not written in any of these explicitly:

TOC is basically a precedent-based organisation.  If you apply and these aren't the law at the time, you won't be held to needing them.  They are good things to have and they may become part of the rules later on.

**Comment by aliok** [comment]
Created a ticket that might need a fix before graduation: https://github.com/knative/community/issues/1407

**Comment by aliok** [comment]
CNCF can help with marketing of Knative's graduation, if we're there by KubeCon NA.

https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/program/project-opportunities/#description-of-opportunities

Look for "PR Support" in the page above.

**Comment by aliok** [comment]
/close
PR opened: https://github.com/cncf/toc/pull/1245. Data collection is over.
Closing this task.
