### ISSUE TITLE
Onboard new TOC member Krsna

### ISSUE THREAD

**Issue by aliok** [knative/community#1369]
The following tasks need to be done 

- Add @kvmware as new member
- Remove @evankanderson  

- [ ] Add new member in [TECH-OVERSIGHT-COMMITTEE.md](https://github.com/knative/community/blob/main/TECH-OVERSIGHT-COMMITTEE.md) https://github.com/knative/community/pull/1368
- [ ] [peribolos](https://github.com/knative/community/tree/main/peribolos) for both knative and knative-sandbox https://github.com/knative/community/pull/1371
- [ ] groups for mailing lists https://github.com/knative/community/pull/1372
  - https://github.com/knative/community/blob/main/groups/committee-oversight/groups.yaml
  - https://github.com/knative/community/blob/main/groups/groups.yaml#L60
- [ ] [CNCF Project maintainers](https://github.com/cncf/foundation/blob/main/project-maintainers.csv)
- [ ] CNCF Knative Project JIRA access (via [cncf service desk](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1) Jira ticket)
- [ ] CNCF Knative maintainers group list (via [cncf service desk](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1) Jira ticket)

**Comment by psschwei** [comment]
In case it helps, I've got a doc in the TOC folder on the shared drive with all the things I had to do when I onboarded

**Comment by kvmware** [comment]
The CNCF parts I think need an existing member or steering. If there is anything else I can do please let me know.

**Comment by aliok** [comment]
Krsna is already in the TOC and  I am guessing after a year, this has been completed.

/close
