### ISSUE TITLE
Sort out knative.team

### ISSUE THREAD

**Issue by evankanderson** [knative/community#137]
Ryan got us a GSuite org. We need to do the following:

* [x] Add new TOC / Steering members to the org
* [x] Get calendar sharing working
* [x] Get team drive working
* [ ] Document setup
* [ ] Update documentation

**Comment by evankanderson** [comment]
Set up time on 6/16 to do this.

**Comment by mattmoor** [comment]
@evankanderson is this a dupe with: https://github.com/knative/community/issues/86

**Comment by evankanderson** [comment]
I think this was part of #86. This was about having the GSuite configuration working to share; I'm going to use #86 for doing the actual cutover.

**Comment by evankanderson** [comment]
/close

Duplicate of #86
