### ISSUE TITLE
Define Case Study Template and Process

### ISSUE THREAD

**Issue by nainaz** [knative/community#1375]
Please review the template and define process to post the case study. 
https://docs.google.com/document/d/1Y40eLubg_yBOOGco74qC7SCdX_Qdh54RoaD5aE_b5a8/edit#heading=h.lrtvy19hlp2a

**Comment by pierDipi** [comment]
@knative/steering-committee @nainaz I've started a simple Google form to help us getting insights for the various sections: https://docs.google.com/forms/d/1asdNOH5sQuAKli5CDTnMZDsugHKMpLDa76OrPUn9X98/edit, can you please take a look and let me know what you think?

**Comment by nainaz** [comment]
Thank you @pierDipi I know asking the user to write that monstrosity of a doc must be painful. So I like that you broke it down

1. We should make Cloud Type required
2. We should add one for Challenges check box field: They could be : Auditing, Compliance, Efficiency, Monitoring, Scaling, , Self-service, Infrastructure, Availability, complexity, Reliability, Abstraction, Communication
3. We should also add Challenge long text (optional) under serving eventing function
4. Also change language to 1-3 main features. Not necessarily they will have 3
5. By the Numbers: - 3x ‘numbers’ required (Example below -- these can also be anecdotes, like estimated 10x faster deployment, increased developer happiness etc.)
6. couple of quotes for highlighting on case study :smile:
7. One diagram easy box architecture diagram but make it optional

**Comment by nainaz** [comment]
@pierDipi Got some more foundational questions that we can ask. 
https://docs.google.com/document/d/1mve5H6dxZO_CtwO2QVMDgl1ll-sISmPkIePpt-FRCc4/edit
Lets see what we can add or what already overlaps

**Comment by nainaz** [comment]
@lance @salaboy @csantanapr @lance Please provide feedback if any on template and/or questionnaire

**Comment by pierDipi** [comment]
@nainaz I've included some foundational questions and your feedback

I'm not sure about what kinda of text I can use for "couple of quotes for highlighting on case study" since it's more for an interview-like process


> One diagram easy box architecture diagram but make it optional

It doesn't let me choose file upload for the question type, so I guess we can ask for a link to a public repository with diagrams?

![image](https://github.com/knative/community/assets/33736985/6e477c06-dcba-45f9-b964-00163740721e)

**Comment by lance** [comment]
I made a few small grammatical changes without comment. Here are a few additional comments on the form.

- Nit: The intro bullet points should either all be sentences with proper capitalization and punctuation or not. Right now, it's kind of a mix.
- Sections 3 and 4 both start with "Knative Serving". The same for "Knative Eventing" and "Knative Functions". Do the second sections for each only appear if the user selects "Yes"? How are required answers for sections handled if the company is not using X component.
- The runtime question in Knative Functions should be checkboxes as companies may be using multiple.

Overall it looks great - thanks for handling this @nainaz and @pierDipi!

**Comment by lance** [comment]
> * Sections 3 and 4 both start with "Knative Serving". The same for "Knative Eventing" and "Knative Functions". Do the second sections for each only appear if the user selects "Yes"? How are required answers for sections handled if the company is not using X component.

I am walking through the form now and realize this is how it works.

**Comment by nainaz** [comment]
Form looks good.
