### ISSUE TITLE
PROCESS CHANGE: WG leads should be in CNCF's maintainers.csv

### ISSUE THREAD

**Issue by aliok** [knative/community#1383]
During https://github.com/knative/community/issues/945 I see TOC and SC members are added to the list in https://github.com/cncf/foundation/blob/main/project-maintainers.csv.

However, we should have more people there.

For example, Istio has different groups (https://github.com/cncf/foundation/blob/main/project-maintainers.csv#L1179):
- Istio: Steering Committee
- Istio: Technical Oversight Committee
- Istio: Working Group Leads
- Istio: Maintainers

We can go with the same structure.

## Expected benefits

- Rewarding the contributors by listing their name there
- Being able to subscribe to maintainers-only things like some newsletters, etc.
- Getting rid of the necessity to prove that I am actually a maintainer in Knative project.

## Expected costs
- More people are listed there - shouldn't cause any issue
- Scripting change

**UPDATE**: see this comment: https://github.com/knative/community/issues/1383#issuecomment-1865809475 . We'll add WG leads and not all approvers.

**Comment by lance** [comment]
> * @lance to lead the discussion for those criteria

I've sent a PR with some language for removal - voluntary and not - in the ROLES.md document here: https://github.com/knative/community/pull/1390. Feedback is welcome - there are a few questions and consider it a WIP until we come to agreement.

**Comment by aliok** [comment]
Update, in SC meeting, we had a vote and agreement for having WG leads in maintainers.csv file as well: https://docs.google.com/document/d/16Rpd2nhmLWrkFJUfpJ31Ox2PpultJ-bYIhqaiWQff_I/edit#bookmark=id.8jsaovwwr9fw

Not all approvers, but WG leads (in addition to SC+TOC members)

Updating the ticket description above.

**Comment by aliok** [comment]
PR https://github.com/cncf/foundation/pull/720

**Comment by dprotaso** [comment]
Going to close this out - I send cmierly@LF an updated list
