### ISSUE TITLE
[ADOPTERS]: Sonavi Labs

### ISSUE THREAD

**Issue by erictg** [knative/community#1384]
### Contact Details

ericsolender@sonavilabs.com

### Company or Organization

Sonavi Labs

### Product or Project

Sonavi Cloud

### Status

- [X] We have a project or product that is in development
- [X] We have a project or product that is publicly available in prerelease form
- [ ] We have a project or product that is in production and publicly available
- [ ] We have a project or product that is in production and used internally

### Where can we learn more?

https://sonavilabs.com/

**Comment by dprotaso** [comment]
cc @knative/steering-committee
