### ISSUE TITLE
How do we extend the community?

### ISSUE THREAD

**Issue by evankanderson** [knative/community#139]
Came up in the 21 May 2020 TOC meeting.

Both [Google](https://github.com/google/knative-gcp) and Triggermesh ([kinesis](https://github.com/triggermesh/aws-kinesis-channel), [azure](https://github.com/triggermesh/azure-event-channel), [aws sources](https://github.com/triggermesh/aws-event-sources), [mq source](https://github.com/triggermesh/mq-eventsource), [vsphere source](https://github.com/triggermesh/vsphere-source), [lambda](https://github.com/triggermesh/knative-lambda-runtime), [aws runtime](https://github.com/triggermesh/aws-custom-runtime), [nodejs runtime](https://github.com/triggermesh/nodejs-runtime), [azure runtime](https://github.com/triggermesh/azure-runtime)) have a bunch of Knative-directed assets that they have built but would like to share with the community.

TOC and Steering should figure out the best way to handle these sorts of **substantial** contributions that probably will continue to be maintained by the vendor, but make them more visible to the larger community, and to feed back input from this larger community to the core WGs when it comes to things like conformance tests and API design.

**Comment by evankanderson** [comment]
/assign @evankanderson @akashrv @isdal @sebgoa 

At a minimum are interested parties. Will try to set up a meeting next week, please add yourself to this issue if you want to participate in the discussion.

**Comment by akashrv** [comment]
Thanks for creating this issue. Here is some more context for the discussion. Eventing enables building a rich ecosystem that is needed to enhance end-users experience and drive knative adoption. Example, we define Source Spec, Broker Spec, Channel Spec (there could be more such as Sink Specs) in core. We expect there to be multiple implementations of these to provide end users with a diverse set of conformant choices. In fact specially for "Sources" I see Knative to be successful if multiple other vendors and product owners start building sources that can expand Knative ecosystem such as PosgreSQL, MongoDB, MySQL, different Cloud provider products etc.
By definition the ones that are part of core is a narrow set - in-memory broker/channel and a couple of K8s sources.
And by definition the ones we are discussing here are NOT vendor neutral. But they can be leveraged by multiple vendors. They are similar to the ones in Eventing Contrib and most of the time are same developers too.
With that here are few topics on my mind to discuss:
- How do we learn from these implementations and improve by knowledge/patterns/design/code sharing?
- How do we encourage more vendors to build more such assets?
- How do we make the conformant ones visible to end users?
- How do we give these assets as well as the contributors more visibility in Knative community?

I would like to hear others' thoughts. Looking forward to the discussion.

**Comment by sebgoa** [comment]
Of the list provided by Evan not all are up to par in terms of quality, but we recently put quite a bit of efforts to get our AWS sources in shape. So if we were to take an example I would point people to:

https://github.com/triggermesh/aws-event-sources

The challenge for us is that if these sources are not part of a "Knative sanctioned" org:

1. Other contributors may not be allowed to contribute from a legal standpoint.
2. Users may not feel that these are "legit"

TriggerMesh is already a top 10 contributor to knative so we feel part of the community, but we also feel that if our code is not "knative sanctioned" then that code is not "legit"

Overall I do think that Knative would indeed benefit by having some growth in terms of contributions.

**Comment by evankanderson** [comment]
I will set up a meeting for next week. Any further interested parties?

**Comment by aijamalnk** [comment]
Hello! My name is Aizhamal, and I recently joined Google's open source team. I'll be working on knative. 
I'd like to join this discussion if possible. Could you add me to the meeting? (aizhamal (at) google).
Thanks!

**Comment by evankanderson** [comment]
/unassign

I haven't had time to work on tihs.

**Comment by bsnchan** [comment]
Ideas:
* Add logos to the website --> maybe figure out a way for people to PR logos to the knative.dev website
* create a community repo that links to other repos (similar to grpc)

**Comment by bsnchan** [comment]
@knative/ux-wg-leads is there a process to have other organizations add their logos to the website at the moment?

**Comment by csantanapr** [comment]
@bsnchan no current process other than the normal process of PRs to submit changes to the website.

**Comment by omerbensaadon** [comment]
There are a couple of low-hanging fruit we need to tackle as UX and I think this could be grouped in with another one: 

https://github.com/knative/ux/issues/35 

We could open an issue in community asking people who have adopted Knative to add a comment (similar to https://github.com/dapr/dapr/issues/3169). 

In that issue, we could also add a bit about adding their logo to the website :)

**Comment by bsnchan** [comment]
Right now the TM committee is working on a "Knative certified badge" for conformance but we could also introduce the idea of "Knative ecosystem" or "Knative friends" in our community.

For Tekton, the process seems lightweight and requires friends to PR into a repo: https://github.com/tektoncd/friends/blob/main/CONTRIBUTING.md

**Comment by vaikas** [comment]
SC thinks there's enough various different efforts that capture these ideas. This issue as it stands is quite open ended, so using more targeted issues would be swell. I'll close this and please reopen more specific issues if they warrant something from the SC.
