### ISSUE TITLE
Explicitly establish who "The Knative Authors" assigns copyright to

### ISSUE THREAD

**Issue by pmorie** [knative/community#141]
We have statements that assign copyright in many files in this project:

```
Copyright <year> The Knative Authors
```

...but it's not clear who that specifically refers to. There is a file in the serving repo that has an (incomplete) list of vendors:

https://github.com/knative/serving/blob/master/AUTHORS

I personally expect that this phrase refers to the community of individuals that develops the project, not the vendors those people work for. I also expect that this is the conventional understanding of what phrases like this mean.

Since the existing formulation is clearly inaccurate, I propose that we explicitly define this phrase to have the conventional meaning.

This is urgent because there are a couple threads that are touching this matter currently in our community:

- Creating sandbox repos
- In-flight proposal for working-group owned repositories outside `knative` org

**Comment by jchesterpivotal** [comment]
> I personally expect that this phrase refers to the community of individuals that develops the project, not the vendors those people work for. I also expect that this is the conventional understanding of what phrases like this mean.

My understanding is this:

1. Copyright originates in a human performing a creative act.
2. It can be transferred contractually to another legal person (which may or may not be a human).
3. That transfer can be automatic.
4. That transferred IP can be transferred again to yet another party.

The status of copyright is then a matter of the facts of (1) who the actual human author was, and (2) what agreements they had made about their creative work. My employment contract automatically renders unto VMware for things I do in pursuit of my employment. In turn VMware has a corporate CLA with Google, who are the custodians.

What's key is that a statement like the one above is not _binding_, it's not a first arbiter of who actually has copyright. I can write a poem and slap "Copyright (c) 3235 Galactic Overlords of Xaxx'nnen", but the copyright still adheres to me because there's no binding agreement saying otherwise.

All of which is to say that yes, we ought to say what we mean by this, and if it's not clear in the current CLAs, it ought to be.

**Comment by vagababov** [comment]
There's golang's example: https://golang.org/CONTRIBUTORS

**Comment by abrennan89** [comment]
Still probably relevant and a question that bothers me since the bottom of knative.dev says "Copyright © 2022 The Knative Authors" - what can be done to advance resolving this?

**Comment by evankanderson** [comment]
The CNCF now owns the copyright and trademark, as those have all been assigned to the CNCF.

I don't know if we need some explicit text mapping "The Knative Authors" ==> CNCF, assigning to steering as they do most of the coordination with CNCF.

**Comment by nainaz** [comment]
Open a ticket with CNCF to get the language clear on who are "Knative Authors".

**Comment by puerco** [comment]
I asked @jorydotcom to get an authoritative answer. Apart from that, I think [this paragraph from the Open Source Casebook](https://google.github.io/opencasebook/authorship/#:~:text=United%20States%20copyright,the%20undivided%20whole.) answers the question of the collective copyright:

> United States copyright law only recognizes two forms of property interest to the copyright rights for that granular work: single-author authorship and joint authorship. The rights to works authored by a single author vest in a single entity. The rights to works authored by joint authors are shared by the joint authors, with each joint author enjoying an equal interest in the undivided whole.

(Of course IANAL!)

**Comment by nainaz** [comment]
I have no idea what to make of this?
It means there could be no collective author?
It has to be individuals.
But it is possible that there might a be a possibility of once you have
posted it in CNCF, CNCF has the right to use it
Thank you,
-N

**Comment by nainaz** [comment]
Delete Knative Authors file https://github.com/knative/serving/blob/main/AUTHORS
Add  "and others that have contributed code to the public domain." to LICENSE.md

**Comment by puerco** [comment]
Opened https://github.com/knative/community/pull/1429 and https://github.com/knative/serving/pull/14350 yo follow up on this.

**Comment by dprotaso** [comment]
> Add "and others that have contributed code to the public domain." to LICENSE.md
Public domain in my mind has a very specific meaning that no one holds the copyright anymore

Technically the CLA we sign donates the code to the CNCF foundation - https://github.com/cncf/cla

**Comment by puerco** [comment]
My understanding is that "The Knative Authors", ie all the contributors to the project, collectively hold the copyright of the code. By signing the CLA you grant the CNCF a license to use your code for whatever they want with it, but the authors still own the copyright, so it should stay. But I'd defer to someone with real legal understanding of these.

**Comment by aliok** [comment]
I just found some information about the copyright notices in CNCF repositories: https://github.com/cncf/foundation/blob/main/copyright-notices.md

https://github.com/knative/community/issues/141#issuecomment-1714497006
> Note: we have knative authors all over our header files and on the website - would be good to know if that changes or we define it as an alias for the CNCF foundation?

Apparently, this is not needed at all, according to my understanding of the document above.

This doesn't mean that we don't need to define who "The Knative Authors" are.

**Comment by dprotaso** [comment]
Nice - looks like we can drop the year

**Comment by nainaz** [comment]
With all this discussion, still not sure what to do here?

**Comment by jorydotcom** [comment]
Firstly, my apologies to @puerco who reached out some time ago via email. In the course of my New Year's inbox I (re?)discovered his message, and figure a late reply is better than no reply at all.

I think this issue can be closed. The Copyright Notice is not an assignment of copyright. It is a notice of who holds the copyright, which is licensed under the terms of your license.md. CNCF does not hold the copyright, the project contributors do; the CLA gathers your agreement as a contributor to make the license grants necessary for the foundation to manage and distribute those contributions.

Your copyright notice follows standard procedure for OSS and adhere to the Foundation's [guidance to its projects for copyright notices](https://github.com/cncf/foundation/blob/main/copyright-notices.md). The LF has an [OS Licensing Training](https://training.linuxfoundation.org/training/open-source-licensing-basics-for-software-developers/) as well that I would encourage anyone to review to learn or refresh their knowledge of licensing and notice practices. If you feel that the term "Knative Authors" implies too much specificity, then you may want to amend the notice to "Copyright Contributors to the XYZ project." 

If there are still questions on this topic, I would recommend reaching out to CNCF's counsel, Joanna Lee.

**Comment by evankanderson** [comment]
It looks like "the Knative Authors" == "the CNCF / Linux Foundation".
