### ISSUE TITLE
Add SVA Case study link published on CNCF site on Knative.dev

### ISSUE THREAD

**Issue by nainaz** [knative/community#1418]
Add SVA Case study on Knative website:
Link to the study:
https://www.cncf.io/case-studies/system-vertrieb-alexander-gmbh/

Case studies can be found here: 
https://github.com/knative/docs/tree/main/docs/about/case-studies
Needs to be added to [docs/config/nav.yml]

**Comment by satyampsoni** [comment]
Is this issue still relevant?

**Comment by aliok** [comment]
To be fixed by https://github.com/knative/docs/pull/5868
