### ISSUE TITLE
Status of UX WG

### ISSUE THREAD

**Issue by aliok** [knative/community#1422]
@Cali0707 and @Leo6Leo are reactivating this WG, and I am helping out.

@Cali0707 organized a meeting with designers and professors from [OCAD University](https://www.ocadu.ca/) where we talked about how to enable designers to contribute to Knative, and what can they contribute.

There are already very good ideas.

The meeting notes are here: https://docs.google.com/document/d/1VCObP1IQFPDGzGG5KIgytQwX7RrU0tyeB7FGjkY0pPk/edit

We've created a new Slack channel, #knative-ux.

@Cali0707 will set up a recurring meeting.

I think it would be great if we make this official.

Currently, we have a [Docs + UX WG](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#documentation--user-experience) listed in Knative WGs.

Although this group currently is not working on any documentation related tasks, it would be nice to have the UX activities part of this WG.

It would be nice to:
- Give relevant people triage and approve permissions (@Cali0707 , @Leo6Leo; and perhaps @evankanderson and @aliok) so that we don't have to bug folks. Current approvers are @csantanapr and @omerbensaadon .
  - If we don't want to go this route because this is against the [written rules in the governance,](https://github.com/knative/community/blob/main/ROLES.md#requirements-2), we should at least make sure SC members (I believe they can approve accros all repos) are responsive to PR review requests.
- Update the [community meeting times](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#documentation--user-experience), with the new WG meeting times. (so, basically, using the new initiative meeting as the WG meeting)
- Clarify if @csantanapr , @omerbensaadon  and @snneji (listed as [current lead](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#documentation--user-experience)) are interested in participating. 

@Cali0707 , @Leo6Leo 
Based on this, let's try to use all the existing stuff written here: https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#documentation--user-experience:
- Google Drive
- Meeting notes
- Zoom
- GitHub project board
- ...

Or, update them with new information.

**Comment by Cali0707** [comment]
@aliok maybe we can also give triage/approval permissions to someone from OCAD? I can ask them tomorrow if any of them would be interested in taking on that resposibility

**Comment by psschwei** [comment]
Added to TOC board for discussion this week

**Comment by Cali0707** [comment]
@aliok @psschwei there are two designers from the research group at OCAD who have volunteered to help lead this WG (and so should get triage/approval permissions) if this is approved: @zainabhusain227 and @mmejia02

Thanks @zainabhusain227 and @mmejia02 🎉

**Comment by dprotaso** [comment]
+1  - You're good to start with getting all this setup.

My recommendation is to split the [Docs+UX working group](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#documentation--user-experience) and put Docs under `Emeritus Working Groups`

Samia is no longer contributing so I'd add her, Ashleigh & Sam as Emeritus Leads. Omer and Carlos would be Emeritus Leads for UX.

**Comment by aliok** [comment]
cc @knative/steering-committee
