### ISSUE TITLE
Create knative-sandbox repo named `eventing-kafka-broker`

### ISSUE THREAD

**Issue by Harwayne** [knative/community#143]
Create knative-sandbox repo named `eventing-kafka-broker`.

As #125 has not yet been merged, there is no defined process for creating sandbox repos. It was suggested that we create an issue here instead.

The main purpose of the new repo is to experiment with alternative implementations of integrating Kafka into knative. For example, using Java rather than Go. It is expected to be distinct enough from the existing implementation in https://github.com/knative-sandbox/eventing-kafka that it will be much easier to allow the two to evolve independently.

**Comment by matzew** [comment]
@evankanderson any chance we can get the repo for our student ?

**Comment by evankanderson** [comment]
I can try to take this on this evening, assuming that no one else on the ToC raises an objection.

**Comment by slinkydeveloper** [comment]
@evankanderson any updates on that one?

**Comment by evankanderson** [comment]
Sorry -- was waiting on #130 to finish. I'll create this today.

**Comment by evankanderson** [comment]
@slinkydeveloper or others following: you can `/lgtm` the website PR if you want. I think the Prow jobs need someone from test-infra to `/approve`

**Comment by evankanderson** [comment]
Thanks for the PRs!

I'd like to wait for https://github.com/knative/test-infra/pull/2222 before starting to use the new repo, but I'll take a look at the peribolos changes.

**Comment by evankanderson** [comment]
It looks like this is complete, and we have PRs that have merged.

/close
