### ISSUE TITLE
Revisit the need to bundle the LICENSE files in `third_party` folder

### ISSUE THREAD

**Issue by cardil** [knative/community#1441]
## Background

We run [`google/go-licenses`](https://github.com/google/go-licenses) tool's _save_ command in every repo. It bundles the `LICENSE` files of the dependencies, or their code, depends on the license itself. This has been the practice of the project since Knative inception. The requirements were coming from Google's OSPO office.

The CNCF has those 2 pages on the licenses:

- https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy
- https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md

Despite that, the [CNCF Allowlist License Policy](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#cncf-allowlist-license-policy) mentions that non-apache deps should be held in a designated third-party folder, such practice is very uncommon among the CNCF projects.

- https://github.com/etcd-io/etcd
- https://github.com/istio/istio
- https://github.com/coredns/coredns
- https://github.com/envoyproxy/envoy (has the third-party folder to hold some Android C header files)
- https://github.com/argoproj/argo-cd
- https://github.com/kedacore/keda
- https://github.com/fluent/fluentd
- https://github.com/prometheus/prometheus

I did find only the https://github.com/kubernetes/kubernetes actually holds some third-party components in a designated folder (not only the LICENSE files)

## Question

Is the current practice really required by CNCF? Maybe we can drop it like most projects do?

## Links

This follows up the discussion in https://github.com/knative/hack/issues/315
Related to https://github.com/cncf/foundation/issues/642

**Comment by evankanderson** [comment]
See discussion in https://github.com/cncf/foundation/issues/642

**Comment by dprotaso** [comment]
> After the upgrade to go 1.21 that introduced "toolchain",

Is there a reason to specify the [toolchain directive](https://go.dev/ref/mod#go-mod-file-toolchain) over [go directive](https://go.dev/ref/mod#go-mod-file-go)?

**Comment by rhuss** [comment]
> Is there a reason to specify the [toolchain directive](https://go.dev/ref/mod#go-mod-file-toolchain) over [go directive](https://go.dev/ref/mod#go-mod-file-go)?

I don't think so. We haven't added `toolchain` manually to `go.mod`, but it was introduced by `./hack/update-deps.sh` for some reason. We don't actively use toolchain (and nailing everything down to the patch-level is also something we should not do via this mechanism)

**Comment by cardil** [comment]
Okay. Can we agree that we could at least remove the need to bundle all those `LICENSE` files?

Personally, I would keep the check as it, from time to time, actually finds some invalid libs, like https://github.com/knative/client-pkg/issues/166

**Comment by dprotaso** [comment]
> Okay. Can we agree that we could at least remove the need to bundle all those LICENSE files?

Yeah let's update hack to stop saving the licenses - then each repo can delete them

**Comment by cardil** [comment]
This PR does that knative/hack#376

**Comment by dprotaso** [comment]
Serving PRs are out that drop the vendored files
