### ISSUE TITLE
Create LinkedIn company page for Knative

### ISSUE THREAD

**Issue by nainaz** [knative/community#1446]

**Comment by nainaz** [comment]
https://www.linkedin.com/company/knative/
Gave access to all Steering members.

**Comment by Cali0707** [comment]
Hey @nainaz I noticed that Cilium is posting a linkedin post whenever a new contributor has their first contribution (e.g. https://www.linkedin.com/posts/cilium_new-cilium-contributor-the-newest-activity-7131279867601395712-NXy7?utm_source=share&utm_medium=member_desktop) do you think that this is something we would be able to do?

**Comment by aliok** [comment]
IMO, let's create a separate ticket for that :)

**Comment by Cali0707** [comment]
> IMO, let's create a separate ticket for that :)

Opened here: https://github.com/knative/community/issues/1473
