### ISSUE TITLE
Change DUX -> UX in the TOC Review Schedule

### ISSUE THREAD

**Issue by Cali0707** [knative/community#1460]
Recently, we split the DUX WG into just a UX WG, and moved docs to emeritus (https://github.com/knative/community/pull/1432). I just noticed that when we did this, we did not update the TOC WG Review schedule to reflect these changes.

**Comment by Cali0707** [comment]
cc @knative/technical-oversight-committee

**Comment by psschwei** [comment]
I'd say go ahead and open the PR for this and we can get the relevant approvals there
