### ISSUE TITLE
Proposal: Knative Mascot

### ISSUE THREAD

**Issue by Cali0707** [knative/community#1463]
Hello Knative Community! :wave: 

The UX Working Group (specifically @mmejia02 and @zainabhusain227) have been working hard to create a mascot for Knative! As there has been some existing use of ducks (in reference to duck typing), they are sticking with having a duck as our mascot, and have created a first draft of a duck which is using the Knative colours as well as trying to fit in with the existing CNCF mascots (see [here](https://store.cncf.io/products/phippy-and-friends-decals)).

We would love to collect feedback on the current draft of the mascot, before trying to finalize this and make it into an **official mascot** for Knative. 

So, please comment here with your feedback on the design, or message the UX WG directly at [#knative-ux](https://cloud-native.slack.com/archives/C05MW1AT1T8)

The draft of the mascot so far is:
![knative-logo-v1alpha1](https://github.com/knative/community/assets/65566908/c49e8804-951e-40f8-868d-9ef8d297f2e9)

**Comment by Leo6Leo** [comment]
Do we want to have a brainstorming on what name should we give to this little cute duck? :laughing:

**Comment by dprotaso** [comment]
> Do we want to have a brainstorming on what name should we give to this little cute duck? 😆

Steve

That's usually the name we use when we can't come up with something eg. https://github.com/knative/serving/issues/1397#issuecomment-401161189

**Comment by gabo1208** [comment]
I'll try a few options with a longer beak maybe, but so far it's looking awesome!!

**Comment by adamzr** [comment]
Looks great!

Maybe add a hat?

**Comment by aliok** [comment]
Can we also check with CNCF brand team or designers? They might have some guidelines or something similar.

Sorry that I came up with this suggestion right now, even though I was involved in this matter for a long period.

**Comment by nainaz** [comment]
This is so cute!
Agree with @aliok about checking the guidelines. @aliok can you find out more who we can talk to?

**Comment by Cali0707** [comment]
@aliok @nainaz what I could find from CNCF re: mascots is https://github.com/cncf/foundation/blob/main/phippy-guidelines.md

**Comment by aliok** [comment]
Everything looks great according to the guidelines.

> To get started, please file a ticket with a [Service Desk.](https://servicedesk.cncf.io/)

They say this, but I don't have access to that system (yet).

Can somebody reach out using that system? A second opinion from CNCF would be super nice.

**Comment by mmejia02** [comment]
Hello! Here is an update on the mascot. We have a couple of different versions and it would be great is people could vote on which they like better or if they would like any other alterations :) The pirate hat is meant for a storyboard/illustration we are making at the UX WG.
Here is the SVG:
![steve_versions](https://github.com/knative/community/assets/143516624/98efca62-8b40-4253-bc9e-32e89aae176e)

Thank you all for the comments and feedback so far!!

**Comment by adamzr** [comment]
I like D!

**Comment by aliok** [comment]
I've added this ticket to steering committee meeting agenda.

**Comment by evankanderson** [comment]
I like the non-hat option as the default.  Then we can add hats for various special topics / occasions as necessary.

**Comment by Charley-Mann** [comment]
Hi folks. It's great to see a new mascot joining the CNCF project ranks!
I manage CNCF's content & work on the Phippy program. Graduated projects can donate a Phippy and Friends character to the program and it will be given the creative treatment by CNCF, which includes 3D rendering and producing dedicated swag for the CNCF store. While we don't offer this service for incubating projects, if you would like to donate this character in the future then I'd recommend designing and naming your mascot along the [Phippy guidelines](https://github.com/cncf/foundation/blob/main/phippy-guidelines.md), so that it can seamlessly fit into the program once Knative graduates.

**Comment by nainaz** [comment]
We would  have to get a different name. "Kevin"?

**Comment by nainaz** [comment]
@Charley-Mann we can still use it though right? Once we are following the guidelines?

**Comment by Charley-Mann** [comment]
@nainaz -- of course you can use it! 
On the name, I'm fine with a Phippy character being called Kxxx the Knative duck. There is a duck breed that begins with K ([Khaki Campbell](https://en.wikipedia.org/wiki/Khaki_Campbell)) so you're covered.

**Comment by aliok** [comment]
Name needs to start with a `K` as project name starts with a `K` (CNCF rule).

@knative/ux-wg-leads  will send an email to Knative dev+users mailing lists to get votes.

**Comment by Cali0707** [comment]
React to this comment to vote for option A:

![image](https://github.com/knative/community/assets/65566908/5d512ddd-3f6f-4f14-8b79-836de11c6776)

**Comment by Cali0707** [comment]
React to this comment to vote for option B:

![image](https://github.com/knative/community/assets/65566908/7e67cf49-3d4e-4e4d-b303-f0e02b2b8862)

**Comment by Cali0707** [comment]
React to this comment to vote for option C:

(I'm just using screenshots of the earlier image, so ignore the chopped off letters in this one)

![image](https://github.com/knative/community/assets/65566908/965ba94c-41fd-4b50-9ff6-ca734fd35dbd)

**Comment by Cali0707** [comment]
React to this comment to vote for option D:

![image](https://github.com/knative/community/assets/65566908/68074666-ad79-497f-b17f-0ccf7b027a1e)

**Comment by Cali0707** [comment]
Hi everyone, please react to one of the four options above to vote for our mascot design! If you think that design changes need to be made to any of the options, let us know as well.

As mentioned above, the name of the mascot needs to start with a `K`. Currently, we are thinking of naming it `Kevin`. If you would like to propose a different name, leave a comment as well!

**Comment by psschwei** [comment]
The differences between A, B, and C are so subtle I can't really tell them apart :smile:

**Comment by matzew** [comment]
I like the pirate mascot !

**Comment by octonawish-akcodes** [comment]
I also like the pirate mascot

**Comment by aslom** [comment]
Kevin The Mighty ? :)

**Comment by duglin** [comment]
can we see them smaller & side-by-side... I can't tell the diff between the first 3 LOL

**Comment by AmanSarraf** [comment]
The pirate one

**Comment by salaboy** [comment]
I agree with Evan, we can add hats for special occasions. Kevin sounds ok, but I wonder if a more creative and non real name is used.

**Comment by KauzClay** [comment]
what about Kuack?

**Comment by nainaz** [comment]
I agree with @evankanderson that we should use the duck without accessories as later we can have fun adorning him as per the occasion and talks :D 
Also Piracy might not be seen as a good thing so I agree here with @pierDipi 

Love the name Kuack :D

**Comment by theofpa** [comment]
Knavi

**Comment by wiggitywhitney** [comment]
I like "Kai" for the name because it is more inclusive.

Plus it is just a cool name
(◠‿・)—☆

**Comment by mmejia02** [comment]
![Mascot Versions, side by side](https://github.com/knative/community/assets/143516624/0535a481-f9b8-4840-9150-b5238c1e5a25)
Here is a side by side comparison @duglin @psschwei :)

**Comment by duglin** [comment]
@mmejia02 thanks a ton!

**Comment by salaboy** [comment]
I do agree with @whitneelee Kai is a really good name

 - Blog: http://salaboy.com <http://salaboy.wordpress.com>
 - Github user: http://github.com/salaboy
 - Twitter: http://twitter.com/salaboy

 - Mauricio "Salaboy" Salatino -

**Comment by wiggitywhitney** [comment]
I also think it could be fun to have an 'N' name and put a 'K' in front of it. Like Knathan or Knicholas.

**Comment by dprotaso** [comment]
A nice Polish name that starts with a 'K' is - Kinga

**Comment by aslom** [comment]
Use Admiral-like or Captail-like hat and put K.N. initial on it?

**Comment by zainabhusain227** [comment]
What about Kaptain Kuack?

**Comment by Leo6Leo** [comment]
Kiki

easy to remember and sounds cute.

**Comment by Leo6Leo** [comment]
> What about Kaptain Kuack?

That's a lovely name! But I think in CNCF phippy family, there is already a captain which is "CAPTAIN KUBE"

https://www.cncf.io/phippy/

**Comment by aliok** [comment]
Here's the announcement for Kuack: https://groups.google.com/g/knative-users/c/wHA8c5FDv3k

Thanks for driving this @Leo6Leo and @Cali0707 

Do we have the design files and similar things in GitHub?

**Comment by aliok** [comment]
Or, in general, what's the next step here?

**Comment by Cali0707** [comment]
> Do we have the design files and similar things in GitHub?

Not yet, I wasn't sure if we should PR them to this repo or the UX repo. Any ideas @aliok?

**Comment by aliok** [comment]
I think UX repo is a better place to store the images and source files (or links to the online design systems).

However, let's put the mascot image and the name in the community repo.

**Comment by duglin** [comment]
Not sure if they allow mascots in there, bu there's this repo: https://github.com/cncf/artwork/

**Comment by jasonsmithio** [comment]
We can call him Kuakers or something of the sort.
