### ISSUE TITLE
Is the trademark committee still a thing?

### ISSUE THREAD

**Issue by pierDipi** [knative/community#1478]
We're still mentioning trademark committee
- https://github.com/knative/community/blob/main/TRADEMARK-COMMITTEE.md
- point 4 at https://github.com/knative/community/blob/main/STEERING-COMMITTEE.md#charter

As far as I know, CNCF detains the trademark now and I don't think the committee is still active

cc @knative/steering-committee

**Comment by aliok** [comment]
https://github.com/knative/community/issues/1399

We still have the issue open.

**Comment by pierDipi** [comment]
Closing this one as it's a duplicate of https://github.com/knative/community/issues/1399
