### ISSUE TITLE
Is Knative forward-compatible? 

### ISSUE THREAD

**Issue by cuihao727** [knative/community#1482]
Is Knative forward-compatible? Can version 0.23 be upgraded to version 1.2?

**Comment by ReToCode** [comment]
See https://knative.dev/docs/install/upgrade/.

> Knative supports upgrading by a single [minor](https://semver.org/) version number. For example, if you have v0.21.0 installed, you must upgrade to v0.22.0 before attempting to upgrade to v0.23.0

**Comment by cuihao727** [comment]
> See https://knative.dev/docs/install/upgrade/.
> 
> > Knative supports upgrading by a single [minor](https://semver.org/) version number. For example, if you have v0.21.0 installed, you must upgrade to v0.22.0 before attempting to upgrade to v0.23.0

Thank you for your generous reply. In fact, we encountered a problem with mounting NFS when using Knative v0.23, but PVC was not supported by Knative until v1.2. Is there any way to use NFS in Knative v0.23? If not, how should we evaluate the compatibility risks brought by upgrading Knative?

**Comment by ReToCode** [comment]
Knative supports PVC using a feature flag: https://knative.dev/docs/serving/configuration/feature-flags/#kubernetes-persistentvolumeclaim-pvc. If that will work with NFS as a provider, depends on your Kubernetes installation and your application specifics. So if NFS works for your application on Kubernetes without Knative it should do that as well with Knative.
