### ISSUE TITLE
Clarify process steps for adding new members

### ISSUE THREAD

**Issue by RichieEscarez** [knative/community#15]
We should update the docs to make the path clear for new members who meet the requirements listed here: https://knative.dev/contributing/roles/#member

If a contributor meets the member requirements, what are the next steps?

Do sponsors simply email the steering committee (knative-steering@googlegroups.com) and what information is needed in that request?

**Comment by vaikas** [comment]
@RichieEscarez do you think this is still needing further clarification? I think the only necessary step is to subscribe to knative-dev group?

**Comment by vaikas** [comment]
@RichieEscarez is it ok to close this?

**Comment by vaikas** [comment]
I'm closing this, if there are specific issues that need addressing, please reopen, and give more deets.

**Comment by RichieEscarez** [comment]
I think all the info is now available somewhere across these pages (it definitely was not when I opened this issue - i had contact the TOC for instructions).

But if im being picking, that page nor elsewhere do we explicitly says "do steps X, Y, and Z to join". 

From the top level (just looking at the Left Navigation Menu), the only topic that might indicate to a user about how to join is "Join working groups", which is likely not what they are looking for.
