### ISSUE TITLE
Knative is being added to LFX Insights - any questions/concerns

### ISSUE THREAD

**Issue by aliok** [knative/community#1507]
https://github.com/cncf/toc/issues/794#issuecomment-1930705776

cc @knative/technical-oversight-committee for the technical review about the LFX Insights.

**Comment by psschwei** [comment]
Looks fine to me
+1

**Comment by aliok** [comment]
Ok, +1 from me too!

**Comment by ReToCode** [comment]
Looks nice, is it possible to mark some users as bots? Seems like they are all counted as well: https://insights.lfx.linuxfoundation.org/foundation/cncf/overview?project=knative&bestPractice=false

**Comment by dprotaso** [comment]
+1 from me - lets drop the bots if we can

**Comment by aliok** [comment]
/close

Closing this one as there are no concerns. We already asked in https://github.com/cncf/toc/issues/794 to remove bots and also include `knative-extension`.
