### ISSUE TITLE
Whether there are bugs or security risks when using the following extensions(kubernetes.podspec-affinity,kubernetes.podspec-persistent-volume-claim,kubernetes.podspec-persistent-volume-write) of knative？

### ISSUE THREAD

**Issue by zzuchen** [knative/community#1518]
I am using Krative 1.3 version, and due to the need to set pod anti affinity and PVC, I need to enable kubernetes.podspec-affinity,kubernetes.podspec-persistent-volume-claim,kubernetes.podspec-persistent-volume-write extensions. But in the official documentation, they are set to disabled by default (the official documentation explains that they are in the alpha stage and may have bugs). May I ask what bugs they may have, and has the latest version of knave already resolved these bugs?

**Comment by dprotaso** [comment]
closing dupe of https://github.com/knative/serving/issues/14918
