### ISSUE TITLE
[SC] Add new member Norris (nrrso) to steering committee

### ISSUE THREAD

**Issue by aliok** [knative/community#1520]
The following tasks need to be done.

See the checklist here: https://docs.google.com/document/d/1FltVxL60yV-NFfzQwm-neearM73HSTtGCdI-BUvlEGQ/edit

- Add @nrrso as new member
- Remove @puerco

---

- [x] [STEERING-COMMITTEE.md](https://github.com/knative/community/blob/master/STEERING-COMMITTEE.md)
    - Add to the steering committee table
    - https://github.com/knative/community/pull/1521
- [Peribolos](https://github.com/knative/community/tree/main/peribolos):
    - Add to `admins `and` Steering Committee` groups in:
        - [x] [knative](https://github.com/knative/community/blob/main/peribolos/knative.yaml)
        - [x] [knative-extensions](https://github.com/knative/community/blob/main/peribolos/knative-extensions.yaml)
        - https://github.com/knative/community/pull/1521
    - You will be automatically added to the GitHub teams in the GitHub organizations
- Mailing lists:
    - [x] Add to [steering@knative.team](https://groups.google.com/a/knative.team/g/steering) \[[YAML](https://github.com/knative/community/blob/main/groups/committee-steering/groups.yaml)]
    - [x] Add to [calendar-maintainers@knative.team](https://groups.google.com/a/knative.team/g/calendar-maintainers) \[[YAML](https://github.com/knative/community/blob/main/groups/groups.yaml#L68)]
    - https://github.com/knative/community/pull/1521
- CNCF
    - [ ] Add to [project-maintainers.csv](https://github.com/cncf/foundation/blob/main/project-maintainers.csv)
    - https://github.com/cncf/foundation/pull/760
    - You will be added to a list of CNCF mailing lists automatically
    - [ ] Add to <cncf-knative-maintainers@lists.cncf.io> by asking to join
- Shared passwords
    - These are in 1Password
    - [ ] Add new member to the 1Password team
    - [ ] Ask member to test access
- Social media
    - [ ] Add as an admin to [Knative LinkedIn page](https://www.linkedin.com/company/knative/)
    - [ ] Twitter: ask member to test access using the credentials in the shared passwords
        - Requires access to the <cncf-knative-maintainers@lists.cncf.io> mailing list for 2FA
- Google workspace
    - [ ] Add a @knative.dev account - can be done by a Google workspace admin
- Slack
    - [x] Add to knative-governance (private)
    - Add to public channels
      - [x] knative-toc-sc-questions
      - [x] knative-contributors
    - [x] Add as channel admins for
        - knative
        - knative-contributors
        - knative-toc-sc-questions
- Calendar
    - [x] Add to “Knative Steering Meeting” calendar invitation
- ServiceDesk
    - [ ] Ask CNCF Knative Project JIRA access (via [CNCF Service Desk](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1) Jira ticket)
    - [ ] Add to CNCF Knative maintainers group list (via [CNCF Service Desk](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1) Jira ticket)
- [ ] Google Analytics
    - TODO: details needed
- [ ] OpenSSF BestPractices Badge: <https://www.bestpractices.dev/en/projects/5913>
    - TODO: details needed
- [ ] New Blog post welcoming recent members ([example](https://knative.dev/blog/steering/2021-12-14-steering-elections-results/))

**Comment by dprotaso** [comment]
@aliok is this all done?

**Comment by aliok** [comment]
/close

We weren't able to finish all of the tasks, but at this stage I would call it done
