### ISSUE TITLE
PROCESS CHANGE: 🚨 Code of Conduct reporting mechanism for Knative is obsolete

### ISSUE THREAD

**Issue by aliok** [knative/community#1525]
If somebody wants to report a code of conduct issue to Knative, they need to report it to code-of-conduct@knative.team.

https://github.com/knative/community/blob/main/CODE-OF-CONDUCT.md:

> Violations of the Code of Conduct should be reported to [code-of-conduct@knative.team](mailto:code-of-conduct@knative.team). This email address is monitored by the Knative Steering Committee. The identity of individuals who report violations of the Code of Conduct will remain confidential.

However, noone in that email alias is active in the project: https://github.com/knative/community/blob/main/groups/committee-code-of-conduct/groups.yaml

Alternatives:
1. Say that CoC issues should be reported directly to CNCF (as in the example project template: https://github.com/cncf/project-template/blob/main/CODE_OF_CONDUCT.md)
2. Change members of this committee with SC members. Steering Charter [states](https://github.com/knative/community/blob/main/STEERING-COMMITTEE.md#charter) that SC "Receive and handle reports about [code of conduct](https://github.com/knative/community/blob/main/CODE-OF-CONDUCT.md) violations and maintain confidentiality.".
3. Say "report to steering@knative.dev" instead of the other alias.

The problem with alternative (1) is that the Knative SC will not know if a CoC issue happened in Knative if the reporting is done to CNCF directly. So, the SC cannot be aware and be cautious against the bad behavior.

**Comment by aliok** [comment]
cc @knative/steering-committee

**Comment by evankanderson** [comment]
I'm willing to perform either (1) or (2).  I'm comfortable with CNCF adjudicating CoC violations, but I'm also willing to be responsible for our own community.

**Comment by dprotaso** [comment]
When we update the code of conduct text can you only do it in the .github repository of each org.

I plan on deleting the extra md files from each individual repo since it's not necessary to have them with GitHub

**Comment by nainaz** [comment]
Can we do it simultaneously somehow? reported to steering AND CNCF/
