### ISSUE TITLE
New Repo: `autoscaler-keda`

### ISSUE THREAD

**Issue by skonto** [knative/community#1527]
Use this issue type to request a new repo in `knative-extensions` (or
`knative`, which may require additional discussion).

## Repo information

Org: `knative-extensions`

Repo: `autoscaler-keda`

Go module (Optional): `knative.dev/serving-keda`

Purpose (Description): This project targets to be a drop in replacement for the Knative Serving autoscaler-hpa component,
using keda for hpa management. For more details and a demo check https://github.com/skonto/serving-keda/blob/main/README.md.

Sponsoring WG: Serving and Operations.

Related issue: https://github.com/knative/serving/issues/14877

## Actions to fulfill

This area is used to track the [repo creation process](https://github.com/knative/community/blob/main/mechanics/CREATING-AN-EXTENSIONS-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/43) for review. You are responsible for moving your entry on the board to "Needs Discussion" or "In Progress" as you move forward in this checklist.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [x] Send a PR adding entries for this repo in [`/peribolos/knative-extensions.yaml`](https://github.com/knative/community/blob/main/peribolos/knative-extensions.yaml). Please mind the alphabetical order when adding to a list.
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  - [x] Grant the sponsoring WG the `write` privilege.

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [x] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/docs/pull/4160)).

- [x] Have a lead from the sponsoring WG bootstrap the Git repository by using an 
  appropriate "template" repository ([basic](https://github.com/knative-extensions/wg-repository),
  [sample-controller](https://github.com/knative-extensions/sample-controller),
  [sample-source](https://github.com/knative-extensions/sample-source)).

  Follow the instructions from [Creating a repository from a template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template)

- [x] Send a PR adding the repo to [knobots](https://github.com/knative-extensions/knobots). Then run the community files update action to propagate new OWNER_ALIASES.

- [x] Add your GitHub Team to the `OWNERS` file for your repo.

- [x] [Set up](https://github.com/knative/test-infra/blob/main/guides/prow_knative_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge) prow for a new repo

- [x] Bootstrap your CI jobs using [hack](https://github.com/knative/hack) project (look at other extensions repos for reference)

- [x] Create a sample PR to verify Prow (e.g., edit the boilerplate README)

- [x] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

- [ ] (optional) Send a PR adding the repo to [CLOMonitor](https://clomonitor.io/projects/cncf/knative) ([more information](/REPOSITORY-GUIDELINES.md#clomonitor-and-clotributor)).

**Comment by skonto** [comment]
cc @dprotaso @ReToCode

**Comment by ReToCode** [comment]
+1 on Rolands proposal. This also points out that this is our "KEDA-integration".

**Comment by skonto** [comment]
Changed to autoscaler-keda. Initially I had it autoscaler-keda-hpa but it is a bit verbose.

**Comment by dsimansk** [comment]
+1 to the `autoscaler-keda` name. 

It make senses in a greater picture with prefix associations to certain WG as well.

**Comment by skonto** [comment]
cc @davidhadas @cardil @upodroid @krsna-m

**Comment by upodroid** [comment]
+1 from me

**Comment by yuzisun** [comment]
+1 !!!!!!!!  I have linked to the KServe issue https://github.com/kserve/kserve/issues/3561

**Comment by tenzen-y** [comment]
Hi, knative folks 👋 
Are there any updates to introduce KEDA extensions?
I'd be looking forward to adding this extension since I'd like to use Kserve's https://github.com/kserve/kserve/issues/3561 feature.

**Comment by terrytangyuan** [comment]
+1 This would be great to have

**Comment by skonto** [comment]
> Are there any updates to introduce KEDA extensions?

I will start working on this next week. RH Serving folks are off this week.

**Comment by psschwei** [comment]
+1
