### ISSUE TITLE
Start to move repos from knative org to knative-bikeshed

### ISSUE THREAD

**Issue by mattmoor** [knative/community#153]
Things discussed as in-scope:
 - sample-*
 - net-*

/assign mattmoor

**Comment by mattmoor** [comment]
The process that @chaodaiG and I followed was roughly what I pasted in slack, thought Peribolos was struggling when we found it.

---
Alright, so sample controller seems to be moved, and barring peribolos working, we think we have some instructions:
1. PR against test-infra to replace jobs: https://github.com/knative/test-infra/pull/2226
2. PR against website to change vanity URLs: https://github.com/knative/website/pull/185
3. PR against community to move peribolos configuration: https://github.com/knative/community/pull/160
4. An admin “transfers the repo” from knative to knative-sandbox.

---

The next step is to watch sample-controller for a day or so, and if peribolos is back to normal then test the above with `sample-source` (@tcnghia watching) and if it goes smoothly canary the first `net-*` repo (probably `net-http01`?) with @tcnghia driving and me watching.

We'll watch those for the end of the week (in particular nightly releases!) and if things look good we will migrate the rest 🤩

**Comment by mattmoor** [comment]
I have staged PRs for 1-3 for sample-source (linked).

**Comment by tcnghia** [comment]
PRs staged for net-http01 move: 
https://github.com/knative/test-infra/pull/2283
https://github.com/knative/website/pull/190
https://github.com/knative/community/pull/180

**Comment by tcnghia** [comment]
Moved to net-http01 to https://github.com/knative-sandbox/net-http01

**Comment by tcnghia** [comment]
Moved to net-{contour,certmanager} to https://github.com/knative-sandbox

**Comment by tcnghia** [comment]
So .. all `sample-*` and `net-*` repositories are moved.

I saw a few remaining candidates:
- eventing-contrib (cc @vaikas @n3wscott )
- client-contrib (cc @rhuss)
- homebrew-client (cc @rhuss)

**Comment by vaikas** [comment]
Yeah, eventing-contrib, we already moved the rabbit source and I think there's some kafka work ongoing as well.

**Comment by rhuss** [comment]
@tcnghia how can we start the process for moving over the plugins from `client-contrib` to per plugin repositories as suggested in #174 . 

* Who should be contacted with a new repo name along with OWNERS for the new repo ?
* How can we start the integration into CI ?

**Comment by mattmoor** [comment]
@rhuss I'll propose the following strawman to avoid overloading this issue too much:
1. Create an issue in client-contrib for each repo move.
2. Add those issues to the TOC board (org-level), and we can spread the love as each is ready to move.

**Comment by mattmoor** [comment]
I'd propose that for the remaining issues, which also entail breaking apart `-contrib` repos we use other issues, since it's more than simple moves.  Let's follow what's above ☝️
