### ISSUE TITLE
UX WG designs contingency plan

### ISSUE THREAD

**Issue by aliok** [knative/community#1545]
UX WG is creating many files in Figma, Canva and similar online tools and we enjoy seeing some beautiful designs.

However, these designs are in their personal accounts as we lack licenses. In the future, if they leave (I hope not), Knative community would have the risk of losing access to those designs. This happened to us in other tools such as Google Suite.

@caniszczyk has [mentioned](https://cloud-native.slack.com/archives/C014YQ8CDCG/p1708612479421929) that CNCF can provide a license.

For that reason, we've created a UX WG email alias (https://github.com/knative/community/pull/1524) and our designers suggested to use that email address to sign up for the paid license.

I will reach out to CNCF Service Desk regarding this (I am working on getting access to the service desk https://servicedesk.cncf.io/)

**Comment by aliok** [comment]
cc @knative/ux-wg-leads

**Comment by aliok** [comment]
Created CNCFSD-2271 on CNCF Service Desk.

**Comment by aliok** [comment]
/close

We're done here.

Knative UX team has a shared accounts for:
- Canva
- Figma

Subscription is paid by the CNCF for this year. We need to reach out next year to CNCF (my contact was @taylorwaggoner).

Passwords are in 1password account.

**Comment by Cali0707** [comment]
Thanks for all of your help with this @aliok!!
