### ISSUE TITLE
Need clarification on logos of 3 specific 'adopters'

### ISSUE THREAD

**Issue by prajjwalyd** [knative/community#1561]
I'm currently updating the 'Trusted by' section on the knative.dev homepage with the latest design provided by the UX group.
(Last PR - https://github.com/knative/docs/pull/5878). 
As part of this update, I need to include logos of various Knative 'adopters' listed in the (https://github.com/knative/community/blob/main/ADOPTERS.MD) file.

However, I'm facing some confusion regarding the logos of three specific adopters:

1. **EASE lab @ University of Edinburgh:**
   - I'm uncertain which logo to use for this. 

2. **SVA System Vertrieb Alexander GmbH:**
   - I couldn't access their website ([sva.de/en](https://sva.de/en))

3. **vorteil pty ltd:**
   - I couldn't access their website as well ([vorteil.io](http://vorteil.io/)) 

Any assistance or guidance would be greatly appreciated. Thank you!

**Comment by aliok** [comment]
Thanks for the investigation @prajjwalyd 

1. I would go with https://ease-lab.github.io/ease_website/images/logopic/inf.gif, but let's ping @ustiugov . Are you still using Knative? What's a good logo that we can show on our website? Context: https://github.com/knative/community/issues/696#issuecomment-933730218

2. Here's the SVA logo: ![sva-logo-2024_0](https://github.com/knative/community/assets/376732/bb41a7cf-8433-469c-bdfc-7a41e322c70d) cc @nrrso 


4. https://www.linkedin.com/company/vorteil/about/ is there, but website isn't, you're right. I see this adopter was added after this comment: https://github.com/knative/community/issues/696#issuecomment-945142636. @jensg-st Is Vorteil.io operating and still using Knative?

**Comment by jensg-st** [comment]
I have updated the comment.

**Comment by ustiugov** [comment]
hi @aliok and @prajjwalyd , we have established an open-source organization, called vHive, with maintainers at NTU Singapore, University of Edinburgh, and ETH Zurich; and users in 30+ universities and global companies. Please see by the link below 
https://vhive-serverless.github.io/

The vHive logo: https://vhive-serverless.github.io/assets/images/vhive-emblem-rgb.svg

Please let me know if there is anything else you would like to know.

**Comment by aliok** [comment]
Thanks for responding quickly folks.

@prajjwalyd I think we're good now?

**Comment by prajjwalyd** [comment]
Yes, @aliok! 
I have created a PR for these changes. (https://github.com/knative/docs/pull/5966)

Do we also need to update some links in the https://github.com/knative/community/blob/main/ADOPTERS.MD?
