### ISSUE TITLE
Archive knative-extensions/net-certmanager

### ISSUE THREAD

**Issue by ReToCode** [knative/community#1563]
knative-extensions/net-certmanager was integrated into the serving code base, so we can archive the specific repository. The following usages have to be updated:

* https://github.com/search?q=org%3Aknative%20net-certmanager&type=code
* https://github.com/search?q=org%3Aknative-extensions+net-certmanager+NOT+repo%3Aknative-extensions%2Fnet-certmanager&type=code

/assign

**Comment by dprotaso** [comment]
From: https://github.com/knative/community/pull/1564#issuecomment-2107650774

> Hey - we technically shouldn't archive net-certmanager until v1.14 and v1.13 has EOL. Which is Oct ([ref](https://github.com/knative/community/blob/main/mechanics/RELEASE-SCHEDULE.md#releases-supported-by-community))
>
> This is in case we neet to cut a point release
