### ISSUE TITLE
[ADOPTERS]: alauda

### ISSUE THREAD

**Issue by chengjingtao** [knative/community#1627]
### Company or Organization

alauda

### Product or Project

Alauda Container Platform

### Status

- [X] We have a project or product that is in development
- [ ] We have a project or product that is publicly available in prerelease form
- [x] We have a project or product that is in production and publicly available
- [X] We have a project or product that is in production and used internally

### Where can we learn more?

https://www.alauda.io/

**Comment by chengjingtao** [comment]
A question. Do I still need to submit a pull request to modify ADOPTERS.MD?

**Comment by chengjingtao** [comment]
Hi, @houshengbo  can you help me to review this PR ?

**Comment by dprotaso** [comment]
Hey @chengjingtao thanks for opening the issue - I've made the PR for you.

https://github.com/knative/community/pull/1633

Could you also send a work contact email to steering@knative.team - we're in the process of gather a list of adopters as part of our CNCF graduation application.

thanks!
