### ISSUE TITLE
State of Observability

### ISSUE THREAD

**Issue by mattmoor** [knative/community#166]
Rotating the WG update schedule, Observability would have been next but was "struck through", and the intent of this was not completely clear to me.  It was not my understanding that we had closed on the topic of "what to do with Observability" (it is still in our community docs).

I think that we either need to get Observability back into the "WG update" rotation or archive the WG and clean up the references in community and elsewhere.

/assign @mdemirhan @evankanderson @mattmoor

**Comment by mattmoor** [comment]
I'm going to put this on this week's agenda since this came up in slack: https://knative.slack.com/archives/C964EFQAW/p1594674091070300?thread_ts=1594388710.067600&cid=C964EFQAW

**Comment by evankanderson** [comment]
We care about making it possible to observe the working of Knative components and make it easy to integrate with o11y backends. Individual WGs will still be responsible for instrumenting their components for metrics, tracing, etc as needed, but we don't have anyone currently with bandwidth to drive larger improvements to observability for workloads running on Knative.

I propose that we [dissolve this WG](https://github.com/knative/community/blob/master/mechanics/WORKING-GROUP-PROCESSES.md#dissolving-a-working-group) in 3 weeks (6 Aug 2020) unless multiple contributors step up.

Note that retiring this WG does not prevent it from being re-charted in the future.

**Comment by mattmoor** [comment]
Talked about this today at TOC.  We'll move ahead with retiring the Working Group.

We can always form a new working group given sufficient activation energy. 😉
