### ISSUE TITLE
Adjust the language around K8s minimum version

### ISSUE THREAD

**Issue by mattmoor** [knative/community#167]
From 6/25 TOC call.

This came up because @dprotaso was adjusting our table to reflect reality.  I also raised that we should probably have a more holistic conversation around this principle considering the hard practical realities that we and our users face.

Let's scope this issue to the set of changes we want to see in the near-term, and if it doesn't cover things, let's split off a new issue to cover incorporating community feedback.

/assign @dprotaso @mattmoor @pmorie

**Comment by dprotaso** [comment]
What prompted this issue:
https://github.com/knative/community/pull/163
