### ISSUE TITLE
Where to add Knative client plugins ?

### ISSUE THREAD

**Issue by rhuss** [knative/community#174]
The client WG wants to split up https://github.com/knative/client-contrib that holds knative client plugins into multiple repositories, one for each plugin.

Naturally, these should go into https://github.com/knative-sandbox but they are also more than just experiments. We suppose these plugins to be a consolidated list of eventing plugins (much like the `net-` repos for ingress implementations). But see also the discussion in #169 .

For the naming, we would suggest a common prefix like `kn-plugin-`, leading to repository names like:

* `kn-plugin-admin`
* `kn-plugin-source-kafka`
* `kn-plugin-source-github`
* `kn-plugin-service-log`
* `kn-plugin-migration`

We expect quite a number of plugins.

Wdyt about this suggestion? If ok, we would start the process as outlined in https://github.com/knative/community/pull/125

**Comment by rhuss** [comment]
// cc: @daisy-ycguo @maximilien

**Comment by csantanapr** [comment]
These plugins git repos should go into a `knative-extentions` github org 🍿

**Comment by zhanggbj** [comment]
@rhuss 
Not sure if the repos are already created, just revisit the plugin names, it looks a little bit long to me if start with `kn-plugin-`, is it still possible to keep using `kn-`, I think that already make it clear that it is part of `kn` client.
Btw, I assume later we'll have a centralized place to list all the kn plugins there, just like all the net-xx solutions for knative serving. There users can know they're all kn plugins. What do you think?

cc @maximilien @daisy-ycguo ^^^^

**Comment by rhuss** [comment]
I'm not sure if a longer name is really an issue as you don't have it type all day. The reasoning behind using a `kn-plugin` prefix for all plugin repositories is to distinguish it from more other `kn` extension like a potential `kn-shared` (for shared code) or `kn-builder` (for supporting a custom kn build process). However if the community thinks that its better to reflect the final c ommand name (so a `kn-admin` repo name is a better fit for a "kn-admin" plugin), then this is ok for ne, too.

This only thing which think would be mandatory is a `kn-` prefix in this shared oragnization.

**Comment by zhanggbj** [comment]
Thanks @rhuss for the explanation. Personally I prefer short name `kn-admin`, but if as you mentioned, the community needs to differ from repo like `kn-shared`, then I'm also fine with the long name:-)

**Comment by navidshaikh** [comment]
If there are plans for repos like `kn-shared`, the plugins repo names should be explicit with prefix `kn-plugin-`.

**Comment by zhanggbj** [comment]
@rhuss @maximilien @daisy-ycguo @navidshaikh Hi,  do we have a final decision,  like `kn-plugin-admin`? I think the community are waiting for our final name prefix to create a repo :-)

**Comment by rhuss** [comment]
Just back from PTO, let's touch down on this.

Let's vote on three possible schemes:

* `kn-plugin-admin` : Prefix `kn-plugin` for all plugins with the benefits that all repos are close to each other alphabetically and we can separate plugin and other client related sandbox repos based on the repo name. Drawback is that the repo does not reflect it's usage when used with `kn` (i.e. there is no command `kn plugin admin` but `kn admin`

* `kn-admin-plugin`: Prefix `kn`, Suffix `plugin` for all plugins with the benefit that the repo name somewhat reflects the usage `kn admin` (but there is no `kn admin plugin` command either so the argument does not fully hold) and that repos holding a plugin are clearly recognizable by  the repo name. Drawback is that we have prefix *and* suffix convention, and that suffix are generally hard to scan on a list of names (people typically read from left-to-right). Also such name neither express a hierarchiy ('kn' -> 'plugin') clearlly nor helps in grouping plugin names alphabetically

* `kn-admin` : Prefix `kn` only with the benefit that the repo name directly reflects the plugin name, but you can't distinguish between plugin and no plugin code by looking at the name only (you would have to go to the repo's readme to find this out). E.g. you can't see if `kn-admin` or `kn-shared` contain plugins or not. Also there is the slight chance that there is a naming conflict (e.g. how would you add a plugin called `kn shared` if there would be already a non-plugin repo `kn-shared`present in the sandbox ?)

All three options are offered below, please vote 👍 on the options that you prefer (multiple choices are possible). The ballot is open until next WG call (next Tuesday)

**Comment by rhuss** [comment]
**`kn-plugin-admin`**

**Comment by rhuss** [comment]
**`kn-admin-plugin`**

**Comment by rhuss** [comment]
**`kn-admin`**

**Comment by rhuss** [comment]
cc: @navidshaikh @maximilien @daisy-ycguo @zhanggbj @zhangtbj @dsimansk and everyone who is interested how to name repos in the sandbox orga.

**Comment by rhuss** [comment]
Extended until friday since I forgot to ping folks to vote.

**Comment by rhuss** [comment]
vote is over, option 1 is the winner (kn-plugin-admin)

**Comment by rhuss** [comment]
We are god with this, let's close it.
