### ISSUE TITLE
Investigate why adding new members in knative and knative-sandbox org will fail peribolos

### ISSUE THREAD

**Issue by chizhg** [knative/community#186]
For unknown reason, the peribolos Prow job will fail when `urasoko` is in the `knative-sandbox.yaml` file, so we have to remove them, see https://github.com/knative/community/pull/185.

We should find out the cause for this issue and add them back after we fix it.

**Comment by chizhg** [comment]
Adding `kimsterv` also failed the peribolos CI job.

**Comment by chizhg** [comment]
There is another issue for adding `zhongduo`, the logs are at https://prow.knative.dev/view/gs/knative-prow/logs/post-knative-sandbox-peribolos/1486015970647478272

Error log is below:

```
{"component":"unset","error":"status code 422 not one of [200], body: {\"message\":\"The request could not be processed.\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#set-organization-membership-for-a-user\"}","file":"prow/cmd/peribolos/main.go:492","func":"main.configureOrgMembers.func1","level":"warning","msg":"UpdateOrgMembership(knative-sandbox, zhongduo, false) failed","severity":"warning","time":"2022-01-25T16:39:57Z"}

{"component":"unset","file":"prow/cmd/peribolos/main.go:209","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure knative-sandbox members: status code 422 not one of [200], body: {\"message\":\"The request could not be processed.\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#set-organization-membership-for-a-user\"}","severity":"fatal","time":"2022-01-25T16:39:57Z"}
```

While we are not entirely sure if they are caused by the same reason, adding them to one single issue for better tracking purpose.

**Comment by aliok** [comment]
Is this still relevant?

**Comment by aliok** [comment]
/close

Thanks Roland. Closing this then.
