### ISSUE TITLE
Serving and Community samples are not in sync

### ISSUE THREAD

**Issue by antoineco** [knative/community#188]
https://knative.dev/community/samples/ and https://knative.dev/docs/serving/samples/ are not in sync.
This is confusing for newcomers.

In today's community meetup, @evankanderson mentioned
> The community samples are community-maintained rather than project-maintained

but @n3wscott also mentioned
> We might need to drop the community/samples, we ported all samples to the docs site

**Comment by abrennan89** [comment]
Community samples now just redirects here https://knative.dev/docs/contributing/

I think this issue is outdated now and can be closed since all the samples I'm aware of live here https://knative.dev/docs/samples/
