### ISSUE TITLE
Investigate the usage of divisive language throughout Knative.

### ISSUE THREAD

**Issue by markusthoemmes** [knative/community#193]
In the last ToC meeting we briefly touched on the topic of divisive language in the Knative project. The consensus was that we should definitely commit to avoid divisive terms wherever possible.

**Comment by evankanderson** [comment]
Some additional background discussion from the linux kernel: https://lkml.org/lkml/2020/7/4/229

Kubernetes document: https://docs.google.com/document/d/1bnPvb6oE07Wg9rb7kBXcpHe6j85bbyltdc0h0_gil88/edit

**Comment by evankanderson** [comment]
The kubernetes document has a lot of associated background reading for those interested.

**Comment by markusthoemmes** [comment]
Here's a preliminary list of words we'd like to replace in the process as a first step: https://docs.google.com/spreadsheets/d/1uSCWEody7WFnBQW4EnQfXFehmt-4DFh-QnoOb9-0d1A/edit#gid=0

In accordance with the Linux kernel, we're going to start with master/slave and whitelist/blacklist and potentially add more as time goes on.

**Comment by markusthoemmes** [comment]
A quick candidate `grep` statement to check a repo:

```
grep -rni --exclude-dir={vendor,third_party,.github,hack} --exclude={go.sum,go.mod,'*.md'} 'whitelist\|blacklist\|slave\|master' . | grep -v '/master/'
```

**Comment by markusthoemmes** [comment]
PRs to all `knative` repositories are out, modulo `test-infra` which might be a little more delicate.

Remaining occurrences are:
- whitelist: spf13/pflag and cobra (in client) https://github.com/spf13/pflag/pull/261
- whitelist/blacklist: strimzi CRD (in eventing-contrib, client-contrib) https://github.com/strimzi/strimzi-kafka-operator/issues/3289
- master: node roles (in eventing) https://github.com/kubernetes/kubeadm/issues/2200
- master: Google API client (in pkg) https://github.com/googleapis/google-api-go-client/
- slave: runtime contract (in serving) via the OCI spec, ultimately from the kernel

**Comment by julz** [comment]
Downloaded all sandbox repos with the following script: 

~~~~
curl -s 'https://api.github.com/orgs/knative-sandbox/repos?per_page=200' | jq .[].html_url | xargs -L 1 git clone
~~~~

Ran grep for divisive language below (using fish):

~~~~
for repo in *; pushd $repo; grep -rni --exclude-dir={vendor,third_party,.github,.git} --exclude={update-deps.sh,go.sum,go.mod} 'whitelist\|blacklist\|white-list\|black-list\|slave\|master' . | grep -v '/master'| grep -v "?= master"; if test $status -eq 1; echo "- [x] $repo"; else; echo "- [ ] $repo"; end; popd; end
~~~~

Remaining references are to 'master' branch in some update-deps.sh and DEVELOPMENT.md scripts, which will be cleared up when we change main branch, and some 'whitelist' references (see below) from an imported package, for which an issue is already open.

- [x] async-component
- [x] build-spike
- [x] discovery
- [x] downstream-test-go
- [x] eventing-autoscaler-keda
- [x] eventing-awssqs
- [ ] eventing-camel: 
   - Issue opened https://github.com/strimzi/strimzi-kafka-operator/issues/3289
- [x] eventing-ceph
- [x] eventing-couchdb
- [x] eventing-github
- [x] eventing-gitlab
- [ ] eventing-kafka: 
   - PR opened https://github.com/knative-sandbox/eventing-kafka/pull/54
- [x] eventing-kafka-broker
- [x] eventing-natss
- [x] eventing-prometheus
- [x] eventing-rabbitmq
- [x] integration
- [x] kn-plugin-admin
- [x] net-certmanager
- [x] net-contour
- [x] net-http01
- [x] net-istio
- [x] net-kourier
- [x] reconciler-test
- [x] sample-controller
- [x] sample-source
- [x] wg-repository

**Comment by markusthoemmes** [comment]
Awesome, thanks @julz!

**Comment by markusthoemmes** [comment]
As per the last ToC meeting, i'll close this one and open tracking issues for the respective dependencies in the respective repos and open a new issue here to track branch renaming.
