### ISSUE TITLE
Consider adding a banner stating the project's against racism of any form.

### ISSUE THREAD

**Issue by markusthoemmes** [knative/community#194]
Similar to #193 several projects have added a banner to their website to call out there solidarity. In the ToC meeting there was an expressed desire to add a similar banner to our website too.

**Comment by evankanderson** [comment]
Ref golang discussion (I found Russ Cox's commentary helpful): https://groups.google.com/g/golang-nuts/c/YzN4LkMHs7k/m/XFtRziMfBgAJ

**Comment by mattmoor** [comment]
This is done, so I am going to close.

Thanks to @markusthoemmes and @grantr for driving this!
