### ISSUE TITLE
Document process to retire a user-facing feature

### ISSUE THREAD

**Issue by evankanderson** [knative/community#199]
Autoscaling just did this successfully for custom-metrics.

Maybe Markus or Victor could write up the process that they used (3-4 paragraphs) and put it in `mechanics/`

**Comment by abrennan89** [comment]
@evankanderson @markusthoemmes should there be something about removing any docs for a retired feature in the process, e.g. adding a PR or raising an issue to have a feature removed?
This might be simple if it's a feature that's only mentioned in one section of docs, but some features are mentioned throughout, e.g. the current updates to Broker docs.

**Comment by evankanderson** [comment]
(Put your comment on #200, which is the PR to start documenting the process)
