### ISSUE TITLE
New Repo: knative-sandbox/operand

### ISSUE THREAD

**Issue by Cynocracy** [knative/community#202]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

Org: knative-sandbox

Repo: operand

Purpose (Description): Prototyping proposed separation of concerns between operand and operator: https://github.com/knative/operator/issues/221

Sponsoring WG: Operations

## Actions to fulfil

This area is used for the TOC to track the [repo creation
process](/mechanics/CREATING-A-SANDBOX-REPO.md)

- [ ] Create a new repo in Github UI, with "Apache License 2.0"
- [ ] Create an OWNERS and README.md file
- [ ] Add entries in `/peribolos/knative-sandbox.yaml`
- [ ] (golang) [Add aliases](https://github.com/knative/website) for
  `knative.dev`
- [ ] Set up [test-infra](https://github.com/knative/test-infra) following the
  docs linked at the beginning.
- [ ] Create a PR with a `CODE-OF-CONDUCT.md` to verify Prow.
- [ ] Once Prow is enabled and PR checks are passing, add branch protection rules.

**Comment by Cynocracy** [comment]
@houshengbo can you agree to take on this repo if I leave the community? I think that's a pre-requisite.

**Comment by evankanderson** [comment]
Ref: https://github.com/knative/community/blob/master/mechanics/CREATING-A-SANDBOX-REPO.md#criteria

**Comment by Cynocracy** [comment]
It was suggested to me to prototype this in a personal repo to start, and I think that's very reasonable. I'll close and open a new issue once I have something to share with the WG.
