### ISSUE TITLE
Changing the release date 2020-12-20

### ISSUE THREAD

**Issue by tcnghia** [knative/community#216]
This release date is bad since it is right around Christmas / New Year time:
* We also have other repositories whose release are following that week, and
* If issues happen, few will be around to help clean things up

I brought this up in the TOC meeting this week and the generally thinking is that we would like to move the release date forward, probably to 2021-01-04 or later.

Creating this issue for more discussions / awareness.

cc @mattmoor @evankanderson @grantr @markusthoemmes @tcnghia

**Comment by grantr** [comment]
Seems like a good idea to me. How would we handle following releases? It would probably be least disruptive to keep the release schedule the same. In other words, we would not shift the following releases 2 weeks later, instead we would just release as normal, 6 weeks after 2020-12-20.

**Comment by evankanderson** [comment]
I'll send a PR, and we can discuss there?
