### ISSUE TITLE
Create .github repo in each org

### ISSUE THREAD

**Issue by mattmoor** [knative/community#218]
I believe we can use this to share stuff org-wide, and selectively override things in individual repositories.

See: https://github.com/chef/.github

I haven't looked at whether this works with Github Actions, but I think this is worth exploring regardless.

**Comment by mattmoor** [comment]
cc @chaodaiG @chizhg

**Comment by mattmoor** [comment]
This only calls out the community files: https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/

**Comment by chaodaiG** [comment]
It's required by github actions as well: https://docs.github.com/en/actions/configuring-and-managing-workflows/sharing-workflow-templates-within-your-organization

**Comment by mattmoor** [comment]
It looks like the `.github` repo's `workflow-templates` feature just creates a sort of marketplace of workflows that you can enable through the Github actions UI.  It still seems to fork the action at creation time into the repo that's consuming it 😞

**Comment by mattmoor** [comment]
Scott found this, which could be useful: https://github.com/marketplace/actions/github-workflow-sync

**Comment by mattmoor** [comment]
This is what shows up under "New workflow" with what'd currently in `knative-sandbox/.github`: 
![image](https://user-images.githubusercontent.com/2442466/90302724-1262a180-de5d-11ea-9641-00eb8cb14504.png)

**Comment by mattmoor** [comment]
Alright, @n3wscott and I seeded a bunch of workflows into `knative-sandbox/.github` 
![image](https://user-images.githubusercontent.com/2442466/90305046-fff36280-de72-11ea-8aee-259f5c069e0d.png)

**Comment by mattmoor** [comment]
Alright, we now have these virtually everywhere.
