### ISSUE TITLE
New Repo: async-component

### ISSUE THREAD

**Issue by beemarie** [knative/community#221]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

Org: knative-sandbox

Repo: async-component

Purpose (Description): This add on component will provide asynchronous functionality to Knative services. More context can be found in the [feature proposal](https://docs.google.com/document/d/1a8f6mVlqQsr0VttWTRLcFT1PtnOHF9dKZXZEos9NSBA/edit?usp=sharing). 

Sponsoring WG: Serving

## Actions to fulfil

This area is used for the TOC to track the [repo creation
process](/mechanics/CREATING-A-SANDBOX-REPO.md)

- [x] Create a new repo in Github UI, with "Apache License 2.0"
- [x] Create an OWNERS and README.md file
- [ ] Add entries in `/peribolos/knative-sandbox.yaml`
- [ ] (golang) [Add aliases](https://github.com/knative/website) for
  `knative.dev`
- [ ] Set up [test-infra](https://github.com/knative/test-infra) following the
  docs linked at the beginning.
- [x] Create a PR with a `CODE-OF-CONDUCT.md` to verify Prow.
- [x] Once Prow is enabled and PR checks are passing, add branch protection rules.

**Comment by beemarie** [comment]
@mattmoor @evankanderson @dprotaso
Our directional discussions have concluded, and we landed on an external component to provide the functionality for asynchronous services. While there are still some open questions, I think our feature proposal defines our direction and highlights where we need to do some more exploration.

Please let me know what my next steps should be!

**Comment by mattmoor** [comment]
/unassign
/assign @beemarie 

@beemarie The repo exists, if you want to sent me a PR for the next couple steps, I'm happy to TAL.

Once Prow is running, feel free to assign back to me to set up branch protection and close this out.

**Comment by beemarie** [comment]
/unassign
/assign @mattmoor 

It looks like Prow is running, please feel free to confirm: https://github.com/knative-sandbox/async-component/pull/1

**Comment by mattmoor** [comment]
/close 

The repo now exists, and branch protections are enabled.

I think you should be unblocked (maybe one more PR to add yourself to OWNERS?).
