### ISSUE TITLE
New Repo: continuous-delivery

### ISSUE THREAD

**Issue by trshafer** [knative/community#222]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

Org: knative-sandbox

Repo: continuous-delivery
Would be happy with any of the variants: continuous-deployment, progressive-rollout, gradual-rollout, etc.

Purpose (Description):
The purpose of knative continuous delivery is to natively support progressive rollout of ksvc. It will allow users to assign a policy to a ksvc and as they push new revisions the revisions will be rolled out according to the policy. There is a working example at https://github.com/googleinterns/knative-continuous-delivery. This project currently supports time based rollouts.

Thanks!

Sponsoring WG:
Talking to networking WG on August 20th about sponsoring.

## Actions to fulfill

This area is used for the TOC to track the [repo creation
process](/mechanics/CREATING-A-SANDBOX-REPO.md)

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review.

- [ ] Send a PR adding entries for this repo in `/peribolos/knative-sandbox.yaml`
  - [ ] Add the repository and a description.
  - [ ] Grant `Knative Admin` the `admin` privilege.
  - [ ] Grant the sponsoring WG the `write` privilege.

_Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [ ] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [ ] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo master
  ```

- [ ] Set up [test-infra](https://github.com/knative/test-infra) following the
  docs linked at the beginning.

- [ ] Create a sample PR to verify Prow (e.g. edit the boilerplate README)

_Once Prow has been verified._

- [ ] Have a member of the TOC enable branch protections so that `tide` is a required presubmit check.

**Comment by evankanderson** [comment]
Another possibility is adding a "contributed tools" section to docs and pointing to non-Knative repos.

**Comment by evankanderson** [comment]
I'd think that this might be more closely aligned with the serving API, but I think if we get answers on "how to keep this from rotting" it would be fine either place.

**Comment by mattmoor** [comment]
I think this is rotten, so I'm inclined to close.  Moving to needs discussion.
