### ISSUE TITLE
New Repo: eventing-couchdb

### ISSUE THREAD

**Issue by lionelvillard** [knative/community#224]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

Org: knative-sandbox

Repo: eventing-couchdb

Purpose (Description): CouchDB integration with Knative Eventing

Sponsoring WG: Eventing and Source WG

## Actions to fulfill

This area is used for the TOC to track the [repo creation
process](/mechanics/CREATING-A-SANDBOX-REPO.md)

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review.

- [x] Send a PR adding entries for this repo in `/peribolos/knative-sandbox.yaml`
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  - [x] Grant the sponsoring WG the `write` privilege.

_Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [x] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [x] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo master
  ```

- [x] Set up [test-infra](https://github.com/knative/test-infra) following the
  docs linked at the beginning.

- [x] Create a sample PR to verify Prow (e.g. edit the boilerplate README)

_Once Prow has been verified._

- [x] Have a member of the TOC enable branch protections so that `tide` is a required presubmit check.

**Comment by lionelvillard** [comment]
@grantr  can you enable branch protection?

**Comment by grantr** [comment]
Enabled. Can you verify Prow by having it merge a PR?

**Comment by mattmoor** [comment]
Prow merged: https://github.com/knative-sandbox/eventing-couchdb/pull/8

closing this as done
