### ISSUE TITLE
Make the repo creation process more self-service.

### ISSUE THREAD

**Issue by mattmoor** [knative/community#241]
The current repo creation process include the manual creation of a repo, which is something that only admins can do.   However, peribolos is an admin and can create repos!

To make the process more self-service, I would suggest the following:
1. Open a PR creating the repo in peribolos with the appropriate permissions, description, etc.  One of these should be the owning WG's leads getting "write" permission.
2. TOC approves the above, which merges and creates the repo.
3. WG lead then follows the remaining instructions.

The final bit around branch protections is something that admins will still need to set up manually, which will close out the issue.

/assign

**Comment by grantr** [comment]
:+1:

Concretely, we change the creation process by updating https://github.com/knative/community/blob/master/.github/ISSUE_TEMPLATE/new-repo.md. Maybe REPOSITORY-GUIDELINES.md too, though it seems general enough to be independent of the actual creation steps.

**Comment by chizhg** [comment]
You can even configure branch protection with Prow! Example for k8s Prow here - https://github.com/kubernetes/test-infra/blob/6d0d0726ecf131ebe3e9ccd80e208d1c3f8f58be/config/prow/config.yaml#L118. Though I haven't personally tried it yet so I'm not sure how powerful it is.

**Comment by mattmoor** [comment]
@chizhg that's actually be great as it'd make this fully self-service (we just have to `/approve`). 🤯 

I think that in general we only need `tide`, right?

**Comment by chizhg** [comment]
Looks like it's a separate `branchprotector` tool (just like `peribolos`) - https://github.com/kubernetes/test-infra/tree/master/prow/cmd/branchprotector, so similarly we could configure it as postsubmit Prow jobs which will be triggered when the config.yaml file is changed.
