### ISSUE TITLE
REQUEST: New membership for MIBc

### ISSUE THREAD

**Issue by MIBc** [knative/community#243]
Since 2019, I have participated in community contributions and actively participated in the tracking and resolution of community problems. 
Currently, I hope to join the community and continue contributing to the project in the field of serverless/faas.
### GitHub Username
@MIBc

### Organization you are requesting membership in
knative

### Requirements

- Has made multiple contributions to the project or community. Contributions
might include, but are not limited to:

    [√] Authoring and reviewing PRs on GitHub.

    [√] Filing and commenting on issues on GitHub.

    [√] Contributing to working group or community discussions.

    [√] Subscribed to [knative-dev@googlegroups.com](https://groups.google.com/forum/#!forum/knative-dev).

- Actively contributing to 1 or more areas.

### Sponsors
@rhuss 
@mattmoor
@zouyee
### List of contributions to the knative project

* knative/client
https://github.com/knative/client/pull/860
https://github.com/knative/client/pull/805
https://github.com/knative/client/pull/790
https://github.com/knative/client/pull/788
https://github.com/knative/client/pull/755
https://github.com/knative/client/pull/738
https://github.com/knative/client/pull/634
https://github.com/knative/client/pull/630
https://github.com/knative/client/pull/599
https://github.com/knative/client/pull/596
https://github.com/knative/client/pull/592
https://github.com/knative/client/pull/575

* knative/serving
https://github.com/knative/serving/pull/8614
https://github.com/knative/serving/pull/7047
https://github.com/knative/serving/pull/6912
https://github.com/knative/serving/pull/6873
https://github.com/knative/serving/pull/6783
https://github.com/knative/serving/pull/6572
https://github.com/knative/serving/pull/6567
https://github.com/knative/serving/pull/6530
https://github.com/knative/serving/pull/6526
https://github.com/knative/serving/pull/6465
https://github.com/knative/serving/pull/6345

* knative/docs
https://github.com/knative/docs/pull/2392
https://github.com/knative/docs/pull/2243
https://github.com/knative/docs/pull/2240
https://github.com/knative/docs/pull/2230
https://github.com/knative/docs/pull/2110
https://github.com/knative/docs/pull/2098
https://github.com/knative/docs/pull/2049
https://github.com/knative/docs/pull/2031

* knative/eventing-contrib
https://github.com/knative/eventing-contrib/pull/1335
https://github.com/knative/eventing-contrib/pull/1289
https://github.com/knative/eventing-contrib/pull/1230
https://github.com/knative/eventing-contrib/pull/1225
https://github.com/knative/eventing-contrib/pull/1210

* knative/eventing
https://github.com/knative/eventing/pull/3641
https://github.com/knative/eventing/pull/2827

* knative/pkg
https://github.com/knative/pkg/pull/966

* knative-sandbox/sample-controller
https://github.com/knative-sandbox/sample-controller/pull/302
https://github.com/knative-sandbox/sample-controller/pull/301
https://github.com/knative-sandbox/sample-controller/pull/259
https://github.com/knative-sandbox/sample-controller/pull/247

**Comment by rhuss** [comment]
Definitely +1 one from my side.

**Comment by zouyee** [comment]
+1！！！！

**Comment by pierDipi** [comment]
@MIBc, you can create a PR to add your GitHub username to the member list:

- `knative`: https://github.com/knative/community/blob/master/peribolos/knative.yaml#L26
- `knative-sandbox`: https://github.com/knative/community/blob/master/peribolos/knative-sandbox.yaml#L28

**Comment by MIBc** [comment]
OK. Thanks all.

**Comment by mattmoor** [comment]
@MIBc please send me the PR, and I can stamp it.  thank you for all of your contributions!
