### ISSUE TITLE
Revisit: K8s minimum version principle

### ISSUE THREAD

**Issue by mattmoor** [knative/community#245]
See here: https://kubernetes.io/blog/2020/08/26/kubernetes-release-1.19-accentuate-the-paw-sitive/#increase-kubernetes-support-window-to-one-year

cc @dprotaso @pmorie

**Comment by mattmoor** [comment]
@dprotaso do you want to take a crack at this now that you're back? 🥺

**Comment by dprotaso** [comment]
yeah it's on my backlog

**Comment by evankanderson** [comment]
(ping)

**Comment by dprotaso** [comment]
related: https://github.com/kubernetes/sig-release/issues/1290

**Comment by dprotaso** [comment]
And https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md

**Comment by dprotaso** [comment]
woo structured data https://github.com/kubernetes/sig-release/blob/master/releases/schedule.yaml

**Comment by dprotaso** [comment]
### [Recap: K8s minimum version principle](https://github.com/knative/community/blob/master/mechanics/RELEASE-VERSIONING-PRINCIPLES.md#k8s-minimum-version-principle)

> We (the community) support the range of upstream minor Kubernetes versions that are Kubernetes community supported at the time of the cut. Only the latest patch release of the minor version is tested for support. Support for versions prior to that are best effort, or by vendors.
> 
> Adoption of newer K8s minimum versions will also be on a best-effort basis. When a Kubernetes version is released it's availability in downstream distributions is often lagging. When these delays affect our planned min K8s version we'll update the version table below and make it known in the release's notes.
> 

### Upstream EOL Changes
With v1.19 the support window is now a year. This change has been rolled back into v1.17 & v1.18 (see [PR](https://github.com/kubernetes/sig-release/commit/27f1b9f155d23475d6e99b694c061887814baf81)). 

### Current Version Pairing between K8s & Knative

Knative | Min K8s | notes
-|-|-
v0.19 | v1.17 |
v0.20 | v1.17 | EOLs 2 weeks after
v0.21 | v1.18 |
v0.22 | v1.18 | EOLs 2 weeks after
v0.24 | v1.19 | 
v0.25 | v1.19 |
v0.26 | v1.19 | EOLs 1 week after
v0.27 | v1.20 |

Here's an interactive [sheet](https://docs.google.com/spreadsheets/d/1AZLU81U_g9r0llShXF5qxnRhIlMTj0_BHgS_kMw8vZw/edit#gid=700434580) showing and an image for the lazies

![Screen Shot 2020-10-28 at 9 28 15 PM](https://user-images.githubusercontent.com/18562/97514235-9dcfd700-1964-11eb-8541-72a1f318b57b.png)

### Recommendation

I suggest we include a clause specifying that releases with a nearby EOL will be skipped.

> We (the community) support the range of upstream minor Kubernetes versions that are Kubernetes community supported at the time of the cut _**excluding versions with an upcoming end-of-life date**_. Only the latest patch release of the minor version is tested for support. Support for versions prior to that are best effort, or by vendors.
> ...

What we should decide is what the cut-off should be - ie. EOL date is <= 2 months skip

**Comment by evankanderson** [comment]
@markusthoemmes to find the right person to look at this, maybe @pmorie ?

**Comment by evankanderson** [comment]
Julz thinks we should be as aggressive as possible given the platforms available.

**Comment by evankanderson** [comment]
@grantr will figure out what's needed on the Google side?

**Comment by sebgoa** [comment]
2 cents. GKE static version is still on v1.17.x . so it feels like knative is pushing me to be on "cutting edge" version on a managed service.

I would feel less pressure if latest knative would be dependent on v1.16

as people get in production with knative I feel that the version of their k8s will start to fall back especially with the cadence of upstream k8s most likely slowing down.

bottom line, I am a bit cautious and would not want to be "too much" cutting edge.

**Comment by mdemirhan** [comment]
On Google's side, we very very strongly prefer to be conservative with min k8s versions. Our k8s product (GKE) supports three versions at any given point in time and the cutting edge k8s version being the least adopted by a very significant margin. Most of our customers prefer staying one or two versions behind. There is also a delay in GKE's adoption of the latest version, so the latest GKE version might not be the latest k8s version, which makes the situation even more dramatic. So from Google customers' point of view, most of them will be up to 3 versions behind the latest k8s version.

If Knative were to go with an aggressive min version requirement, we will have to keep most of our customer base with old versions of Knative, and that is a very undesirable for us. Keeping customers on older versions of Knative also introduces another complexity when it comes to upgrades: if we were to have more than 2 versions of Knative for a given min k8s version (in the table above, Knative 0.24, 0.25 and 0.26), then we can end up forcing customers to jump more than 2 knative versions when they upgrade their GKE version (example: if the customer is on k8s 1.18, their Knative version will be 0.22 - if they go to GKE 1.19, they might end up jumping to version 0.25).

We want to meet with our customers where they are, and not push them to be always at the cutting edge (most of them won't).

If there is a feature that requires the latest version of k8s, we can have a fork that depends on the latest version of k8s and development of that specific feature can happen on that fork. Eventually, when Knative min version meets that fork's min requirement, the feature can be brought back to master. This should give the option to work on cutting edge k8s versions for vendors who wants it without forcing everyone else to be aggressive & cutting edge.

**Comment by dprotaso** [comment]
> So from Google customers' point of view, most of them will be up to 3 versions behind the latest k8s version.

@mdemirhan K8s upstream has extended their support policy to a year - so there's roughly _four_ K8s releases being maintained simultaneously - based on this has GKE changed it's support policy in any way?

> If Knative were to go with an aggressive min version requirement...

I'm not advocating for that - do you have thoughts on my recommendation to pick the min support version upstream version of K8s **_but exclude it if it's going to EOL very soon_**.  I'm trying to qualify `very soon` from different vendors.

ie.  K8s 1.17 will be EOL two weeks after the 1.20 release. So I'm thinking we should pro-actively bump to K8s 1.18.

**Comment by dprotaso** [comment]
It may also be worth noting we can adjust these on a per-release basis and as things change upstream.

**Comment by duglin** [comment]
We can live with this. The only concern raised was the move away from kube 1.18 by end of April due to all of the holidays between now and then. But not enough of a concern to push back on this proposal.

**Comment by vagababov** [comment]
Having discussed this a bit internally it would be strongly preferable for Google to read this as
`**including** versions with an upcoming end-of-life date before next Knative release` — basically support the current k8s version at the time of Knative release.
I.e. in this case we'd prefer that 0.20 supported 1.17 and the minimum supported version for 0.21 is 1.18.

**Comment by pmorie** [comment]
I'm definitely glad that the window of community support for upstream k8s has increased to be more in line with how people consume k8s.

The central tradeoff in my mind when it comes to supporting versions that are close to EOL is:

Ease of consumption:

- vendors take time to deliver k8s in their products 
- users take time to move onto more recent k8s versions

Feature / capability enrichment:

- takes longer to be able to assume that new feature X is available within any supported k8s cluster

Fundamentally, it doesn't seem like supporting versions that are technically supported but near EOL when a version of knative is released drastically changes the dance we have to do about using features that aren't available everywhere yet. 

Related thought: we should probably be specific about how we might handle cases like the above, where there is a supported version of knative with an EOL k8s version. We can provide what most people would understand as 'community support', but our options may be very limited in that situation if there's a problem due to a bug in the unsupported k8s version.

**Comment by dprotaso** [comment]
[Datadog's container report](https://www.datadoghq.com/container-report/) has some stats on k8s version usage here: https://www.datadoghq.com/container-report/#8

(Updated November 2020) 
![Screen Shot 2020-11-19 at 10 44 24 AM](https://user-images.githubusercontent.com/18562/99688823-3cc38c80-2a54-11eb-866f-8a717ee71521.png)

**Comment by dprotaso** [comment]
Seems like K8s has an upgrade problem

**Comment by evankanderson** [comment]
We need to figure out how to separate hard minimum version from community supported / tested versions.

**Comment by evankanderson** [comment]
We need some sort of policy around what it means / what we do if Knative accidentally includes a feature that's outside the community support level but is still a popular K8s version. (And we should define what a "popular" k8s version is.)

**Comment by evankanderson** [comment]
@julz will write up something about how to adopt new K8s features _optionally_, rather than as a hard dependency, to allow adopting newer k8s features while still supporting older k8s installs as well.

**Comment by evankanderson** [comment]
We also need to write up what we test against, and what we will roll back breakages on but won't test. (Mostly when reported by vendors who are maintaining non-upstream supported versions based on popularity/population.)

**Comment by mdemirhan** [comment]
Awesome, looking forward to seeing the write up. Thanks @evankanderson @julz @dprotaso @pmorie

**Comment by dprotaso** [comment]
> We need to figure out how to separate hard minimum version from community supported / tested versions.

I'm hoping a [`knative/release` repo ](https://github.com/knative/community/issues/360) could document/capture this metadata and then surface it automatically to the docs/website

**Comment by dprotaso** [comment]
We've sort of branched out and these digressions now have their own follow up issues. Based on the discussions here and in the TOC meetings the majority of folks prefer _not_ to change the principle. 

@knative/technical-oversight-committee I think we can close this issue out
