### ISSUE TITLE
New Repo: reconciler-test

### ISSUE THREAD

**Issue by n3wscott** [knative/community#252]
## Repo information

Org: knative-sandbox

Repo: reconciler-test

Purpose (Description): Breaking the behavior driven testing framework for reconcilers into a separate releasable module. It is in use in Discovery and Eventing RabbitMQ, each integration required a copy/paste. 

Sponsoring WG: Sources WG

## Actions to fulfill

This area is used for the TOC to track the [repo creation
process](../tree/master/mechanics/CREATING-A-SANDBOX-REPO.md)

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review.

- [x] Send a PR adding entries for this repo in `/peribolos/knative-sandbox.yaml`
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  - [x] Grant the sponsoring WG the `write` privilege.

_Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [x] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [x] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo master
  ```

- [ ] Set up [test-infra](https://github.com/knative/test-infra) following the
  docs linked at the beginning.

- [x] Create a sample PR to verify Prow (e.g. edit the boilerplate README)

_Once Prow has been verified._

- [x] Have a member of the TOC enable branch protections so that `tide` is a required presubmit check.

**Comment by grantr** [comment]
For some reason Peribolos didn't add all the requested github teams from #254 to the repo permissions (https://github.com/knative/community/pull/254#issuecomment-686653731). I added Eventing Writers (write) manually so we could make progress.

**Comment by grantr** [comment]
https://github.com/knative-sandbox/reconciler-test/pull/1 was created before the "Set up test-infra" step, and Tide and Prow are already working in the repo. Is test-infra setup actually required?

**Comment by mattmoor** [comment]
@grantr not for tide and CLA bot which use org-level hooks.  If you want any repo-specific prow jobs, then you need to setup test-infra.

Is this done?

**Comment by mattmoor** [comment]
I enabled branch protection.

/assign @n3wscott 

Scotty, create the test-infra jobs you want and mark that PR as fixing this?

**Comment by n3wscott** [comment]
I don't want any prow jobs, this is intended to be a lib. I think we are gtg, thanks!!

/Close
