### ISSUE TITLE
Add security issue template(s)

### ISSUE THREAD

**Issue by richterdavid** [knative/community#259]
Now that we have a (draft, pending) security policy, we should have a corresponding issue template, or several if appropriate.

This is especially useful to the extent we can create confidential (just visible by knative-security@googlegroups.com or a corresponding Github team) issues. If we go that route, we should update the security policy to reflect this additional, supported, way to submit reports.

Splitting this off from https://github.com/knative/serving/issues/7925

**Comment by aliok** [comment]
Is this still relevant?

**Comment by davidhadas** [comment]
We are going to move to github vulnerability disclosures - which has a template.
