### ISSUE TITLE
Enable use of codecov for Knative repos

### ISSUE THREAD

**Issue by mattmoor** [knative/community#281]
There is a nice (and free for OSS) code coverage tool, which a number of other projects I work with use (ggcr, ko, contour): codecov.io.

You can see a sample report here: https://github.com/google/go-containerregistry/pull/770#issuecomment-693678098

The configuration itself is relatively simple: https://github.com/google/go-containerregistry/blob/master/.codecov.yml

and it is pretty easy to integrate into common CI tools:
 * Travis: https://github.com/google/go-containerregistry/blob/2ff6f48e2524c5b02a915978ff247802451efa6b/.travis.yml#L32
 * Actions: https://github.com/codecov/codecov-action

/assign
cc @n3wscott

**Comment by mattmoor** [comment]
Oh, and when I looked into the permissions needed in order to install the Github application, they looked about as I'd have expected (IIRC the only "write" permission was `commitstatus`).

**Comment by n3wscott** [comment]
Let me bootstrap on discovery and see if I run into issues.

**Comment by mattmoor** [comment]
Well, we need to install the github app first 😉

**Comment by n3wscott** [comment]
ok staged. https://github.com/knative-sandbox/discovery/pull/60

**Comment by n3wscott** [comment]
looks like my job worked, but it does not yet have the full integration, https://codecov.io/github/knative-sandbox/discovery/commit/764f22331a5e37c9f54c23a7134597757085bca2

**Comment by mattmoor** [comment]
Yeah, to write commit status it probably needs to be installed in the Github Org

**Comment by mattmoor** [comment]
Here are the permissions it wants:

![image](https://user-images.githubusercontent.com/2442466/93530386-5c262800-f8f2-11ea-96ff-ab5dd8b56392.png)

This seems about right for presubmit checks.

**Comment by mattmoor** [comment]
I am going to grant it access to just discovery as we experiment with it.

**Comment by mattmoor** [comment]
Alright, it works great on discovery, so I'm going to expand access to sandbox.

**Comment by mattmoor** [comment]
You can see this in action here: https://github.com/knative-sandbox/discovery/pull/63#issuecomment-694523340

**Comment by mattmoor** [comment]
Scotty sent: https://github.com/knative-sandbox/.github/pull/20

This is done in the same style as Markus did golangci-lint, so if the config is present it runs.  We'll pilot on a few sandbox repos first.

**Comment by mattmoor** [comment]
This is done
