### ISSUE TITLE
New Repo: kn-plugin-pkg

### ISSUE THREAD

**Issue by maximilien** [knative/community#282]
## Repo information

Org: knative-sandbox

Repo: kn-plugin-pkg

Purpose (Description):

Common code for `kn-source-*` plugins, e.g., kn-source-kafka, kn-source-github, kn-source-gitlab, etc

Sponsoring WG: client

## Actions to fulfill

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review.

- [x] Send a PR adding entries for this repo in `/peribolos/knative-sandbox.yaml`
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  - [x] Grant the sponsoring WG the `write` privilege.

_Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [x] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [x] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo master
  ```

- [x] Set up [test-infra](https://github.com/knative/test-infra) following the
  docs linked at the beginning.

- [x] Create a sample PR to verify Prow (e.g. edit the boilerplate README)

_Once Prow has been verified._

- [ ] Have a member of the TOC enable branch protections so that `tide` is a required presubmit check.

**Comment by maximilien** [comment]
FYI @rhuss @navidshaikh @daisy-ycguo

**Comment by mattmoor** [comment]
@knative/client-wg-leads I think we'd defer to you for `kn-plugin-` prefixed stuff, so when this has your blessing please make sure we know.

**Comment by evankanderson** [comment]
Does this need `go mod` support and/or test-infra set up?

**Comment by rhuss** [comment]
/hold

I think we need a more discussion in the wg how we want to model our shared dependencies. (whether fine grained or more a single shared repo)

**Comment by rhuss** [comment]
In the client group, we decided to move all the shared code (not only for plugins) to a `client-pkg` repository. See #523  for the followup repo. 

I think we can close this issue here and followup on #523 .
