### ISSUE TITLE
New Repo: kn-plugin-source-github

### ISSUE THREAD

**Issue by maximilien** [knative/community#283]
## Repo information

Org: knative-sandbox

Repo: kn-plugin-source-github

Purpose (Description):

The `kn` plugin for for GitHub events source

Sponsoring WG: client

## Actions to fulfill

This area is used for the TOC to track the [repo creation
process](/mechanics/CREATING-A-SANDBOX-REPO.md)

- [ ] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [ ] Send a PR adding entries for this repo in `/peribolos/knative-sandbox.yaml`
  - [ ] Add the repository and a description.
  - [ ] Grant `Knative Admin` the `admin` privilege.
  - [ ] Grant the sponsoring WG the `write` privilege.

_Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [ ] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [ ] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo master
  ```

- [ ] Set up [test-infra](https://github.com/knative/test-infra) following the
  docs linked at the beginning.

- [ ] Create a sample PR to verify Prow (e.g. edit the boilerplate README)

_Once Prow has been verified._

- [ ] Have a member of the TOC enable branch protections so that `tide` is a required presubmit check.

**Comment by maximilien** [comment]
FYI @rhuss @navidshaikh @daisy-ycguo

**Comment by rhuss** [comment]
+1 @maximilien are you about to adapt the Peribolos config or do you want me to do this ? (im fine with that).

**Comment by maximilien** [comment]
Not sure what that entails @rhuss :) So please go ahead. If you need me to do anything then let me know.

**Comment by rhuss** [comment]
ok, will do it tomorrow and then send in a PR. You then would need to update the description for checking the marks

**Comment by aliok** [comment]
/close

I don't think there's something we want to do here after 3 years.
