### ISSUE TITLE
Proposal to use an enhancement proposal process similar to KEPs

### ISSUE THREAD

**Issue by taragu** [knative/community#29]
How do we feel about using an enhancement proposal process similar to KEP (https://github.com/kubernetes/enhancements/tree/master/keps)? We don't have to use all components of the KEP process. Here are the elements we can adopt easily:
- Using a repo (as opposed to google docs) for design docs organized by working groups. This makes these documents more easily findable, and users can cross reference these docs more easily.
- Define approvers and reviewers for design docs under each working groups. This will help us to have more discoverable records about the decisions we make.

@mattmoor WDYT?
FYI @maximilien

**Comment by mattmoor** [comment]
It's on me to move https://docs.google.com/document/d/1QRREfL8gSVSURHMkDLjDtMh1BBsNiwfmaBiGnJUDQ2g/edit# into this repo.  Feedback welcome.

**Comment by vagababov** [comment]
While the final version is fine in the repo, I find Google docs and related
commenting, suggesting, etc features significantly better suited for
discussion.

**Comment by taragu** [comment]
Thanks @mattmoor for pointing out the official Feature Tracks doc. @vagababov I think Google docs works well for faster back-and-forth discussions and has better mobile support. Although I find it difficult to look through resolved comments because it's not easily searchable.

**Comment by rgregg** [comment]
With the new feature tracks process in place, should we close this issue out?

**Comment by taragu** [comment]
@rgregg yes! Closing this issue
