### ISSUE TITLE
Rename the primary branches of all repositories to 'main'

### ISSUE THREAD

**Issue by markusthoemmes** [knative/community#293]
Generally $subj is what Github is doing across the board and they claim to provide tooling for gracefully moving branches at the end of the year. Let's wait for said tooling and then use it.

See https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-

**Comment by markusthoemmes** [comment]
Github now supports renaming, see https://knative.slack.com/archives/CCSNR4FCH/p1610812772029700. I'll kick off discussions towards making our scripts more durable to allow both master and main and then go through our repos and rename things. YAAAY.

/assign

**Comment by markusthoemmes** [comment]
Good news:
> Redirect web requests for the old branch name to the new branch name

Works like a charm! So we can focus on making sure our scripts continue to work and don't have to worry about links just yet and can update those lazily. One less thing to keep track off.

**Comment by n3wscott** [comment]
[] All README files will need to be updated in all repos to use the new branch name for badges.

**Comment by markusthoemmes** [comment]
Sandbox repos have all been renamed.

**Comment by markusthoemmes** [comment]
Knative repos have all been renamed, this is done!
