### ISSUE TITLE
Being an approver in repos separated from eventing-contrib

### ISSUE THREAD

**Issue by aliok** [knative/community#295]
We now have many repositories split from `eventing-contrib` into `knative-sandbox`.

We need to define who are the approvers for these.

The regular criteria (reviewed 30 PRs + primary reviewer for 10 substantial PRs) approach will not work for these because the repositories are small and there will not be a lot of activity on individual reports.

So, the questions that I want to get answered are:
- Are repositories in `knative-sandbox` subject to Knative governence rules as they are in `knative` Github org?
- Any alternative ideas when the criteria to become an approver is not applicable, such as in XYZSource on `knative-sandbox` which is a very small project?

**Comment by aliok** [comment]
One idea from @devguyio was this:

> so for future folks, approvers can be decided by contributions per repo "approver in knative-sandbox/eventing-kafka" . For other folks, I don't see why not just counting eventing-contrib contributions + your desired new repo (e.g. eventing-kafka) .
e.g. 21 (eventing-contrib) + 9 (eventing-kafka) = 30 -> approver in eventing-kafka (edited)

**Comment by evankanderson** [comment]
This probably should result in clarification in the governance docs, but it seemed reasonable for the eventing WG leads to manage this process with a different bar that was more appropriate.

**Comment by evankanderson** [comment]
I'd encourage the Source WG to innovate here, either by assigning sub-OWNERS for specific sources that wouldn't be "Approvers for all Sources" (much like you could add a user to OWNERS for just one directory in `eventing-contrib`), or by pooling contribution counts across all source repos.

**Comment by evankanderson** [comment]
(Leaving in the steering backlog to allow them to update any governance docs)

**Comment by vaikas** [comment]
@bsnchan will document and summarize the discussion we had on slack.

**Comment by bsnchan** [comment]
For reference, [this](https://knative.slack.com/archives/CU9DGL4FM/p1614194892008400) is the discussion that was had in Slack.

To summarize: All repos in the `knative-sandbox` GitHub org are the reflection of WG leads. These leads are free to use their judgement to take set what bar is used to assign reviewers, approvers, owners for the knative-sandbox repos they are responsible for. Similarly, when a knative-sandbox repo is abandoned, they take the responsibility to archive the repo.
