### ISSUE TITLE
New Repo: kn-plugin-diag

### ISSUE THREAD

**Issue by cdlliuy** [knative/community#296]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

Org: knative-sandbox

Repo: kn-plugin-kn-diag

Purpose (Description): Code for kn plugin for kn-diag

Sponsoring WG: client

## Actions to fulfill

This area is used to track the [repo creation process](/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [x] Send a PR adding entries for this repo in [`/peribolos/knative-sandbox.yaml`](https://github.com/knative/community/blob/master/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  - [x] Grant the sponsoring WG the `write` privilege.

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [x] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [x] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo master
  ```

- [x] Set up [test-infra](https://github.com/knative/test-infra) following the
  docs linked at the beginning.

- [X] Create a sample PR to verify Prow (e.g. edit the boilerplate README)

**TOC Gate** : _Once Prow has been verified_

- [X] Have a member of the TOC enable branch protections so that `tide` is a required presubmit check.

**Comment by cdlliuy** [comment]
fyi  @maximilien,   @rhuss

**Comment by mattmoor** [comment]
cc @knative/client-wg-leads

**Comment by mattmoor** [comment]
If client is ok with this, let's start the process.

**Comment by tcnghia** [comment]
video demo of Kn-diag from Ying: https://youtu.be/PxD0yxb8B7c

**Comment by mattmoor** [comment]
ping @knative/client-wg-leads

**Comment by evankanderson** [comment]
@cdlliuy -- next steps are to send a PR for https://github.com/knative/website to set up go import aliases and a then a PR for https://github.com/knative/test-infra for prow setup.

(Sorry, we're hoping to automate this since it turns out that everyone wants a repo now that we have a process.)

**Comment by cdlliuy** [comment]
Sorry for the delay.  Raised PRs as suggested, 
https://github.com/knative/website/pull/238
https://github.com/knative/test-infra/pull/2562  ( I am not sure whether the format is correct in this PR, I didn't find a good example PR in this repo)

**Comment by maximilien** [comment]
The test-infra PR has some issues @cdlliuy

**Comment by cdlliuy** [comment]
@maximilien ,  I think I fixed the errors on PR.

**Comment by rhuss** [comment]
I think we are good with this and move on to import the code. @cdlliuy I added an OWNERS file to the repo, and please could you create a PR that imports your initial plugin code ? I then would setup the infrastructure scripts.

Also, I think you need also to be added to the Knative Github organization.

**Comment by evankanderson** [comment]
(This looks like it's still at the `OWNERS`-file, but no code state. Is this still planned to be contributed?)

**Comment by cdlliuy** [comment]
@rhuss   , do you mean that I can ignore the error in go-coverage https://github.com/knative-sandbox/kn-plugin-diag/pull/11#issuecomment-769626925 , and do the commit directly?  

I thought I removed all the go-coverage in test-infra, but  the check can't pass ...

**Comment by rhuss** [comment]
> (This looks like it's still at the `OWNERS`-file, but no code state. Is this still planned to be contributed?)

@evankanderson PR should be merged, next step is to enable the proper tests.

**Comment by rhuss** [comment]
Should work all now.
