### ISSUE TITLE
Update /docs repo tag to opt in for Hacktoberfest

### ISSUE THREAD

**Issue by abrennan89** [knative/community#308]
Hacktoberfest is now opt-in only: https://hacktoberfest.digitalocean.com/hacktoberfest-update
There's a gif in the video that shows what needs to be done, I can take care of the label obviously.
Thanks!

cc @mattmoor

**Comment by mattmoor** [comment]
I added the `hacktoberfest` topic to docs

**Comment by mattmoor** [comment]
/assign @abrennan89 

Ashleigh, lmk if anything else is needed from us, I added to our backlog so it doesn't get lost also.

**Comment by abrennan89** [comment]
@mattmoor that should be all, thank you!
