### ISSUE TITLE
Request approval of SC Election details

### ISSUE THREAD

**Issue by jberkus** [knative/community#311]
As much as possible, the EC is trying to base the elections on the TOC elections of April. However, there are some details we don't know, so I'd like to ask the current SC to approve our choices.

## Timeline:
(assumes that Transition Plan is revised in the next couple days)
- Oct 27: call for nominations and exceptions
- Nov 9: call for nominations closes
- Nov 12: voting begins
- Nov 22: last call for exceptions, ballot replacements
- Nov 29: Voting ends
- Dec 3: announce results

## Voter List
- Oct 15 2019 to Oct 15 2020: relevant period for contributions
- Please check https://knative.teststats.cncf.io/d/68/repository-groups?orgId=1 to see which repositories are not represented that are now part of Knative.  Archived repositories are not an issue.

## Nomination Process
- candidates self-nominate
- candidates nominate by opening a PR against community/elections with their profile, and announce that on knative-dev and/or -users
- candidates need at least one +1 (or lgtm) on that profile to merge, as an endorsement

## Voting Details
- options for CIVS: no opinion allowed, no write-ins, detailed but anonymous ballot reporting
- EC will report full ballot results to the SC privately
- EC will report only winners of election publicly

## General
- we will use Google Forms for exception and ballot replacement forms
- all election dates & reminders will be announced to both knative-dev and knative-users
- election deadlines will go on knative community calendar

Please approve, thanks!

@thisisnotapril @geekygirldawn
@pmorie @bsnchan @mbehrendt @anicolao @ronavn

**Comment by evankanderson** [comment]
I think for TOC elections, we allowed others to nominate as well (but the candidate could decline the nomination). Other than that, the details seem pretty correct.

If you need help collecting / mapping github accounts to working email addresses, I recall that was a little tricky last time and Ryan Gregg had to ask around in a few cases, but we were able to get a lot by cross-referencing with knative-dev@ mailing list if they weren't in the github profile.

**Comment by jberkus** [comment]
Evan: yes, that's likely to be an issue.  We have the list from the TOC election, but I can already see a bunch of addresses that are out-of-date.

My plan was to let folks self-service by just telling us their email addresses in a form.

**Comment by bsnchan** [comment]
Thanks for this @jberkus! What do you mean by "(assumes that Transition Plan is revised in the next couple days)"?

**Comment by geekygirldawn** [comment]
@bsnchan One of the issues we need to resolve before we can start this process is that the transition plan says that "One Google, one IBM/RedHat, and one VMware seat will be retained from the current Steering Committee" After talking to @thisisnotapril, she thought that she might actually still be on the Steering Committee. If so, this makes her ineligible to be one of the election officers, and we would need to replace her before we can start the election process. 

Also, we'll need to come up with a new timeline, since we've already missed our first deadline :)

**Comment by jberkus** [comment]
Also, the Transition plan was written to retain 3 of the current Steering members back when SC was planned to be 7 members, not 5.  So the EC is not clear on whether we're only electing 2 members, or whether we're doing something else entirely.

**Comment by thisisnotapril** [comment]
Plan lgtm!

**Comment by bsnchan** [comment]
Hey @jberkus @geekygirldawn - we had our steering meeting today and confirm that the plan is to retain 3 of the current steering members and have 2 seats up for election (5 seats total).

**Comment by bsnchan** [comment]
The dates will probably need a bit of adjusting, but the plans LGTM :)

**Comment by pmorie** [comment]
The plans look good to me, why don't we adjust the dates to start 10/26?

**Comment by jberkus** [comment]
SC:
See new timeline.

Because of conflicts with the US election, Kubecon, and American Thanksgiving, it's a much longer election timeline than we were originally requesting:

- Oct 27: call for nominations and exceptions
- Nov 9: call for nominations closes
- Nov 12: voting begins
- Nov 22: last call for exceptions, ballot replacements
- Nov 29: Voting ends
- Dec 3: announce results

Please approve, thanks!

**Comment by bsnchan** [comment]
LGTM

**Comment by thisisnotapril** [comment]
LGTM

**Comment by pmorie** [comment]
LGTM

**Comment by mbehrendt** [comment]
LGTM

**Comment by ronavn** [comment]
LGTM

**Comment by pmorie** [comment]
LGTM

**Comment by mbehrendt** [comment]
LGTM

**Comment by jberkus** [comment]
Great!  Given this approval, look for a PR tommorrow with the election folder and the details for voters and candidates.
