### ISSUE TITLE
Migrate slack management to Tempelis

### ISSUE THREAD

**Issue by mattmoor** [knative/community#314]
* Expected benefits. Who gains the benefits? Why will they benefit?

Makes slack channel management self-service through community PRs.

* Expected costs. Who bears the costs? How heavy are they?

Question for @knative/productivity-wg-leads but Tempelis is from the family of tooling we already operate, so hopefully this has a low incremental overhead 🤞 

* Timeframe for implementation / rollout.

Once someone is available...

* Are you willing to drive the process, or is this a request for help?

I'm mostly raising this for tooling awareness, but hopefully this is something that can be driven under the `#productivity` umbrella.

**Comment by mattmoor** [comment]
relevant K8s link: https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-channel

**Comment by rhuss** [comment]
@vaikas Do you track the issue in the SC board so that we can remove it from the TOC board, or should we keep it here as well? I don't think it makes sense track this issue in two boards (just doing some TOC backlog hygienic gymnastics ;-)

**Comment by csantanapr** [comment]
This is on hold, until we move to the CNCF Slack

**Comment by lance** [comment]
Not relevant now that we have moved to CNCF Slack
