### ISSUE TITLE
Update SC representation

### ISSUE THREAD

**Issue by sebgoa** [knative/community#32]
Checking our charter I do not see a provision that describes how and when to update the SC representation by companies.

Right now IBM and RH are a single company and Pivotal has been acquired by VMware.

At a minimum we should update the knative stats and re-check the contributions of companies.

**Comment by rgregg** [comment]
There are two provisions in the KSC charter that define when and how to update membership on the steering committee:
> Seats on the steering committee are allocated based upon contribution to the project by an organization.
> ...
> * Changes to the number of seats, which company seats are allocated to, and nominations to the committee are confirmed by majority vote of the committee members.
> ...
> * Members on the committee have a 1 year term from their confirmation, and may be reconfirmed to the committee at the end of their term.

The Steering Committee hasn't raised the issue, but I'll add it to the agenda for us to discuss how we should update the representation based on the recent acquisitions.

**Comment by jchesterpivotal** [comment]
As a nitpick, Pivotal is still an independent public company at this time, though VMware have announced intent to acquire.

**Comment by rgregg** [comment]
Great point @jchesterpivotal, I know there are strict rules around keeping things separate until a deal closes. I've made sure this is on our agenda, and I expect we'll leave the "how to represent our company" as a question to the individual representatives of each company to resolve.

**Comment by thisisnotapril** [comment]
Closing with #277
