### ISSUE TITLE
New Repo: kn-plugin-source-kafka

### ISSUE THREAD

**Issue by daisy-ycguo** [knative/community#330]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

Org: knative-sandbox

Repo: kn-plugin-source-kafka

Purpose (Description):

The `kn` plugin for Kafka event sources

Sponsoring WG: client

## Actions to fulfill

This area is used to track the [repo creation process](/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [x] Send a PR adding entries for this repo in [`/peribolos/knative-sandbox.yaml`](https://github.com/knative/community/blob/master/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  - [x] Grant the sponsoring WG the `write` privilege.

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [x] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [x] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo master
  ```

- [x] Set up [test-infra](https://github.com/knative/test-infra) following the
  docs linked at the beginning.

- [x] Create a sample PR to verify Prow (e.g. edit the boilerplate README)

**TOC Gate** : _Once Prow has been verified_

- [x] Have a member of the TOC enable branch protections so that `tide` is a required presubmit check.

**Comment by evankanderson** [comment]
Our pattern is `kn-plugins-...`, but otherwise this name seems fine.

**Comment by evankanderson** [comment]
Actually, the prefix _is_ `kn-plugin-...`, so this name should be good, but @maximilien wanted to double-check.

**Comment by mattmoor** [comment]
/assign @grantr 

Grant volunteered to be on point from TOC side

**Comment by grantr** [comment]
I approved https://github.com/knative/community/pull/336, so you should be able to move past the TOC gate now :+1:

**Comment by maximilien** [comment]
Thanks @grantr 
Cc: @daisy-ycguo

**Comment by maximilien** [comment]
We are all good @evankanderson . Thx

**Comment by daisy-ycguo** [comment]
Thanks all. I will go to the next step of TODOs.

**Comment by daisy-ycguo** [comment]
Thank @navidshaikh to add prow jobs for knative-sandbox/kn-plugin-source-kafka, refer to: https://github.com/knative/test-infra/pull/2587

**Comment by navidshaikh** [comment]
> Create a sample PR to verify Prow (e.g. edit the boilerplate README)

The tests works now, see https://github.com/knative-sandbox/kn-plugin-source-kafka/pull/5

Only branch protection needs to be enabled now.

**Comment by navidshaikh** [comment]
ping @grantr

**Comment by grantr** [comment]
Sorry for the delay @navidshaikh, I'll get to this today.

**Comment by grantr** [comment]
Looks like there are a couple files missing from the repo root:
- [CODE_OF_CONDUCT.md](https://github.com/knative-sandbox/wg-repository)
- [OWNERS_ALIASES](https://github.com/knative-sandbox/wg-repository/blob/master/OWNERS_ALIASES)

Once those are present, replace the TOC members in the OWNERS file with the `technical-oversight-committee` alias.

I'll enable branch protection now but leave this issue open until those two files are in place.

**Comment by grantr** [comment]
Actually, looks like branch protection was already enabled. But I verified it was correct :)

**Comment by navidshaikh** [comment]
thanks @grantr!, PTAL https://github.com/knative-sandbox/kn-plugin-source-kafka/pull/15

**Comment by navidshaikh** [comment]
/close 
Thanks @grantr ! https://github.com/knative-sandbox/kn-plugin-source-kafka/pull/15 is merged.
