### ISSUE TITLE
Finalize setup of trademark committee

### ISSUE THREAD

**Issue by pmorie** [knative/community#337]
I believe we still need:

- instructions for how to approach the committee
- backlog github project (for example, #9 is on the steering backlog currently, and this is now in scope for KTC)
- public meeting schedule?

**Comment by bsnchan** [comment]
There is now the Trademark Committee Back log here: https://github.com/orgs/knative/projects/16

We also plan to have a regular public meeting schedule once the steering elections have been completed (and once the committee has had a few private meetings to get kickstarted).
