### ISSUE TITLE
Update STEERING-COMMITTEE.md to match reality

### ISSUE THREAD

**Issue by duglin** [knative/community#34]
From the TSC md file:

> The Knative Steering Committee (KSC) is the ultimate authority for the Knative project, and governs all aspects of the project.

We need to update this sentence to more accurately reflect reality, then people can decide if they want to join, or continue to work, on a project with that governance model. Regardless of whether people agree or disagree with the model, we should at least be honest about what it is.

/assign @lindydonna

**Comment by rgregg** [comment]
We'll take this up as part of the overall updates to the community rules.

**Comment by rgregg** [comment]
The KSC is meeting the week of December 9th to work through some of these open questions and start making progress here.

**Comment by evankanderson** [comment]
I think this is done?

/assign @bsnchan

**Comment by duglin** [comment]
Sort of. What's missing now, and I'll admit it's only obvious due to the history, is what can't the TSC do? ie. What does Google retain control of?

**Comment by duglin** [comment]
Oops - sorry, I was looking at the TOC doc. The SC one is still incorrect IMO

**Comment by bsnchan** [comment]
This feels like it is answered now in https://github.com/knative/community/pull/277.
