### ISSUE TITLE
Security Working Group Charter/Proposal

### ISSUE THREAD

**Issue by julz** [knative/community#347]
We should create a security working group.

Here is a draft Charter for it: https://docs.google.com/document/d/18y5PuAlgKVhe_lpd3sAHvcs7PzEIGi2vy3SvIq1Vj5w/edit?usp=sharing.

Security is a cross-cutting concern which is best addressed pro-actively. Many users of Knative will want to use it to support "-aaS" (multi-tenant) and security sensitive workloads. A Security WG would provide guidance on using Knative successfully in multi-tenant scenarios/for secure workloads, would provide a forum for sharing best practices in this area, would consider features and close gaps (working with other WGs) as needed for Knative to support these use cases, and would review and approve feature proposals from a security/multi-tenancy perspective.

**Comment by evankanderson** [comment]
We discussed this at the 19 Nov 2020 TOC meeting. I'm commenting a bit further on the charter now, but the current formulation -- focusing on general security including but not exclusively hard multi-tenant security (aka hard mode) seems like it fills a useful gap that we've historically said "we can fix that later". At this point, I think later has come.

**Comment by grantr** [comment]
Charter LGTM. Thanks @julz for pulling this together!

**Comment by mattmoor** [comment]
LGTM

**Comment by evankanderson** [comment]
(Mattmoor gave a thumbs-up to approve)

**Comment by evankanderson** [comment]
(General verbal agreement plus 3 official votes -> let's get this ball rolling)

**Comment by evankanderson** [comment]
Remaining items to close this issue:

Update `WORKING-GROUPS.md`, choose a WG meeting time, and figure out where to put roadmap, etc given lack of a "home" git repo.
