### ISSUE TITLE
Golang support policy

### ISSUE THREAD

**Issue by markusthoemmes** [knative/community#355]
We had a fairly extended discussion on the Golang version used in our projects in Slack after [this post](https://knative.slack.com/archives/CCSNR4FCH/p1604071096381100). It might make sense for us to discuss this in ToC, even if only briefly to maybe put out something explicit.

**Comment by evankanderson** [comment]
@markusthoemmes says that Red Hat has a timeline on picking up a new golang version. Here's a chance for others to chime in with their own needs.

**Comment by dprotaso** [comment]
@markusthoemmes what's Red Hat's timeline?

To clarify my point in the slack thread I think all our repos should update their go version to remain in lockstep with what's used in our CI.

There are subtle differences in the build tool chain across go versions and we don't test our hack scripts against older versions. I'm hoping this simple practices helps new contributors.

**Comment by markusthoemmes** [comment]
Yeah, 1.15 is certainly fine anyway, we've got that in our pipelines too.

Unfortunately, our internal Golang releases are currently slower than we'd like, but we're giving input into that process and if we roughly follow what K8s is doing wrt. timing, we should probably be fine. Let's not let this discussion stop an upgrade to 1.15 at all.

**Comment by dprotaso** [comment]
> we roughly follow what K8s is doing wrt. timing, we should probably be fine.

What does K8s do?

Regardless of the _when_ we adopt a specific version I'd like us to formalize/automate a lockstep bump process.

**Comment by evankanderson** [comment]
Matt suggests that we should use a minor version of Go which has been available for the entire release cycle.

Markus wants to know if we need to support multiple Golang versions for building e.g. `knative/serving`. General consensus was "no".

**Comment by mattmoor** [comment]
/assign @markusthoemmes 

Markus is going to write up what we discussed today.

**Comment by evankanderson** [comment]
#401 should fix
