### ISSUE TITLE
New Repo: knative/release repo

### ISSUE THREAD

**Issue by dprotaso** [knative/community#360]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

Org: knative

Repo: release

Purpose (Description):

1) We have a bunch of 'release' related documentation split across community and knative.dev/pkg. We should collate these to a single repo
1) Metadata - ie. capturing EOL dates, k8s [hard/soft](https://github.com/knative/community/issues/245#issuecomment-730501532) min versions. 
1) A place for workflow/scripts common to the release processes -  ie. we still have manual steps that can be automated in the release steps in `knative/pkg/RELEASE.md`

Sponsoring WG: Shared responsibility across all WG groups

## Actions to fulfill

This area is used to track the [repo creation process](/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [x] Send a PR adding entries for this repo in [`/peribolos/knative-sandbox.yaml`](https://github.com/knative/community/blob/master/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  - [x] Grant the sponsoring WG the `write` privilege.

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [ ] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [ ] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo master
  ```

- [ ] Set up [test-infra](https://github.com/knative/test-infra) following the
  docs linked at the beginning.

- [ ] Create a sample PR to verify Prow (e.g. edit the boilerplate README)

- [ ] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

- [ ] (optional) Send a PR adding the repo to [knobots](https://github.com/knative-sandbox/knobots).

**Comment by mattmoor** [comment]
I think perhaps consolidating this stuff into community would be my preference.

**Comment by evankanderson** [comment]
I recommend `community/mechanics/release`.

**Comment by dprotaso** [comment]
I hope this repo in the future could be the main point for:

1) Metadata - ie. capturing EOL dates, k8s [hard/soft](https://github.com/knative/community/issues/245#issuecomment-730501532) min versions
2) A place for workflow/scripts common to the release processes -  ie. we still have manual steps that can be automated in the release steps in `knative/pkg/RELEASE.md`

**Comment by dprotaso** [comment]
Some feedback about our release process: https://groups.google.com/g/knative-dev/c/jQsloZD-sW8

> What I generally struggled with is that we have 2 CI systems, one does the checks, one does the actual release, and in the middle tons of bash scripts. We even have separate repos where we have github actions, prow jobs, knobots jobs, etc. Sometimes it was hard for me to grasp which tool was doing what and how, consequently limiting my ability to solve issues. My take is that It would be nice if we manage, at some point, to transition to just using a single tool which performs from the click to the actual release, without asking for human intervention in the middle (branch cutting, pinning deps PRs stamping, etc). This makes the release lead able to better understand what's going on and, at the same time, having a simple system where each step is well defined helps troubleshooting and "manual triggers" when something goes wrong.

I'm hoping this repository could be that central place

**Comment by evankanderson** [comment]
GitHub actions seems to be a driving rationale for making this a separate repo vs test-infra

Approved at 21 Jan 2020 meeting
