### ISSUE TITLE
Working Group Proposal: Knative Conformance

### ISSUE THREAD

**Issue by tayarani** [knative/community#381]
I would like to propose a new Knative Conformance WG based on this charter:

https://docs.google.com/document/d/1ggSKzyVKmcFgUecAxZxAI5QBqHaQA_rq3x9IrMWKBy8/edit#

**Comment by mattmoor** [comment]
/assign @knative/trademark-committee

A few of us want @knative/trademark-committee to weigh in on what the actual policies are here.  I am going to move this to "Wait on input" from them.

**Comment by bsnchan** [comment]
Based off our last Trademark Committee Meeting on February 25, 2021 (meeting minutes [here](https://docs.google.com/document/d/1ghGQl0O7TM8N_YQ33w6xKyQ2yUnOX0ACsOnlqoV_XgY/edit)), I believe the trademark committee is all in favour of this WG. This will be a WG that is the "technical arm" of the Knative Trademark Committee.

/lgtm

@duglin @ronavn can one of you approve please?

**Comment by evankanderson** [comment]
This got sponsored through trademark rather than TOC.

**Comment by grantr** [comment]
The proposal above is obsolete. The charter proposal approved by the Trademark Committee is https://docs.google.com/document/d/11QhP-EjL3_rmYiIzkNAYe-Sn-zR2D1zCzftLXhhASFI/edit.

**Comment by bsnchan** [comment]
Since @tayarani has moved on to another team, I believe we no longer have anyone leading this working group so I'll close out this issue.
