### ISSUE TITLE
We don't have a process/criteria for promoting projects to a 1.0/GA status.

### ISSUE THREAD

**Issue by dprotaso** [knative/community#383]
note: please don't make this a technical discussion about go module versions - that's orthogonal to the version number end-users see

We've forever been on the 0.x release train. I think end-users have an expectation that a 1.0 version signals the release is stable and will be supported.

How should projects switch to a `1.0` version to signal this GA status?

**Comment by dprotaso** [comment]
@knative/steering-committee I can't add this to your backlog

This seems like a joint discussion amongst various leadership groups

**Comment by dprotaso** [comment]
cc @knative/technical-oversight-committee @knative/trademark-committee

**Comment by evankanderson** [comment]
I think there are some missing 

* Knative Trademark Committee should probably understand the scope of what's being licensed.
* Any other Steering/TOC bar that we don't already have, but trademark seems to be the big blocker.

**Comment by evankanderson** [comment]
Possibly also relevant: https://github.com/knative/community/pull/229

**Comment by evankanderson** [comment]
In particular, for a GA product, we'd like to be able to tell users who download a Knative release when they are or are not allowed to call what they are running "Knative".

**Comment by csantanapr** [comment]
One thing to add to the checklist for 1.0 is observability on the control plane. 
For a platform to be able to manage a knative 1.x certain metrics labels should not change.

**Comment by evankanderson** [comment]
This is two parts:

* What is the scope covered under the Knative mark
* What are the rules for mark usage on the covered parts.

This seems like *one* of the "is everything ready to go" items on the 1.0 checklist. We should think about things like docs requirements (if any additional) or security reporting processes (for example) as other items.

**Comment by evankanderson** [comment]
We need a rough shape of the scoping from Trademark Committee before TOC can weigh in on technical requirements.

Understanding what "Knative 1.0" might mean will help in terms of setting requirements.

Related #131

**Comment by evankanderson** [comment]
Would love to see a writeup of the various facets of a software product (technical and non-technical) that we could use to assess and draw a bar:

* Test coverage (unit and/or functional)
* User Documentation
* Reliability
* Administrator Documentation
* Licensing / redistribution rules (trademark et al)
* Scope covered
* User feedback / usage

Matt points out that we need to be able to call out certain features as non-GA/1.0 within a "GA-ready" API at a field or object level.

There's also a doc that Matt wrote about what was needed for Serving "1.0".

**Comment by evankanderson** [comment]
https://docs.google.com/presentation/d/1qyUtoSmzhh11SWahjaf3o_bE_M8eO6rf_uRinqczv-Q/edit#slide=id.p

**Comment by evankanderson** [comment]
Also this (more recent) doc: https://docs.google.com/document/d/1i5wfLldNI8gw8hvQPaO5XegVCJ5dga3_U9xgBueFGY8/edit?resourcekey=0-3Ni-QVVakAQGW-jWnO82kQ

**Comment by dprotaso** [comment]
cc @julz @richterdavid re: security wg

**Comment by duglin** [comment]
All - current thought process around defining the scope of the various groups (ktc, sc, toc), plans for the conformance wg, and a proposal for how to get to GA:  https://docs.google.com/document/d/1TGtzYZjukEm1657XEQgTF-FUwoLGrVmLErRcCYaeLjw/edit#

feedback is welcome. In particular, around what versioning scheme we should use.

**Comment by csantanapr** [comment]
As a ✏️ item I have seeing a lot of mini virtual conferences lately IstioCon, CDCon, ZertoCon, etc

one idea is when we declare 1.0 we can make some more noise 🎉  by having a KnativeCon align with the milestone.

**Comment by vaikas** [comment]
This was raised 2021-03-18 in TOC and we've been discussing this in the WGs, Trademark committee and Steering. Notes for the TOC mentions a possibility of TPM helping coordinate this across various repos.

**Comment by evankanderson** [comment]
Work to do:

* [ ] Someone to own the process

For each governing group:
* [ ] Collect a set of requirements from KTC
* [ ] Collect a set of requirements from SC
* [ ] Collect a set of requirements from TOC

We'll crowdsource the requirements as well and track which group has approved the addition of items to the requirements.

Spreadsheet incoming later today.

**Comment by evankanderson** [comment]
Created a spreadsheet for tracking work for a "1.0" effort: https://docs.google.com/spreadsheets/d/1h4OjOi2eML7LhuxE9BuN2X0lG_bf5dYbF5f3ecKh1gQ/edit#gid=0

For non-trademark-covered components, there is this definition of maturity levels (which might need updating once we've reviewed the spreadsheet): https://github.com/knative/community/blob/main/mechanics/MATURITY-LEVELS.md

**Comment by rhuss** [comment]
> Created a spreadsheet for tracking work for a "1.0" effort: https://docs.google.com/spreadsheets/d/1h4OjOi2eML7LhuxE9BuN2X0lG_bf5dYbF5f3ecKh1gQ/edit#gid=0

@evankanderson the link leads to 

![image](https://user-images.githubusercontent.com/99080/124155124-6fc40900-da96-11eb-89ca-e2e28d5298c8.png)

and

![image](https://user-images.githubusercontent.com/99080/124155315-a732b580-da96-11eb-9839-1fc5fa6dbcdf.png)

which is a bit confusing. Do you have the link to the final spreadsheet handy ?

**Comment by rhuss** [comment]
ah, found it:

https://docs.google.com/spreadsheets/d/1dH4c3_2bZUQn6nz09Hmn5VLcVNUV1ZocCEAN76jYjas/edit#gid=0

**Comment by evankanderson** [comment]
Yes, correct link (sorry!)

https://docs.google.com/spreadsheets/d/1dH4c3_2bZUQn6nz09Hmn5VLcVNUV1ZocCEAN76jYjas/edit#gid=0

**Comment by omerbensaadon** [comment]
1.0.Alpha Project. Targeting August 15th 

https://github.com/orgs/knative/projects/26

**Comment by vaikas** [comment]
SC doesn't think there's anything that we need to do on this anymore, so removing from our backlog. If there are particular items, maybe open specific issues?
