### ISSUE TITLE
2020 voters list appears twice in docs

### ISSUE THREAD

**Issue by abrennan89** [knative/community#385]
![image](https://user-images.githubusercontent.com/40172997/100272014-0daf8e00-2f20-11eb-98dc-68d046dd7321.png)

In the Contribution Guidelines docs page:
https://knative.dev/community/contributing/

2020 voters list appears twice in the left nav bar. These two instances should probably be grouped into one page?

**Comment by vaikas** [comment]
@abrennan89 I think this went away in the reorg of the docs? If so, can this be closed?

**Comment by abrennan89** [comment]
Yeah, I don't think that page was ever supposed to be there, and if I go to that link now I don't see it, so probably OK to close this. Thanks @vaikas !
