### ISSUE TITLE
New Repo: net-ingressv2

### ISSUE THREAD

**Issue by ZhiminXiang** [knative/community#389]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

Org: knative-sandbox

Repo: net-ingressv2

Purpose (Description):
This repo is used for the code of integrating with k8s Ingress V2. 

Sponsoring WG: Networking

## Actions to fulfill

This area is used to track the [repo creation process](/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review. You are responsible for moving your entry on the board to "Needs Discussion" or "In Progress" as you move forward in this checklist.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [x] Send a PR adding entries for this repo in [`/peribolos/knative-sandbox.yaml`](https://github.com/knative/community/blob/master/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  - [x] Grant the sponsoring WG the `write` privilege.

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [x] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [x] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo master
  ```

- [x] Set up [test-infra](https://github.com/knative/test-infra) using the [hack](https://github.com/knative-sandbox/hack) project.

- [x] Add your GitHub ID to the `OWNERS` file for your repo.

- [x] Create a sample PR to verify Prow (e.g., edit the boilerplate README)

- [x] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

- [x] (optional) Send a PR adding the repo to [knobots](https://github.com/knative-sandbox/knobots).

**Comment by mattmoor** [comment]
Can we use `net-ingressv2`?

**Comment by mattmoor** [comment]
(or even just `net-ingress`)

**Comment by ZhiminXiang** [comment]
`net-ingressv2` sounds good to me.

**Comment by evankanderson** [comment]
/assign @tcnghia 

To shepherd, I'm guessing @ZhiminXiang will do most of the PRs.

**Comment by nak3** [comment]
> Peribolos will create an empty repository.

Peribolos is broken https://testgrid.knative.dev/utilities#post-knative-sandbox-peribolos and new `net-ingressv2` repo is not created.

I am fixing it now in https://github.com/knative/community/pull/406.

**Comment by nak3** [comment]
> - [ ] Bootstrap your CI jobs using [hack](https://github.com/knative/hack) project (look at other sandbox repos for reference)
> 
> - [ ] Create a sample PR to verify Prow (e.g., edit the boilerplate README)
>
> - [ ] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

The new repo was created and TODO list except for above prow stuff were done.
The prow is currently broken because the default branch is  `main`  instead of `master`. The issue was already created https://github.com/knative/test-infra/issues/2632
