### ISSUE TITLE
Hello World - Dart(community/samples/serving/helloworld-dart/index.md)

### ISSUE THREAD

**Issue by kevmoo** [knative/community#396]
Edit points to content that isn't there: 

https://github.com/knative/community/tree/master/samples/serving/helloworld-dart/README.md

Should point to 
https://github.com/knative/docs/blob/master/community/samples/serving/helloworld-dart/README.md

**Comment by vaikas** [comment]
@kevmoo where are you seeing this link at? I can't find it anywhere in this repo.

**Comment by kevmoo** [comment]
Maybe it's all fixed now. 🤷
