### ISSUE TITLE
PROCESS CHANGE: Add a rotation app to slack to remind people when they are a community contact

### ISSUE THREAD

**Issue by grantr** [knative/community#402]
We now have a community contact rotation for eventing and other WGs, but there's no great way to notify people when they're up next in the rotation. This seems like a good case for a slack app to manage the schedule and notifications.

Bonus, this might be useful for the TOC presentation rotation.

Here are a few blogs about such things I found in a quick google search:
https://medium.com/in-the-weeds/round-robin-rotating-responsibilities-responsibly-f4a9b44e174c
https://dev.to/kimmaida/hello-rota-a-slackbot-for-rotation-management-216c

**Comment by aliok** [comment]
Is this still relevant?

**Comment by krsna-m** [comment]
There is a very limited number of approved slack apps we can access. I used zapier to create a bot that runs weekly https://zapier.com/webintent/edit-zap/222341604?source=slack to check a schedule https://docs.google.com/spreadsheets/d/1Gw6j5dZzTUJBNBLFlepeyUPz4uI-GaLuzpj83uyqj1c/ spreadsheet to generate the slack messages that will go into `#knative-contributors` channel.

Things to note:
1. There is no biweekley schedule so there is still some conditions that need to be included to have it skip non eventful weeks.
2. The date in the google sheet needs to stay in that format for the automation as the schedule part of the workflow does not allow an alternative `dd` (zero leading) format.
3. The zapier app is currently under my knative teams email.

**Comment by krsna-m** [comment]
Unfortunately, the zapier solution requires 3 steps [schedule, sheets, slack] and thus requires payment. I opened a PR for a GHA solution that solves all the shortcomings of zapier

**Comment by dprotaso** [comment]
TOC reminder is here - https://github.com/knative/community/blob/main/.github/workflows/toc-review-reminder.yaml
