### ISSUE TITLE
Backfill charters for all working groups

### ISSUE THREAD

**Issue by dprotaso** [knative/community#410]
It's unclear from [WORKING-GROUPS.md](https://github.com/knative/community/blob/master/working-groups/WORKING-GROUPS.md) what is the scope of existing working groups and the problems they are trying to solve.

We should have our WGs backfill/refine their charters.

**Comment by rhuss** [comment]
Any idea about some recommendations for the WG ? E.g. "2-3 sentences that we will be put between headline and artifact table"

If so I can go out to slack and collect the teasers.

**Comment by dprotaso** [comment]
I think for me the main goal of the charters for me was the communicate the scope of the working group.

ie. is productivity there to keep CI and automation running or are they building tooling to enhance the contributor experience.

**Comment by evankanderson** [comment]
I think we have these (though they may be outdated) for most of the WGs except the ones that started before the TOC was meeting regularly (roughly, pre-reveal near Google I/O 2018).

I can dig those out and markdownify them and put them in working-groups/$GROUP/charter.md for ongoing maintenance to happen there, alongside an OWNERS file to let the WG leads manage them themselves.

**Comment by rhuss** [comment]
@evankanderson that sounds good to me, to populate the `working-groups/` directory wg-specific directories and add the charter in there. Maybe we then could include those charters directly in the overview WORKING-GROUPS.md document ?

We could go even one step further and also add all WG specific information into the subdirs, like the lead list and the communications channels, and then concatenate those files for the website ?
