### ISSUE TITLE
[policy] Adopting new K8s features optionally

### ISSUE THREAD

**Issue by dprotaso** [knative/community#412]
@julz will write up something about how to adopt new K8s features _optionally_, rather than as a hard dependency, to allow adopting newer k8s features while still supporting older k8s installs as well.

_Originally posted by @evankanderson in https://github.com/knative/community/issues/245#issuecomment-738143182_

**Comment by rhuss** [comment]
@julz any updates on the document ? Curious myself as it could be useful for the client project, too.

**Comment by dprotaso** [comment]
I'm going to close this out as there hasn't been much discussion/action here

**Comment by dprotaso** [comment]
Secondly, we haven't had requests to adopt any newer features
