### ISSUE TITLE
PROCESS CHANGE: Knative Release Lead needs more power

### ISSUE THREAD

**Issue by slinkydeveloper** [knative/community#414]
As outlined in the mail sent to knative-dev, release leads, in order to properly deliver the release, needs:

* lgtm and approver rights in every knative & knative-sandbox PR
* HackMD rights to create the document with the release notes (maybe we can just add all approvers, without any automation here?).
* Rights to trigger jobs to prow, like retrigger auto-release jobs, nightly, dot release etc. (I think these are the rights that knative milestone maintainer group contains)
* Rights to delete a release from Github
* Rights to delete a protected release branch

For more details: https://groups.google.com/g/knative-dev/c/jQsloZD-sW8/m/8E31LeFGCgAJ

**Comment by vaikas** [comment]
@evankanderson can this be closed?
https://github.com/knative/community/blob/main/peribolos/knative.yaml#L875
https://github.com/knative/community/blob/main/peribolos/knative-sandbox.yaml#L689

At least I think when I did .23 with @tcnghia all went well there. Just adding @dprotaso and @matzew in case they had any troubles with .24.

**Comment by dprotaso** [comment]
> Rights to trigger jobs to prow, like retrigger auto-release jobs, nightly, dot release etc. (I think these are the rights that knative milestone maintainer group contains)

I added the release team to the list - https://github.com/GoogleCloudPlatform/oss-test-infra/pull/937

I'd say the outstanding thing is:

> HackMD rights to create the document with the release notes (maybe we can just add all approvers, without any automation here?).

I just made a new random doc last round people were able to edit so unsure how important this is 🤷‍♂️
