### ISSUE TITLE
New Repo: knative-sandbox/kn-plugin-migration

### ISSUE THREAD

**Issue by zhangtbj** [knative/community#423]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

Org: knative-sandbox

Repo: kn-migration

Purpose (Description):
From the Serving WG meeting on [2020-08-05](https://docs.google.com/document/d/1NC4klOdNaU-N-PsKLyXBqDKgNSHtxCDep29Ta2b5FK0/edit#heading=h.wfetj9f1dqvz), the original kn plugins in https://github.com/knative/client-contrib should move to the new `knative-sandbox` repo, as the kn-migration plugin owner, I plan to provide this issue and PR to move the plugin to the new repo.

kn-migration plugin allows you to migrate Knative service including the all revisions and configurations from the source cluster to the destination cluster.

<img width="935" alt="step3" src="https://user-images.githubusercontent.com/18108042/106421826-66f3ea80-6498-11eb-974b-7dde60fdf5be.png">

**Use cases**
- As a knative serving user, I want to list all Knative serving resources in one namespace of my cluster.
- As a knative serving user, I want to migrate all of knative serving including all revision and configurations from source cluster to destination cluster.
- As a knative serving user, I can choose to delete the knative services on source cluster or force update the knative services on destination cluster.
- As a knative serving user, I want to see what knative serving resources are migrated and how they are migrated during the execution.

Sponsoring WG:
Serving WG

## Actions to fulfill

This area is used to track the [repo creation process](/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review. You are responsible for moving your entry on the board to "Needs Discussion" or "In Progress" as you move forward in this checklist.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [ ] Send a PR adding entries for this repo in [`/peribolos/knative-sandbox.yaml`](https://github.com/knative/community/blob/master/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
  - [ ] Add the repository and a description.
  - [ ] Grant `Knative Admin` the `admin` privilege.
  - [ ] Grant the sponsoring WG the `write` privilege.

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [ ] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [ ] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo master
  ```

- [ ] Add your GitHub ID to the `OWNERS` file for your repo.

- [ ] [Set up](https://github.com/knative/test-infra/blob/master/guides/prow_knative_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge) prow for a new repo

- [ ] Bootstrap your CI jobs using [hack](https://github.com/knative/hack) project (look at other sandbox repos for reference)

- [ ] Create a sample PR to verify Prow (e.g., edit the boilerplate README)

- [ ] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

- [ ] (optional) Send a PR adding the repo to [knobots](https://github.com/knative-sandbox/knobots).

**Comment by zhangtbj** [comment]
Good day @maximilien ,

As I know, we planned to move all plugins from `client-contrib` to `knative-sandbox` repo.

I also opened this issue to follow the process.

The first step is: **Add this issue to the TOC project board for review.**

Could you please help add it to review or let me know if any action I need to take first?

Thanks a lot!

**Comment by zhanggbj** [comment]
@zhangtbj I just created an issue to the TOC project for tracking and further discussion.
could you please also update the repo name, as all plugins are following the naming rule like `knative-sandbox/kn-plugin-xxxx`, thanks!

FYI, as discussed at WG meeting^^^ @maximilien @rhuss

**Comment by zhangtbj** [comment]
Provided a PR: https://github.com/knative/community/pull/428 adding entries for this repo in `/peribolos/knative-sandbox.yaml`

**Comment by zhangtbj** [comment]
Close this one and switch to use the new one: https://github.com/knative/community/issues/433
