### ISSUE TITLE
New Repo: kn-plugin-migration

### ISSUE THREAD

**Issue by zhanggbj** [knative/community#427]
https://github.com/knative/community/issues/423

**Comment by rhuss** [comment]
@zhanggbj oops, I just added a similar issue in #433 ;-) + also the required PR in #432 

Maybe we can close this one and continue on #433 ? You can also copy over the description to the issue as this is more complete here then over there.

**Comment by zhanggbj** [comment]
@rhuss I'll close this one, #433 have more description there. thanks!
