### ISSUE TITLE
PROCESS CHANGE: Establish docs release rotation

### ISSUE THREAD

**Issue by vaikas** [knative/community#429]
As discussed in #101 there currently is no docs release rotation. @RichieEscarez is the ongoing docs release lead and requires additional rights especially in knative/docs and knative/website repos.

We should establish a regular docs release lead rotation as per other repos, or alternatively, figure out a way to make the docs release process so that release leads can perform these duties as part of the normal release process.

* Expected benefits: Docs release process to behave like the other repos release process.
* Expected costs: Initial cost will be @RichieEscarez figuring out what the diff is between the docs release process and determining how we might be able to modify it so that it will be in line with the other repos. After that we can get an actual estimate of the work that needs to be done.
* Timeframe for implementation / rollout: Ideally we'd tackle this asap at least to understand what work there is to be done so we can plan / schedule accordingly.
* This is a request for help since I'm not clear what the actual release process in docs/website is.

**Comment by RichieEscarez** [comment]
Ive started the "how to" instructions a while back but other priorities pulled me away. I'll be picking this back up this week, status is being tracked here: https://github.com/knative/docs/issues/2960

**Comment by RichieEscarez** [comment]
MVP for a docs release:

Update the API docs: https://github.com/knative/docs/pull/3426
Add the new version to the site: https://github.com/knative/website/pull/287

**Comment by vaikas** [comment]
@omerbensaadon @RichieEscarez Should we add these steps to here:
https://github.com/knative/release

**Comment by csantanapr** [comment]
All the contribution docs got released on the website, thanks to @RichieEscarez 

You can find how to release the current docs here https://knative.dev/help/maintainer/docs-release-process/
These instructions need to use for 0.23 release using hugo, for release 0.24 will have updated instructions for mkdocs

**Comment by csantanapr** [comment]
I will add the link in https://github.com/knative/release

**Comment by csantanapr** [comment]
@vaikas Not sure what type of updates you want to see in https://github.com/csantanapr/knative-release/blob/main/README.md
