### ISSUE TITLE
New Repo: kn-plugin-event

### ISSUE THREAD

**Issue by rhuss** [knative/community#438]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

Org: knative-sandbox

Repo: kn-plugin-event

Purpose (Description): A kn plugin that sends CE to destinations, which is useful for development and debugging.
See https://github.com/cardil/kn-event for a prototype.

Sponsoring WG: client

## Actions to fulfill

This area is used to track the [repo creation process](/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [X] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review. You are responsible for moving your entry on the board to "Needs Discussion" or "In Progress" as you move forward in this checklist.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [X] Send a PR adding entries for this repo in [`/peribolos/knative-sandbox.yaml`](https://github.com/knative/community/blob/master/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
  - [X] Add the repository and a description.
  - [X] Grant `Knative Admin` the `admin` privilege.
  - [X] Grant the sponsoring WG the `write` privilege.

PR: https://github.com/knative/community/pull/437

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [X] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

--> https://github.com/knative/website/pull/251

- [X] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo master
  ```

- [X] Add your GitHub ID to the `OWNERS` file for your repo.

- [X] [Set up](https://github.com/knative/test-infra/blob/master/guides/prow_knative_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge) prow for a new repo

--> https://github.com/knative/test-infra/pull/2712

- [x] Bootstrap your CI jobs using [hack](https://github.com/knative/hack) project (look at other sandbox repos for reference)

- [x] Create a sample PR to verify Prow (e.g., edit the boilerplate README)

- [x] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

- [X] (optional) Send a PR adding the repo to [knobots](https://github.com/knative-sandbox/knobots).

--> https://github.com/knative-sandbox/knobots/pull/61

**Comment by cardil** [comment]
Thanks for adding this @rhuss

**Comment by markusthoemmes** [comment]
I think this is done. tide is active and knobots should pass. At least nothing left to do for the TOC I think.
