### ISSUE TITLE
PROCESS CHANGE: Adopt K8s infra for gsuite mgmt

### ISSUE THREAD

**Issue by mattmoor** [knative/community#443]
I plugged this [here](https://github.com/knative/community/issues/86#issuecomment-601946451), but opening a separate issue to track the automation aspect of this.

cc @knative/productivity-wg-leads

**Comment by mattmoor** [comment]
cc @dims for any additional grand wisdom on this tooling 🙏

**Comment by dims** [comment]
Here's what we have:
1. A tool that reads a groups.yaml (google groups in k8s.io domain and list of owners/members/managers) and can create/add/delete google groups (and folks in those groups). please see https://github.com/kubernetes/k8s.io/tree/master/groups
2. once we have the google groups from step 1, we use those google groups as ACL(s) to GCP based resources (who all can update say a GCS bucket). please see https://github.com/kubernetes/k8s.io/tree/master/infra/gcp for scripts that can create GCP resources and apply ACL's.

We talk about these tools above and bunch more in the "K8s Infra WG" over at https://github.com/kubernetes/community/tree/master/wg-k8s-infra please feel free to join us on the k8s slack or drop into our meeting(s)

**Comment by vaikas** [comment]
Thanks @dims !! I'll go do some reading :)

**Comment by evankanderson** [comment]
We'll need to move `knative-users` and `knative-dev` to `@knative.team` to enable API access to these groups.

**Comment by chizhg** [comment]
We can probably still have different groups for different level of access? Such as:
- `knative-users` is for the users, and will only be granted limited view access
- `knative-dev` is for the developers, and will be granted full view access and _some_ editor access
- `knative-admin` is for the admins, and will be granted full access

**Comment by upodroid** [comment]
@chizhg Can you add kind/cncf-infra label to this issue?

It should be a prerequisite for https://github.com/knative/test-infra/issues/2976 

I'll work on this next.

**Comment by chizhg** [comment]
The label does not exist yet for this repo, I have created https://github.com/knative/test-infra/pull/3026 to add the label for the knative org.

**Comment by chizhg** [comment]
@upodroid the label has been added for this issue.
