### ISSUE TITLE
Inconsistent election docs for TOC/Steering

### ISSUE THREAD

**Issue by mattmoor** [knative/community#447]
I noticed that [this](https://github.com/knative/community/tree/master/elections#knative-steering-committee-elections) was `TBD` after @vaikas linked it in TOC today, and wanted to track some of what I uncovered pulling on the "loose thread".

I don't think the above has a good analog for steering in our docs, it reads sort of like a playbook, and I don't see anything at that same level for steering.  So I think this `TBD` is AI number `1.`

---

Digging into this a bit, `STEERING-COMMITTEE.md` has [this](https://github.com/knative/community/blob/master/STEERING-COMMITTEE.md#election-procedure) section, for which `TECH-OVERSIGHT-COMMITTEE.md` has no analog.  However, these extra bits in `STEERING-COMMITTEE.md` feel mostly redundant with [`SC.md`](https://github.com/knative/community/blob/master/mechanics/SC.md) which is very similar to [`TOC.md`](https://github.com/knative/community/blob/master/mechanics/TOC.md).

This redundancy will almost certainly drift and create confusion, so I believe we should cut (and optionally cross-link?) the redundancy in `STEERING-COMMITTEE.md`, and keep `SC.md` which is consistent with `TOC.md` already.

cc @knative/technical-oversight-committee @knative/steering-committee @jberkus @geekygirldawn @macruzbar

**Comment by bsnchan** [comment]
Oh wow, thanks for catching this. We'll make sure to prioritize cleaning this up in steering!
