### ISSUE TITLE
Change the emails for Knative prow robots.

### ISSUE THREAD

**Issue by vaikas** [knative/community#448]
Currently:
https://github.com/knative-prow-robot

Belongs to google.com domain. As discussed on 2021-02-03 and 2021-02-11 SC meeting, there is no reason for this, and @thisisnotapril has done some investigation into the matter and k8s for example has set this up so that various folks have access to the robot (not sure of the details). This would make it easier for external folks like @n3wscott to be able to attend to more matters pertaining to prow troubleshooting, as well as fixing issues as they come up.

So, this issue should track figuring out how do we move the account over and who (most natural would probably be productivity WG leads) should have access to the robot, etc.

I'm assigning this to @thisisnotapril and @n3wscott to sort out what needs to be done, how to do it. Feel free to delegate as necessary :)

**Comment by vaikas** [comment]
@n3wscott @thisisnotapril any updates on this?

**Comment by thisisnotapril** [comment]
@n3wscott could we take the [Knative prow infra](https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/knative) and move it from the current GCP-owned repo to a Knative repo? Then our permissions would apply. We'd need to update where Prow looks for our config; I am assuming (hopefully not too radically) that would be an easy change.

**Comment by vaikas** [comment]
Let's try to make this move on 2021-04-12 and see what all breaks and then decide if we should continue or revert.
@n3wscott @thisisnotapril

**Comment by vaikas** [comment]
Let's wait on this until after the .23 release since we do not have cycles to deal with this, nor is this the biggest problem we're dealing with at the moment.

**Comment by bsnchan** [comment]
We decided to push this to post 1.0

**Comment by vaikas** [comment]
@thisisnotapril @n3wscott is this something that we might now be able to tackle? How does (if at all) this relate to the new CLA work also going on.

**Comment by n3wscott** [comment]
I sure could, what is the new CLA work? I don't know that one.

**Comment by evankanderson** [comment]
We need to figure out the plan here; my naive assumption is that this was simply a password associated with the GitHub user named `knative-prow-robot`. I think we need to figure out some way to escrow these credentials and figure out who has access to that secret.

**Comment by evankanderson** [comment]
(There's also a published email for this account, but that should be possible to change.)

**Comment by evankanderson** [comment]
There are some other robots that we could probably remove from the org: `google-prow-robot`, `k8s-ci-robot`.

**Comment by lance** [comment]
@upodroid @kvmware ping - can this be moved to productivity?

**Comment by upodroid** [comment]
I can login to the bot and change its email to automation+prow-robot@knative.team so the account is owned by the community.

I'll do this next week. I might need to speak to the Googlers who can access the old mailing list.

**Comment by nainaz** [comment]
@upodroid Do you have any updates on this?

@lance do you know what happened to knative.team domain?

**Comment by nainaz** [comment]
Need to assign it to Productivity group.

**Comment by upodroid** [comment]
I fixed this today. https://github.com/knative/community/pull/1374

/close

**Comment by lance** [comment]
@knative/productivity-leads should this be in your wheelhouse instead of steering?

**Comment by kvmware** [comment]
I think if it has to do with billing or membership it should be steering otherwise probably us

**Comment by upodroid** [comment]
This is done now.

https://github.com/knative-prow-robot
https://github.com/knative-prow-updater-robot
