### ISSUE TITLE
Update the WG doc to include the Github team alias

### ISSUE THREAD

**Issue by csantanapr** [knative/community#450]
Update the [WG doc](https://github.com/knative/community/blob/master/working-groups/WORKING-GROUPS.md) to include the Github team alias `@<wg>` 

This would make it easier to discover how to @ a team in an issue or PR, for example in docs we need to assign PRs that need the WG to take care of the PR to resolution and for new members to the community, they might not know what's the team alias.

Take the current info from [peribolos](https://github.com/knative/community/blob/master/peribolos/knative.yaml)

cc @evankanderson

**Comment by csantanapr** [comment]
I see now from the peribolos file the conversion is


`Productivity WG Leads:` -> `@knative/productivity-wg-leads `

**Comment by csantanapr** [comment]
Just testing something,  @knative/api-core-wg-leads

**Comment by csantanapr** [comment]
@mattmoor @evankanderson 

Why the Docs WG github team shows 0 members?
![image](https://user-images.githubusercontent.com/1094878/107819624-794b0f80-6d47-11eb-885a-01cd3f92cc4b.png)

**Comment by mattmoor** [comment]
Because Ashleigh stepped down, and we had no backup 😞

**Comment by csantanapr** [comment]
I'm aware of that but her github id is the peribolos file, I thought the peribolos file drove the github team
