### ISSUE TITLE
New Repo: icons

### ISSUE THREAD

**Issue by joshuawilson** [knative/community#453]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

Org: knative-sandbox

Repo: icons

Purpose (Description): A set of icons for use across the Knative community and projects.

Sponsoring WG: client / UX

## Actions to fulfill

This area is used to track the [repo creation process](/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [ ] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review. You are responsible for moving your entry on the board to "Needs Discussion" or "In Progress" as you move forward in this checklist.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [ ] Send a PR adding entries for this repo in [`/peribolos/knative-sandbox.yaml`](https://github.com/knative/community/blob/master/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
  - [ ] Add the repository and a description.
  - [ ] Grant `Knative Admin` the `admin` privilege.
  - [ ] Grant the sponsoring WG the `write` privilege.

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [ ] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [ ] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo master
  ```

- [ ] Add your GitHub ID to the `OWNERS` file for your repo.

- [ ] [Set up](https://github.com/knative/test-infra/blob/master/guides/prow_knative_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge) prow for a new repo

- [ ] Bootstrap your CI jobs using [hack](https://github.com/knative/hack) project (look at other sandbox repos for reference)

- [ ] Create a sample PR to verify Prow (e.g., edit the boilerplate README)

- [ ] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

- [ ] (optional) Send a PR adding the repo to [knobots](https://github.com/knative-sandbox/knobots).

**Comment by joshuawilson** [comment]
Since the icons are to be used across all of knative, should they be in knative proper? I do not expect the repo to hold code or require it to be built.

**Comment by csantanapr** [comment]
Should these icons be located in a directory under community or docs repo?

Are these icons ones that the  @knative/trademark-committee needs to review and approve, or maybe just protect so if they are unique to knative no other project or product should use inappropriate to confuse the branding/design.

**Comment by joshuawilson** [comment]
I agree that  @knative/trademark-committee needs to at least protect them. They are unique in the sense that I draw them each. I don't have the tools to search for similar icons that would infringe on another Trademark. Though I did do multiple google image searches when I was drawing them to avoid copying someone. They may want to review them too.

I do not think Docs is the right location because more then Docs will use them. Community might be the right place. My intention is to ensure they are available to the entire knative community and so they need a visible home some place.

**Comment by bsnchan** [comment]
I'd be happy to approve them as a directory under the community repo. Please let us know if that doesn't work for you!

**Comment by joshuawilson** [comment]
@bsnchan I made a PR https://github.com/knative/community/pull/457

Closing this as the above PR covers it.

**Comment by csantanapr** [comment]
Thank you @bsnchan 👍
