### ISSUE TITLE
Idea: contributor of the month!

### ISSUE THREAD

**Issue by pmorie** [knative/community#469]
We should have a contributor of the month program:

Capturing suggestions from our discussion in steering; none of these are finalized, just meant to see convo

- Eligible voters vote
- Results announced in community meeting
- Start with one and see if we should do multiples every month or by area
- Swag and recognition (@vaikas and I will seed the pot to cover swag while we work out funding)
- 3 month cooldown after being chosen by community before eligible again

**Comment by pmorie** [comment]
PS this idea shamelessly stolen from [falco](https://falco.org) community

**Comment by csantanapr** [comment]
I saw it from falco I think in Twitter was awarded to @n3wscott 🎉

**Comment by csantanapr** [comment]
I would like to nominate a few knative heros

**Comment by n3wscott** [comment]
it felt good.

**Comment by rhuss** [comment]
👍 , like the idea, too.

**Comment by evankanderson** [comment]
This is awesome, 👍

**Comment by pmorie** [comment]
Any suggestions on mechanics? Once a month? Once a release? WDYT?

**Comment by csantanapr** [comment]
Once a release sounds like a good idea

**Comment by vaikas** [comment]
One additional question that came up while we were discussing was, should we just have one per Knative, given the visibility for some of the folks is not necessarily seen throughout the project (for example, serving/eventing). Do we feel it's enough to have one?

**Comment by csantanapr** [comment]
Maybe start small and expand?

Start with 1 person every 6 weeks. 

As you get feedback and see how things go increase people and and shorten the period. 

Maybe you end up with 3 persons per month.

**Comment by julz** [comment]
> Do we feel it's enough to have one?

How much swag money do you and @pmorie have? ;)

**Comment by pmorie** [comment]
I like:

- Once per release
- Start with one person and see if we need to do more

**Comment by pmorie** [comment]
Should we do one now that the release is out?

**Comment by csantanapr** [comment]
@pmorie  Let me know if you want to do it for this new release 0.21 I can include in the release v0.21 blog post that I’m currently working  on

**Comment by csantanapr** [comment]
Now that I think doing a new and separate blogpost for hero of the moth is better then it can linked from a tweet and Slack. 

In the release notes we can do a mentioned with the link to the post of the hero of the moth post with all the details of the program and the individual contributions listed.

**Comment by vaikas** [comment]
@pmorie @csantanapr let's do it for this release for sure!

**Comment by csantanapr** [comment]
How do we get consensus and move forward ?

lazzy consensus? 😂

**Comment by vaikas** [comment]
I think we just need to figure how to do this. Set up voting? How do we nominate, etc. I figure it's just logistics.

**Comment by csantanapr** [comment]
I think you can start as simple as a private slack DM/email thread between TOC and Steering to pick a person, maybe do this ad hoc for this release v0.21 and then you have 6 weeks to plan a more formal voting among the committees to pick the second hero.

**Comment by vagababov** [comment]
<pedantic-mode> 😁 
If it's per-release, it's not the contributor of the month :)

**Comment by csantanapr** [comment]
That’s true “contributor of the month” has a better marketing ring than “contributor of the release”  the later might indicate the person did something specific for the specific release

maybe 1 person a month to start with to be able to say “contributor of the month” makes more sense

**Comment by csantanapr** [comment]
So let’s pick “contributor of the month” for March 2021.  And the announcement we can say something like For the month of March we want to recognize such person for all her/his contributions to Knative ....

**Comment by pmorie** [comment]
I sent out a message to the -dev and -users list with the ad-hoc way we'll do it looking backward for February

**Comment by csantanapr** [comment]
@pmorie 's saw the message on the mailing list kudos for taking action

**Comment by vaikas** [comment]
Next step:
@pmorie to add to general with voting options

**Comment by vaikas** [comment]
Done, we can tweak the process as we learn more.
/close
