### ISSUE TITLE
PROCESS CHANGE: Adopting lazy consensus

### ISSUE THREAD

**Issue by devguyio** [knative/community#474]
### Background
Transparent decision making and effective communication are key for the success of any FOSS. While the project contributors, approvers and WG leads do their best to ensure we have a healthy and inclusive community, there's still big room for improvement. This is a proposal that came after [a long discussion](https://groups.google.com/g/knative-dev/c/O4gbnJ8pZ5Y) on the Knative Developres Mailing List. 

#### Changes
1. Adopting [lazy consensus](https://community.apache.org/committers/lazyConsensus.html) as a decision-making process.
1. Using Feature Track docs as the source of truth.
1. Using Knative Developers mailing list as the "formal" communication channel for decisions, their technical discussions, and their status updates (approve, reject, etc)
#### Minimum time to revisit : 6 months
Nothing is set in stone, but we think this is the minimum time to try out the proposed changes and give them a fair shot before revisiting them. 

### Benefits
1. Clear expectation of what is the single source of truth of the status. Is it a GitHub issue that links to the FT doc? the FT doc itself? (i.e copy key comments from the GitHub issues into the doc?) else? (Markdown with the FT akin to TEP)? ML?
1. Agreeing on the minimal decisions communication expectations and narrowing them to a single communication channel that is:
   1. Fully asynchronous, ideally a contributor (not necessarily WG leads) wouldn't even need to join any meeting to smoothly propose a FT, follow up its approval/adoption and implement it.
   1. Preserves history.
   1. Have a high SNR. 
   1. Have a high delivery guarantee. Email has a "delivery guarantee", "you've been informed". That's important for adopting "lazy consensus", cause literally every single contributor gets his own copy of proposals/decisions. 
    1. Discoverable/linkable/searchable
      for the intended users "i.e contributors"
1. Enhancing decision making by adopting a time tested, transparent decision-making process used by well established entities like ASF and Kuberenetes itself.
1. Promoting more inclusion for users across different time zones. 
1. Promoting community trust because in lazy consensus a contributor just assumes they have the community’s support unless someone says otherwise.

### Problems
Multiple contributors communicated one or more of the following problems that can be solved by this proposal.
1. Slow or no progress on significant discussions, Feature Tracks and proposals. 
1. Contributors facing difficulties staying involved in the technical discussions and decisions without a huge effort of following up multiple communication channels (slack, meetings, GitHub issues, PRs and sometimes DMs)
1. Contributors giving up on driving features forward due to the vagueness of decision making and long stagnation in reaching a clear conclusion. 
1. Decisions power grip. Sometimes key contributors unintentionally impose a power grip on a proposal or feature by showing disapproval in a meeting or a comment without giving a path for reconciliation or alternative path forward and leaving the proposal author with no choice but chasing them over multiple channels and having the process drag heavily.
1. Key contributors muting slack due to a high SNR and become unavailable for questions by the users. 
1. There's a huge undocumented, unindexed context of what's in-flight and history of decisions that exists in the head of a few key contributors. New project members need to stay involved in all meetings, slack messages, channels and GH issues for months before they feel up to speed within the project and engage productively. 

### Adoption steps
It's understood that changing people and their behavior is hard and takes time. These are the steps needed to start introducing those changes
1. Create a one pager about lazy consensus in Knative and link it to all key repos documents.
1. Create a decision log for each working group which is a one pager list of the Feature Tracks linked to their docs.
1. WG leads should start encouraging that technical discussions take place over the mailing list and refrain from taking decisions in meetings or on slack.

### FAQ
1. Hold on!!! Does that we won't have our lovely WG meetings, slack, or can't explore the new kid in the block aka GitHub  Discussions ? 
  - Nope, it just means we want to change them as secondary, optional communications channels for reaching out for a larger set of users. Also, how can we start our days without @mattmoor infamous "Good Morning" ? or without emoji parties!

2. Hmm, so we'r going to discard GitHub issues then. right?
 - Nope, we want to making them more about tracking work items, small scoped changes and maybe even lead into a larger mailing list thread. 

### More reading
- [This comment ](https://github.com/knative/community/issues/474#issuecomment-781992732)
- To read more about how others are adopting similar processes, check out this [ML message](https://groups.google.com/g/knative-dev/c/O4gbnJ8pZ5Y/m/wORIwScFFgAJ).

**Comment by lionelvillard** [comment]
I really like it! Thanks for putting this together.

In addition to the changes you are proposing, what about:

4. Use GitHub as the single point of entry. One issue per FT, **for indexing and tracking purpose only**. No discussions allowed in the issue, just links to various artifacts, such as ML, design document, Slack channel (if needed), PR, etc..

**Comment by julz** [comment]
I like everything about this other than the mailing list requirement (but it’s possible I just haven’t understood it fully yet).

While it's possible to get searchable and linkable discussions from mailing lists, it's not easy, especially for new contributors. I think it risks turning new contributors off. I think it might have turned me off. Adding more email to my inbox is among the last things I want to do.

Could we adopt the proposal above but allow comments on the GitHub issue as an alternate allowed form of documenting discussions/making decisions?

**Comment by csantanapr** [comment]
I just subscribed to this github issue
![image](https://user-images.githubusercontent.com/1094878/108439892-275f2980-7220-11eb-89ee-53e29c4986cb.png)

Now I get emails, I think this git issue is important to me, I'm going to add it to my "VIP" on my iPhone I will get a notification anytime there is a comment.

I believe folks can reply back to this git issue via email.

**Comment by csantanapr** [comment]
I really fixing my typos on github issues, unlike Twitter where I continue with typo shame 😢

**Comment by csantanapr** [comment]
If you want to see what I edited in my comment you can see it in "edited"
![image](https://user-images.githubusercontent.com/1094878/108440261-c7b54e00-7220-11eb-900a-231e72bf7612.png)

**Comment by csantanapr** [comment]
I agree with this proposal on
1.  less sync technical comments on FT proposals on meetings or slack
2. Lazy consensus is a good thing 
3. Less discussions around a google doc and instead the doc on github so the comments can be done on github 

I think using github or email are good medium, but I think github is better

I have not heard what are the arguments that email list is better to discuss a document FT proposal located in github. 

With github is easier to add a comment to a doc line on a PR, with email how your going to refer to the doc and comment on it?

github it integrates with email, for example if you want to get emails on a pr or issue you can subscribe, if you want to comment you can do reply from email

**Comment by slinkydeveloper** [comment]
> I have not heard what are the arguments that email list is better to discuss a document FT proposal located in github.

The arguments on why mailing lists are better, and the answers to your points in favour to github, are on this thread https://groups.google.com/u/0/g/knative-dev/c/O4gbnJ8pZ5Y

**Comment by julz** [comment]
> The arguments on why mailing lists are better, and the answers to your points in favour to github,

It's maybe relevant to the problems with the searchability of email threads (at least, by those of us like me not adept at using them) that I've spent about 15 minutes now going through that thread trying to identify the bit where this is addressed and I'm not sure I found it. 

As far as I can tell k8s mostly uses GitHub issues to discuss KEPs and certainly doesn't mandate all discussion happen in a ml, which seems like quite a good but of precedent that issues work ok.

**Comment by slinkydeveloper** [comment]
> It's maybe relevant to the problems with the searchability of email threads (at least, by those of us like me not adept at using them) that I've spent about 15 minutes now going back through that thread trying to identify the bit where this is addressed and I'm not sure I found it.

I don't see how this is a problem. Complex discussions takes time and a lot of back and forth, so for me this is absolutely normal. It would be the exact same with github.

> quite a good bit of precedent

Well, internet and the web were built on mailing lists, basically 99% of open source projects we use was built on mail, isn't that a good precedent?

**Comment by julz** [comment]
> I don't see how this is a problem

We'll have to disagree here. I think it's an enormous problem for the goals of this proposal. Reading back through a KEP on a GitHub issue, e.g. https://github.com/kubernetes/enhancements/pull/2176, is a much more pleasant and fruitful experience than trying to divine original intent from a back and forth mailing list thread. This is triply true for new contributors used to the GitHub model for whom even discovering the existence of these discussions at all is likely to be difficult and off-putting.

> Well, internet and the web were built on mailing lists, basically 99% of open source projects we use was built on mail

Sure, but you could say the same about mailing git patches back and forth. We have better tools now that are much more welcoming to newcomers and have some pretty nice features.

**Comment by devguyio** [comment]
@julz @csantanapr Maybe it'll help to differentiate between two things

1. Encouraging the contributors (not the end users, but us members of Knative) towards more async communications and discussions.
    - I thinks that's where most folks have different opinions.
    - I lean towards leaving this for the community to find their sweet spot over a number of "encouraged" async mediums.
    - I believe for knative contibutors those should be: mailing list, pull requests and GitHub issues. 
1. Communicating changes to seek lazy consensus.
    - I see mailing lists as a clear winner here.
    - I think that's the case in kubernetes as well. Check out [contrib-ex SIG chater](https://github.com/kubernetes/community/blob/master/sig-contributor-experience/charter.md#cross-cutting-and-externally-facing-processes) . I think they need to communicate large scope changes/proposals (which means to me anything that requires a FT in our case) on the ML and give 72 hrs room for lazy consensus (that's similar to ASF I believe). 
    - This doesn't mean that discussions can't take place on PRs or GitHub issues, but at the very least the change communication must be announced on the ML to have a valid lazy consensus based decision making.
    - The rule should be before reaching a lazy consensus decision for large scope changes/proposals "was it communicated on the ML" ?

## Why emails, not GitHub issues for communicating large scope changes?

1.  I believe we need to make sure our priorities are set straight and we have the right tool for the purpose. I think we're here talking about a communication channel intended for the "contributors". I.e users who need to awaringly take some initial steps to become "contributors". Things like join slack, the ML (that's mandatory to view any meeting recording, design doc or WG notes). So with that in mind, I think the barrier to entry becomes irrelevant/insignificant? no?
1. With that in mind, I think if we set a "contributor" persona in mind for the "dev" mailing list mailing lists give us the following:
    - Be fully asynchronous. 
    - Retains the history
    - Have a high SNR, and I would like to clarify some thoughts here.
    - The structure of the information is predetermined for all users. (You setup the repos in a predetermined structure). In email, I get to categorize them as I want, filter them as I want, label them as I want, or even ignore what I want.
    - If you use email notifications, you don't get an "opted in by default" because still there're new repos, even new orgs that spawn off all the time "just check knative-sandbox"
    - There's no "collapse read messages in a GitHub issue, nor if a thread is all read, keep it off my sight. With email you can do with email. Instead you have to scroll through all the old comments to see the newest ones at the bottom.
1. In GitHub you need to jump into all different repos and orgs that are "predetermined" for you to get the information you want, while in email, the information comes to you if that makes sense.
1. Have a high delivery guarantee. Email has a "delivery guarantee", "you've been informed". Think of it as your post mailbox where there's a guarantee that you'll receive your ballot as long as you've the correct address and name on the mailbox. That's important for communities adopting "lazy consensus", cause literally every single contributor gets his own copy of proposals/decisions.
1.  Discoverable/searchable
    - for the intended users "i.e contributors", IMHO searching my own inbox is way more efficient than searching GitHub issues. "labels, categories, tons of filtering capabilities"

**Comment by julz** [comment]
@devguyio Im totally fine with something that says "communicate the GitHub issue to the mailing list to ensure folks have time to object as part of lazy consensus". This feels quite different from the original proposal, but I'd personally be entirely on board with "there should be a KEP-style markdown in a GitHub PR, it should be commented on via the PR (a la Kubernetes KEP process), the issue is the source of truth (approvals, etc), it must be communicated to the mailing list when consensus is sought so people know about it" - would that work for you? (If not why)

**Comment by devguyio** [comment]
@julz 
1. When it's time for formulating the process in a markdown, I wanna refrain from presenting the ML as a necessary evil paperwork. Instead, I wanna show that is that for healthy lazy consensus:
    1. Recommended: Start the large scope discussions on ML (possibly with a GH issue).
    2. Required: Communicate the proposal and give required time for lazy consensus.
1. Bottom-line, about the recommendation, I want to experiment with a decision to "encourage" having most of large scope discussions on the mailing list, and reevaluate that in 6 months. 
1. As for the KEP, I stuck to the Feature Track docs and single pager decision log as the source of truth here because it's a smaller change (we already use FTs) compared to adopting a new thing like KNEP (which was an option in the mailing list thread) . Switching for FC to a markdown KEP style file is orthogonal to this discussion IMHO.

**Comment by julz** [comment]
FWIW I think it's worth saying these lines may be a key reason we don't see this the same way.

> [..] So with that in mind, I think the barrier to entry becomes irrelevant/insignificant? no?

> for the intended users "i.e contributors", IMHO searching my own inbox is way more efficient than searching GitHub issues. "labels, categories, tons of filtering capabilities"

I don't see contributors as a fixed, closed community. New contributors may come wishing to propose or participate in only a couple specific issues or areas that are important to them. They will not have a pre-filtered, nicely tagged inbox, they will have the google groups UI 😬. Even those who _do_ become core contributors will be confronted with that UI when trying to get context on past decisions. Many or most will be familiar with contributing via GitHub issues, searching, and following them and will be unlikely to discover a mailing list. Having a hard to search, uncategorised back-channel of past communication on the ML that isn't reflected on an issue will make it difficult for new contributors to gain confidence and context. As a say, I rather suspect it would have put me off joining, or made it much more difficult for me to gain confidence and context on the project.

AFAIK you are also entirely free to subscribe to a repo via email, if you wish to do your own filtering, at which point you have every advantage your email client can offer. The reverse is not true of those who would rather _not_ open their email client more than twice a day (🙋🏼).

**Comment by julz** [comment]
> Bottom-line, about the recommendation, I want to experiment with a decision to "encourage" having most of large scope discussions on the mailing list, and reevaluate that in 6 months.

Instead of making three large changes at once as a single experiment, could we not start the experiment with just the core change here - the one in the title of the issue :) - lazy consensus, without bundling in an attempt to fairly dramatically change the workflow of some contributors (I open email twice a day...).

What Would Be Bad If the proposal was "lazy consensus, feature docs + corresponding issue as source of truth, announce in slack/mailing list for reach, make sure to reflect any important non-issue discussion back on to the issue"? AFAICT all the advantages claimed for emails above are available to you by just subscribing to the relevant repos where the issues would be and adding whatever filtering you like. The reverse is not true.

> As for the KEP, I stuck to the Feature Track docs and single pager decision log as the source of truth here because it's a smaller change (we already use FTs) compared to adopting a new thing like KNEP

Moving to KNEP as PR-ed markdown with GitHub Issue for comments rather than feature docs seems like a much smaller change than moving communication to mailing lists, so if we only have bandwidth for a certain amount of experimentation at once, I'd vote we spend that bandwidth towards something roughly similar to Kubernetes here and do KNEPs via GitHub, with mailing list + slack notification for reach and lazy consensus.

**Comment by devguyio** [comment]
I'm game for you to add to the description "Proposal 2" . But can we agree on for proposal 2 to be "announce on slack AND mailing list" ?. 
> without bundling in an attempt to fairly dramatically change the workflow of some contributors (I open email twice a day...).
I'm sorry if this came off as a way to dramatically disturb your workflow (or other folks with similar workflows).

 Honestly I was hoping it'll only shift the discussion to the middle, where MLs and GitHub issues are BOTH live, some groups prefer one, others prefer the other. Simply because I believe with "encouraging" best case scenario we'd reach the middle point, not tip it over totally towards mailing lists. I'm personally willing to take the extra toll of keeping up with both to have folks not feel that their 99% of mailing list threads are abandoned by the key contributors nor that their GitHub issues are deserted. (hence it'd have been totally fine if a big beefy GH issue ends up getting approved with a single mailing list email. 

> AFAICT all the advantages claimed for emails above are available to you by just subscribing to the relevant repos where the issues would be and adding whatever filtering you like. The reverse is not true.
I'd say mostly yes with a single precondition, if we all agree on a single source for those large scope discussions (at least single one per WG) which is not the current case for any of the eventing WGs. We add a new repo every couple of weeks or so and with that the SNR decreases dramatically specially with issues having both trivial issues, bugs, small and large scope changes. But if you want to take out "large scope changes" in a separate repos "KNEP" repo, then they'd be more or less the same.

**Comment by julz** [comment]
> I'm game for you to add to this issue a "Proposal 2" . But can we agree for proposal 2 to have "announce on slack AND mailing list" ?.

Thanks @devguyio, I took a crack at it in https://github.com/knative/community/issues/478. Hopefully it reflects your concerns above.

> I'm sorry if this came off as a way to dramatically disturb your workflow (or other folks with similar workflows).

No, I understand, I'd like to find a way that achieves as many of the entirely valid goals in this issue as possible. Ideally we can minimise disruption for those of us who prefer a GitHub-based life while also giving folks who actually like their email client a way to use it. We can all agree that decision making split across 5 mediums with no lasting context is something with plenty of room to improve.

> I'd say mostly yes with a single precondition, if we all agree on a single source for those large scope discussions (at least single one per WG) which is not the current case for any of the eventing WGs

👍 makes sense, I added that to the proposal in https://github.com/knative/community/issues/478.

**Comment by csantanapr** [comment]
I would like to clarify a few things I love lazy consensus I have worked in ASF projects for years where we practice lazy consensus 

One example is Apache Cordova when I used to be very active on the project we were one of the first projects to move to github and slack, but followed lazy consensus 

A new feature was proposed on a github repo and most comments were made on github on the doc

When it came down for the person proposing after adjusting the proposal based on feedback, then it was time to “APPROVE” the proposal to move forward on implementing into the project at this time we need consensus a vote is started. 

The person proposing would start an email thread [VOTE] approve proposal x the voting will remain open for 72 hours if there are negative votes the proposal is approve and we move forward

So I’m in favor of using the mailing list for lazy consensus where 2 email threads about a proposal are open, the [ANNOUNCE] and the [VOTE] and that would be recorded as te officials start and end of a proposal

As the 100 comments/feedback on the proposal I think we should encourage Github

On other aspects:
Now that we move to a new Google Drive, we can make all documents and recordings public accesible to read no need to join any mailing list. I tried this on some documents yesterday and it allowed me to create links with permission to allow anyone. 

With this said Google docs is good to do meetings notes interactive and store files like presentations and videos. But discussions should be moved to Github when discussing a change/addition in the software 

I keep hearing mailing list keeps history, well Github also keeps history too. That github allows you to edit a typo or a comment that’s a good thing, that github allows you to delete a comment well that’s good also. 


Sending this from my iPhone email client :-)


- Carlos Santana
@csantanapr

**Comment by csantanapr** [comment]
On the point on that as new github repo get created people are not opt in automatically 

in Apache Cordova and Apache OpenWhisk we had two many repos and had this problem about consuming github activity from email clients two problems

1. People that wanted to be aware of everything that happens on github ( people could choose to get one email per activity or get a digest email once a day or once a week)
2. People that do not wanted to get emails about everything on github just the most important decisions or announce te about the project development. 

To solve this I created different mailing lists 
dev@ this is the main dev ML, announcements, votes, introductions, etc
issues@ all issues across all repos
prs@ all prs across all repos 

All mailing lists supports digests in case you don’t want that many email. 

Also I use an email client good for this type of notifications like gmail that is smart organizing threads, threads and filter and move into folders

**Comment by rhuss** [comment]
fwiw, catching up substantial discussion like *this* is much more enjoyable for me (but still work) in a GitHub issue, because:

* Linear navigation by just scrolling down
* Easy in-page search supported by your browser
* No quoting by default  for new comments
* No top-postings
* Limited and uniform formatting
* A single thread
* Chronological order

I'm fine with having email pointers to GitHub issues carrying discussions, but working with emails (searching, context extraction, reading) is worse than with GitHub issues.

**Comment by evankanderson** [comment]
It would be good to track how often we need to "back out" Lazy Consenus and/or times that this people were upset by a change that they missed.

**Comment by devguyio** [comment]
Closing this for #579
