### ISSUE TITLE
PROCESS CHANGE: Every file on Knative.team Google Drive to be public viewer with link

### ISSUE THREAD

**Issue by csantanapr** [knative/community#481]
Is my understanding that since they moved from google owned Google Drive, to Knative.team Google Drive 
now is possible to share a file with a link and change the permissions that anyone with the link is able to view/read-only the file

My proposal is that every file by default created on Google drive that the document creator makes file shareable by clicking share, Get link, and change permissions that anyone with the link can be a viewer (not commenter, or editor)

Today we state that WG Meeting Minutes are public viewable, but I notice some minutes notes did not changed the link to viewer.

I keep seeing links to google files linked in github repos but the links are only valid to folks that belong to the Google Knative Project via the mailing list

* Expected benefits. Who gains the benefits? Why will they benefit?
Better experience when folks see a link in github or slack click on it and can easily access the link without being block.

* Expected costs. Who bears the costs? How heavy are they?
No cost

* Timeframe for implementation / rollout.
Today

* Are you willing to drive the process, or is this a request for help?
Yes

![image](https://user-images.githubusercontent.com/1094878/108554744-883f3e00-72c2-11eb-826e-9caa365ed725.png)

![image](https://user-images.githubusercontent.com/1094878/108555271-45319a80-72c3-11eb-96e9-f5fdd165b8ac.png)

**Comment by rhuss** [comment]
👍 

I support this idea, as I already had the situation where I wanted to share e.g. a Feature Track or Proposal document to someone who is not in the knative-dev google group. Asking to join the google group only for having access to the document felt like overkill (and also probably prevented for some engagement to happen).

**Comment by vaikas** [comment]
Ok, selected an option that I think should fix this. The option that seemed to fit was:
ON - Primary target audience with the link.

Let me know if that solves it, @csantanapr @rhuss

**Comment by evankanderson** [comment]
@csantanapr 

If you want to write a tool to automate this, the code that Nghia wrote for copying all the gdocs is here:

https://github.com/knative/community/tree/main/mechanics/tools/gdocs-migrate

**Comment by rhuss** [comment]
/lgtm 

Thanks a lot @vaikas (tested it with some docs, the only thing that was a bit strange is that the Client WG Notes were open for editing by everyone with the link, a bit too wide open. Restricted it to view-only for the public, with edit for knative-dev members)

**Comment by vaikas** [comment]
Thanks for the test @rhuss 

Hm, wonder if there's something else in the settings that need to be tweaked.

**Comment by rhuss** [comment]
I think this was just a peculiarity on this particular document. The configuration looks good to me: you can make the docs publicly readable but still allow special groups to edit it.

**Comment by vaikas** [comment]
ah, ok :) Thanks!!!

**Comment by vaikas** [comment]
/close

Reopen if things don't work as expected.
