### ISSUE TITLE
Knative Hoodie Distribution Signup - Spring 2021

### ISSUE THREAD

**Issue by n3wscott** [knative/community#487]
Howdy folks! If you are interested in getting a custom ducktagon hoodie, please act fast, the following people assigned are qualified to request a hoodie, please respond by *Feb 26 2021* for us to get the order together.

The bar to be included in this list is be in an owners file in a Knative project. Even as a reviewer! We are rewarding folks that step up and are volunteering for code reviews or owning code.

@Cynocracy
@Fredy-Z
@JRBANCEL
@ZhiminXiang
@aavarghese
@adrcunha
@ahevenor
@albertomilan
@andrew-su
@averikitsch
@beemarie
@benjamintf1
@carieshmarie
@cdeppisch
@cdlliuy 
@coryrc
@csantanapr
@daisy-ycguo
@davidor
@davyodom
@devguyio
@dtimm
@dushyanthsc
@efiturri
@houshengbo
@imjasonh
@jcrossley3
@jmprusi
@jonatasbaldin
@josephburnett
@julz
@macruzbar
@mbehrendt
@mdemirhan
@mpetason
@nbarthwal
@nicolaferraro
@nlopezgi
@omerbensaadon
@phamilton
@pianohacker
@richieescarez
@sixolet
@srinivashegde86
@steven0711dong
@syedriko
@tcnghia
@thisisnotapril
@tommyreddad
@travis-minke-sap
@trshafer
@tzununbekov
@wfernandes
@whaught
@yanweiguo
@yt3liu
@yu2003w
@yuvalif
@zhanggbj
@zhangtbj
@zhongduo
@dsimansk
@christophd

If you are on this list, please fill out:

https://docs.google.com/forms/d/e/1FAIpQLSebg5du4_65J9YCEIYU4KWWYZeHR5wOg1gEnKp5TK-X6iP5Qw/viewform?usp=sf_link

This is an honor system, please don't submit if you are not on the list or have not talked to me personally. I am required to filter based on who has not received a hoodie in the past and who meets the in an OWNERS file bar. Thank you so much!!

**Comment by n3wscott** [comment]
Ping  @Cynocracy @Fredy-Z @JRBANCEL @ZhiminXiang @aavarghese @adrcunha @ahevenor @albertomilan @andrew-su @averikitsch @beemarie @benjamintf1 @carieshmarie @cdeppisch @cdlliuy  @coryrc @csantanapr @daisy-ycguo @davidor @davyodom @devguyio @dtimm @dushyanthsc @efiturri @houshengbo @imjasonh @jcrossley3 @jmprusi @jonatasbaldin @josephburnett @julz @macruzbar @mbehrendt @mdemirhan @mpetason @nbarthwal @nicolaferraro @nlopezgi @omerbensaadon @phamilton @pianohacker @richieescarez @sixolet @srinivashegde86 @steven0711dong @syedriko @tcnghia @thisisnotapril @tommyreddad @travis-minke-sap @trshafer @tzununbekov @wfernandes @whaught @yanweiguo @yt3liu @yu2003w @yuvalif @zhanggbj @zhangtbj @zhongduo

**Comment by n3wscott** [comment]
This is an honor system, please don't submit if you are not on the list or have not talked to me personally. I am required to filter based on who has not received a hoodie in the past and who meets the `in an OWNERS file` bar. Thank you so much!!

**Comment by n3wscott** [comment]
Odd rendering bug or there is a limit (retry trying the un-highlighted folks)

@trshafer @tzununbekov @wfernandes @whaught @yanweiguo @yt3liu @yu2003w @yuvalif @zhanggbj @zhangtbj @zhongduo

**Comment by zhongduo** [comment]
You are a hero! Thanks @n3wscott !

**Comment by n3wscott** [comment]
> You are a hero! Thanks @n3wscott !

😊 _na_, I am just lucky enough to be able to thank those that have stepped up to help the project! So, thank YOU!! Let's get this thing to 1.0!! 🎉 🎉 🎉 🎉

**Comment by n3wscott** [comment]
Adding @dsimansk and @christophd

cc @rhuss

**Comment by n3wscott** [comment]
/close

OK, looks like new signups have stopped over the last couple days and we are at the end date. I am going to get this batch to the makers.

Until next time!
