### ISSUE TITLE
PROCESS CHANGE: All working groups should have a visible link to their roadmap

### ISSUE THREAD

**Issue by csantanapr** [knative/community#490]
Background:
While starting to a new UX WG roadmap document like stated in the process document https://github.com/knative/community/blob/master/mechanics/WORKING-GROUP-PROCESSES.md#setting-up-a-working-group

> Create a Roadmap Document. Create a document in the above folder and call it "GROUP_NAME Group Roadmap". Put your initial roadmap in the document.

I noticed that would be very convenient to document for every working group where is their respective roadmap "document"

For UX WG we are going to a Github Project board [UX WG Roadmap](https://github.com/orgs/knative/projects/20) for this I wanted to add a link to the table for our WG https://github.com/knative/community/blob/master/working-groups/WORKING-GROUPS.md#user-experience

Regardless if the Roadmap is a Google Doc/Slide or Github Project, anyone with the link should be able to access it, there is no need to join the mailing list now to view any of the google docs, every google doc link can be configured to be share as "viewer" with anyone with the link Rel: https://github.com/knative/community/issues/481

* Expected benefits. Who gains the benefits? Why will they benefit?
I think community members will benefit to have a link to the roadmap alongside all the other links related to a working group

* Expected costs. Who bears the costs? How heavy are they?
$0

* Timeframe for implementation / rollout.
1 week for all WGs

* Are you willing to drive the process, or is this a request for help?
Yes 🙄

**Comment by csantanapr** [comment]
cc @omerbensaadon

**Comment by evankanderson** [comment]
+1 from most of the TOC.

Evan has a suspicion that there may be WGs that don't have a separate roadmap document at this point.

**Comment by evankanderson** [comment]
Any updates?

Do we want to put these in a central location, like `working-groups/$WGNAME/roadmap.md`?

**Comment by evankanderson** [comment]
/assign @omerbensaadon 

Omer is interested in this, too. He's working with a few other contributors.

**Comment by evankanderson** [comment]
I think resolved by #746

**Comment by csantanapr** [comment]
This is resolved now with final PR https://github.com/knative/community/pull/859
/close
