### ISSUE TITLE
New Repo: specs

### ISSUE THREAD

**Issue by tayarani** [knative/community#499]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

Org: knative

Repo: specs

Purpose (Description): This repo will act as the unified repo which will contain all the specs and conformance tests. Details of the proposal: https://docs.google.com/document/d/1TGtzYZjukEm1657XEQgTF-FUwoLGrVmLErRcCYaeLjw/edit#heading=h.uajvrznq814p

Sponsoring WG: Conformance WG (on behalf of the KTC)

## Actions to fulfill

This area is used to track the [repo creation process](/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review. You are responsible for moving your entry on the board to "Needs Discussion" or "In Progress" as you move forward in this checklist.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [x] Send a PR adding entries for this repo in [`/peribolos/knative-sandbox.yaml`](https://github.com/knative/community/blob/master/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  - [x] Grant the sponsoring WG the `write` privilege.

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [x] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [x] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo main
  ```

- [x] Add your GitHub ID to the `OWNERS` file for your repo.

- [x] [Set up](https://github.com/knative/test-infra/blob/master/guides/prow_knative_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge) prow for a new repo

- [ ] Bootstrap your CI jobs using [hack](https://github.com/knative/hack) project (look at other sandbox repos for reference)

- [x] Create a sample PR to verify Prow (e.g., edit the boilerplate README)

- [x] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

- [ ] (optional) Send a PR adding the repo to [knobots](https://github.com/knative-sandbox/knobots).

**Comment by n3wscott** [comment]
it is a bit of overhead now to have the docs samples outside of the repo that implement the sampled feature. I worry it will be the same problem with this. And then does the spec repo have code or tests? if it does you end up in a fun versioning dep issue as it becomes a star point.

What is the downside of having the specs next to the code that implements the spec?

**Comment by tayarani** [comment]
The objective @n3wscott is to separate the specs from the reference implementation. The repo structure is proposed [here](https://docs.google.com/document/d/1TGtzYZjukEm1657XEQgTF-FUwoLGrVmLErRcCYaeLjw/edit#).

**Comment by n3wscott** [comment]
I understand the objective. I question the value of separation.

**Comment by duglin** [comment]
At its core "knative" is a set of spec. The code is just a reference implementation of those specs. We need a clean separation so that there will be no confusion as to which bits of data (spec, code, tests, ...) are acting as statement related to the specs (and conformance) and which are related to the choices of the ref impl.

**Comment by n3wscott** [comment]
It will be very messy to add conformance impl to a single repo for all of Knative, you will have to be very careful about imports and how the modules work if that is the plan.

**Comment by tayarani** [comment]
I'm having trouble with this step "Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
appropriate "template" repository". Everything I've tried results in:

```ERROR: Permission to knative/specs.git denied to tayarani.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Can someone grant me permissions? 
cc @vaikas @grantr

**Comment by tayarani** [comment]
I'm trying to use the sample-source template.

**Comment by tayarani** [comment]
Was blocked on permissions due to https://github.com/knative/community/issues/520 which has now been resolved

**Comment by vaikas** [comment]
@tayarani Is there anything left here? Seems like this can be closed?
