### ISSUE TITLE
Peribolos seems to have silently failed to update a team

### ISSUE THREAD

**Issue by grantr** [knative/community#520]
#518 added @tayarani to the Conformance WG Leads team in peribolos, but in reality that team has no members. Is peribolos failing to update the teams configuration?

**Comment by grantr** [comment]
Optimistically assigning to @evankanderson :D

**Comment by rhuss** [comment]
@evankanderson looks like that we can close the issue with the fix #521 resolving it ? Feel reopen it, if I'm wrong.

**Comment by tayarani** [comment]
Yes this did fix the issue I was experiencing.
