### ISSUE TITLE
New Repo: client-pkg (in org "knative")

### ISSUE THREAD

**Issue by rhuss** [knative/community#523]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

Org: knative

Repo: client-pkg

Purpose (Description):  Repository for holding shared client code, like between `kn` and its plugins

This repo will also hold the reusable CLI API which can be leveraged by other projects for simplified access to Knative (adding also some enhancements like 'wait to be ready' and also some knative specific logic)

Sponsoring WG: Client WG

## Actions to fulfill

This area is used to track the [repo creation process](/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [ ] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review. You are responsible for moving your entry on the board to "Needs Discussion" or "In Progress" as you move forward in this checklist.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [X] Send a PR adding entries for this repo in [`/peribolos/knative.yaml`](https://github.com/knative/community/blob/master/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
  - [X] Add the repository and a description.
  - [X] Grant `Knative Admin` the `admin` privilege.
  - [X] Grant the sponsoring WG the `write` privilege.

--> https://github.com/knative/community/pull/522

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [ ] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [ ] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo main
  ```

- [ ] Add your GitHub ID to the `OWNERS` file for your repo.

- [ ] [Set up](https://github.com/knative/test-infra/blob/master/guides/prow_knative_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge) prow for a new repo

- [ ] Bootstrap your CI jobs using [hack](https://github.com/knative/hack) project (look at other sandbox repos for reference)

- [ ] Create a sample PR to verify Prow (e.g., edit the boilerplate README)

- [ ] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

- [ ] (optional) Send a PR adding the repo to [knobots](https://github.com/knative-sandbox/knobots).

**Comment by rhuss** [comment]
An altnerative option would be to add a 'client' subdirectory to the `knative/pkg` repository, but this would increase the dependency surface for `knative/pkg` considerably (e.g. adding client-specific libraries like cobra etc)

**Comment by evankanderson** [comment]
Having a `pkg` or `infra` subdirectory in `client` doesn't work because it sometimes introduces circular dependencies if `kn` wants to include certain plugins as part of the baseline.

**Comment by evankanderson** [comment]
Markus thinks we should start in `pkg`, since `go mod` won't pick up transitive dependencies on e.g. `cobra` if the `client`  module isn't used by some other import.

**Comment by evankanderson** [comment]
Scott wonders about submodules in `go`...

**Comment by evankanderson** [comment]
Markus/Grant suggest using `pkg` for now and seeing how it feels...

**Comment by rhuss** [comment]
@knative/technical-oversight-committee one thing that I oversaw and forgot to mention in the call: In order to allow plugins to reuse the client API (e.g. the part that does a sync call), we want to add this to this shared code, too. But these APIs also need serving and eventing clients, so we will add a dependency from pkg -> serving and pkg -> eventing, which will lead to a cycle.

I don't think this is desirable. Thinking again, we are probably not talking about `client-pkg` but more like `client-api` which also contains tooling code (e.g. how to uniformly parse options). 

So let me go back to the drawing board and check again if we can not keep the code in the client repo itself, resolving our circular issue differently.

**Comment by rhuss** [comment]
cc @maximilien ^^

**Comment by evankanderson** [comment]
@markusthoemmes

**Comment by rhuss** [comment]
I think we can close this for now as we haven't made much progress yet, but want to try to use either a submodule in the `knativel/client` or really leverage the standard golang semantics which putting internal stuff all into `internal` (as described in https://github.com/golang-standards/project-layout) and the public part to `pkg`. 

In order to reduce noise here, let me close this issue and only reopen if we really think that an own `knative/client-pkg` would be the best solution.
