### ISSUE TITLE
New Repo: homebrew-kn-plugins

### ISSUE THREAD

**Issue by maximilien** [knative/community#527]
Use this issue type to request a new repo in `knative-sandbox` (or
`knative`, which may require additional discussion).

## Repo information

Org: knative-sandbox

Repo: homebrew-kn-plugins

Purpose (Description):

Collect homebrew formulas for the different `kn` plugins. This makes it easy for end users to install plugins and update them.

Sponsoring WG: client

## Actions to fulfill

This area is used to track the [repo creation process](/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review. You are responsible for moving your entry on the board to "Needs Discussion" or "In Progress" as you move forward in this checklist.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [X] Send a PR adding entries for this repo in [`/peribolos/knative-sandbox.yaml`](https://github.com/knative/community/blob/main/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
  - [X] Add the repository and a description.
  - [X] Grant `Knative Admin` the `admin` privilege.
  - [X] Grant the sponsoring WG the `write` privilege.

--> https://github.com/knative/community/pull/528

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [ ] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [ ] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo main
  ```

- [ ] Add your GitHub ID to the `OWNERS` file for your repo.

- [ ] [Set up](https://github.com/knative/test-infra/blob/main/guides/prow_knative_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge) prow for a new repo

- [ ] Bootstrap your CI jobs using [hack](https://github.com/knative/hack) project (look at other sandbox repos for reference)

- [ ] Create a sample PR to verify Prow (e.g., edit the boilerplate README)

- [ ] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

- [ ] (optional) Send a PR adding the repo to [knobots](https://github.com/knative-sandbox/knobots).

**Comment by evankanderson** [comment]
+1 from Grant
+1 from Evan
+1 from Roland
+1 from Markus

**Comment by maximilien** [comment]
Thanks all 🍻

**Comment by maximilien** [comment]
OK so shall I expect a comment here when the repo is created to continue to next steps? Thanks.

**Comment by rhuss** [comment]
Yep, I will ping you when we can push the initial code. If everything works correctly, you should be able to do this initialisation step on your own (because we don't have any branch protection enabled yet).

**Comment by rhuss** [comment]
@maximilien https://github.com/knative/community/pull/528 has been merged and you can push now your work directly to the new repository`knative-sandbox/homebrew-kn-plugins`. Let me know when you are done because then I will setup prow (no ci jobs yet, but enabling tide) and enable branch protection on that repo.

**Comment by maximilien** [comment]
Thanks @rhuss I’ll get to it this week. Thanks for the quick turn around. Cheers all 🍻

**Comment by markusthoemmes** [comment]
Tide seems setup fine and this repo won't have any golang code etc. I think we're done here?
