### ISSUE TITLE
PROCESS CHANGE: Create a Read-Only #mailing-list Channel

### ISSUE THREAD

**Issue by omerbensaadon** [knative/community#550]
### Expected benefits. Who gains the benefits? Why will they benefit?
There has been a lot of talk about lazy consensus recently, and we keep coming back to the mailing list being a place to solicit this sort of consensus + feedback.  

Most of us contributors live and work in Slack as do many of the folks in our Slack community. If we simply copy over all newly created Mailing List posts into a read-only Slack channel, folks will not have to check their email to see the posts and can easily navigate through links to previous posts. 

Making the channel read-only prohibits people from having the conversations in Slack threads which keeps the source-of-truth to one singular location. 
### Expected costs. Who bears the costs? How heavy are they?
very low, just make a channel and create a simple bot (then allow it to post to that channel).

### Timeframe for implementation / rollout.
As soon as it's approved. 

### Are you willing to drive the process, or is this a request for help?
Yes, I am willing to drive the process

**Comment by evankanderson** [comment]
This notification that mailing list posts happen, but just for awareness.

Approve

**Comment by julz** [comment]
I guess my only hesitation here, personally, is this seems like its going to end up with a lot of the same problems as a mailing list (lot of content that may not be relevant which is hard to sort through for the actually important stuff, poor threading etc) except with even _less_ ability to filter effectively. Still it obviously wouldnt hurt (I personally probably wouldnt open the channel much) so I dont have any big objection, just I think personally it might be better to only mirror stuff with a [lazy consensus request] in the subject line or something. That can easily be a different/follow-on proposal though which I can open separately and steal whatever bot you build for this ;)

**Comment by omerbensaadon** [comment]
Maybe the bot can just echo "[PROPOSAL]" Subject lines? And we can standardize around that for achieving consensus?

**Comment by omerbensaadon** [comment]
We can implement this as-is and check back on it in ~ 1 month? 

The important thing here is we have to standardize on proposals going to the Mailing List.

CC: @evankanderson @grantr

**Comment by evankanderson** [comment]
Given that this is a new slack channel, I think whomever is driving the change gets to define the initial filter on messages. If we discover we need a different filter, we can work that out subsequently.

I know that @pmorie and @vaikas are driving a document around lazy consensus that will spell out in some more detail how to announce a lazy consensus decision point, which might help.

**Comment by omerbensaadon** [comment]
Done! Ended up not being Read-Only since we don't have the Slack plan for that

**Comment by julz** [comment]
just wanted to say: I was wrong about this! having the channel only post top-level topics and not replies solved the problem I was worried about and this has so far been v useful without being distracting at all. Nice work @omerbensaadon!
