### ISSUE TITLE
PROCESS CHANGE: Lazy consensus as a community value [The P&V Edition]

### ISSUE THREAD

**Issue by devguyio** [knative/community#579]
### Overview

In order to improve the efficiency and transparency of decision making in Knative Community, two proposals for adopting lazy consensus were introduced : #474 , #478 . However, the community couldn't align on the communication channel aspect of either of the proposals. 

In order to move forward with lazy consensus, @pmorie and @vaikas introduced the proposal in this issue which proposes a resolution and avoid some of the entanglements that have prevented this topic from being driven to a resolution in previous proposals.

### Proposal

You can read the proposal here - [link](https://docs.google.com/document/d/1l7pWR2qyEgmCu1zbYwiufQH6aSM9DnwlJ1xtjuxz4MA/edit#)

### Adoption steps
It's understood that changing people and their behavior is hard and takes time. These are the steps needed to start introducing those changes
1. Create a one pager about lazy consensus in Knative and link it to all key repos README.
1. Schedule a call for "introducing lazy consensus" for the community members, with WG leads and approvers as primary invitees.
1. WG leads: Announce the adoption of lazy consensus in a WG meeting.

**Comment by vaikas** [comment]
/close
@devguyio if you think there's still something remaining, please reopen.
