### ISSUE TITLE
Suggestion: Knative Ambassadors

### ISSUE THREAD

**Issue by julz** [knative/community#588]
We currently recognise those who contribute in terms of code (e.g. via Approver and Lead roles), and in terms of note-taking (Scribe Role) and execution leadership (Execution Lead Role). We do not, however, currently recognise those who evangelise and advocate for the project. Other communities have specific roles (Docker Captain, Kubernetes Ambassador, Cloud Foundry Ambassador) to recognise those who evangelise and spread the word about them; the people who write blog posts, answer support requests, create videos etc to help users be successful with Knative. We should, too.

Example: https://www.cncf.io/people/ambassadors/

## Expected benefits. Who gains the benefits? Why will they benefit?

- Recognition for those who advocate for and evangelise Knative, and help our users understand and be successful with the project
- Hopefully, by recognising and rewarding the above, more of the above!
- Enablement of the above, by giving Ambassadors resources, maintaining list of ambassadors, pool of potential speakers for conferences etc

## Expected costs. Who bears the costs? How heavy are they?

- Some overhead for steering in running the program, defining criteria, swag etc, helping and enabling ambassadors
- We would want to set up some defined benefits (custom hoodies?) and responsibilities, which will need someone to do, and funding for
- Nomination criteria, probably based on precedent from other communities (see eg https://www.cncf.io/people/ambassadors/)

## Are you willing to drive the process, or is this a request for help?

If Steering wants to do it, Id happily draft a first version of the program and do any work like that, but there may well be better qualified people in the community who would be a better fit for actually running this

Edit: meant to say, we could also (credit @csantanapr) and/or expand the existing contributor of the month to have an advocate of the month etc

**Comment by csantanapr** [comment]
Here are other examples

- CD Foundation https://cd.foundation/cdf-community-awards/ (Ambassador, Evangelist, Advocate, End User)
- Linkerd https://linkerd.io/2021/04/21/vote-for-your-april-hero/ (Hero)

**Comment by csantanapr** [comment]
Ambassador should not be a monthly or yearly award.

CNCF has an Ambassador program and people can apply
https://www.cncf.io/people/ambassadors/


I think the "Knative Ambassador" should follow a similar recognition and criteria as CNCF

**Comment by vaikas** [comment]
@julz would you mind taking a crack as you offered? Steering is +1 on this.

**Comment by julz** [comment]
\o/ - okiedoke, added to my todo list

**Comment by julz** [comment]
this is struggling to get near the top of my todo list at the moment, @csantanapr if you're interested please take it :)

**Comment by csantanapr** [comment]
@pmbanugo is interested on joining as an ambassador for knative 🎉

**Comment by csantanapr** [comment]
The next step is for me to write a google doc proposal on how the program going to work for steering to review and approve.

I'm thinking the ambassador program should be bootstrapped with a few members already selected and not empty, folks that already do the work today folks like @salaboy and @pmbanugo that writing a knative books, doing presentations or blogs already about knative.

**Comment by csantanapr** [comment]
We will also need admins for the program, I'm thinking folks like @xtreme-sameer-vohra would be great for administrating the program. admin means a lot of fun things to grow the community :-)

**Comment by salaboy** [comment]
I am all up for this, count me in

**Comment by lance** [comment]
Closing until we have more community leadership/representation
