### ISSUE TITLE
Clarify criteria for TOC membership

### ISSUE THREAD

**Issue by pmorie** [knative/community#59]
This issue is a takeaway from a steering F2F; issue is to clarify what the criteria / rules etc around TOC membership are.

**Comment by bsnchan** [comment]
TOC criteria and election proposal here: https://docs.google.com/document/d/1Dfs7CwjdRalT10tMaDtS_VcubCrXpI-8HggbjcWaPv0/edit

We'll leave it open for community feedback until March 20th.

**Comment by bsnchan** [comment]
We are planning to leave this open until **March 27th** due to folks operating under limited bandwidth at the moment.

**Comment by mattmoor** [comment]
I'd say we can mark this as done now, right? 🎉

**Comment by bsnchan** [comment]
https://github.com/knative/community/blob/master/mechanics/TOC.md
