### ISSUE TITLE
Proposal to remove knative-sandbox/eventing-natss repo

### ISSUE THREAD

**Issue by vaikas** [knative/community#593]
After many attempts to gather usage stats as well as recruit maintainers, this repo:
https://github.com/knative-sandbox/eventing-natss

should be removed. This was brought up again in the TOC meeting at 2021-04-29 and consensus seemed to be to remove it. But following the processes here, just creating the ticket to make sure that it's all good. 

**I'd like to not release .23 of the repo since there are no changes there and adds unnecessary overhead.**

Though this is not a core repo and onus is on the WG but criteria is certainly met:
https://github.com/knative/community/blob/main/REPOSITORY-GUIDELINES.md#grounds-for-removal

As per:
https://github.com/knative/community/blob/main/REPOSITORY-GUIDELINES.md#deletion

And:
https://github.com/knative/community/blob/main/REPOSITORY-GUIDELINES.md#procedure-for-removal

**Comment by vaikas** [comment]
@evankanderson @markusthoemmes @grantr @rhuss 
In case there are questions/comments/concerns.

**Comment by vaikas** [comment]
Also as per discussion in the TOC meeting:
https://github.com/knative/community/pull/594
@abrennan89

**Comment by evankanderson** [comment]
Not sure if https://github.com/knative/community/blob/main/mechanics/SUNSETTING-FEATURES.md is of help here as well.

**Comment by zhaojizhuang** [comment]
Hi @vaikas ,we are now using `eventing-natss`,add add feature `natss source` Based on this repository https://github.com/openhonor/eventing-natss

**Comment by vaikas** [comment]
@zhaojizhuang Thanks for letting us know!!!

**Comment by vaikas** [comment]
/close
@zhaojizhuang has stepped up to maintain this.
