### ISSUE TITLE
Organize recurring community demo sessions

### ISSUE THREAD

**Issue by isdal** [knative/community#60]
During the Steering Committee AMA on Jan 13th it was suggested that we create a space for users of Knative to show how they are using the project.

We are looking for a volunteer to organize this. Responsibilities include:
 - Solicit demos from the community
 - Set up meetings, publish recordings
 - Review and merge demo's into a shared demo repository

**Comment by vaikas** [comment]
Do we feel like this has been sufficiently addressed by our Knative Community Meetups?

**Comment by bsnchan** [comment]
I think this is now an outdated issue. Closing.
