### ISSUE TITLE
New Repo: kn-plugin-quickstart

### ISSUE THREAD

**Issue by rhuss** [knative/community#603]
## Repo information

Org: knative-sandbox

Repo: kn-plugin-quickstart

The name is under discussion and not written in stone yet.
It's important as the name is reflected in the usage of this plugin.

Purpose (Description):

Provide a plugin for `kn` to allow the installation of a Knative cluster for initial exploration and/or developer purposes.
It is not supposed to be a general-purpose installation command for arbitrary Kubernetes cluster, but with a very clear and limited scope on running Knative on the desktop via e.g. `kind` or Kubernetes on Docker Desktop.

Therefor the name should not be `kn-plugin-install` to avoid any wrong expectations. Alternatively to `quickstart` it could be also `kn-plugin-kind` or `kn-plugin-docker` reflecting the underlying technology used for setting up the cluster. Other ideas are welcome.

Other possible usages:

* In CI actions for setting up a cluster

Sponsoring WG: User Experience + Client

## Actions to fulfill

This area is used to track the [repo creation process](/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [X] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review. You are responsible for moving your entry on the board to "Needs Discussion" or "In Progress" as you move forward in this checklist.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [x] Send a PR adding entries for this repo in [`/peribolos/knative-sandbox.yaml`](https://github.com/knative/community/blob/main/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  - [x] Grant the sponsoring WG the `write` privilege.

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [x] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [x] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo main
  ```

- [x] Add your GitHub ID to the `OWNERS` file for your repo.

- [ ] [Set up](https://github.com/knative/test-infra/blob/main/guides/prow_knative_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge) prow for a new repo

- [ ] Bootstrap your CI jobs using [hack](https://github.com/knative/hack) project (look at other sandbox repos for reference)

- [ ] Create a sample PR to verify Prow (e.g., edit the boilerplate README)

- [ ] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

- [ ] (optional) Send a PR adding the repo to [knobots](https://github.com/knative-sandbox/knobots).

**Comment by evankanderson** [comment]
Might be nice for this to leverage the operator

**Comment by evankanderson** [comment]
TOC approved: evan, roland, markus

**Comment by omerbensaadon** [comment]
Sandbox is out since we have a GH org named `knative-sandbox`, quickstart is the next best option. 

As an MVP, we would like to put @csantanapr's KonK script into this plugin. 

The command would be `kn quickstart --kind`, we can add other environments later as we see fit! 

NOTE: Quickstart should not be used for production, only for "quickstart" deployments

**Comment by navidshaikh** [comment]
/retitle New Repo: kn-plugin-quickstart

@evankanderson can we get the repo created ? I will setup the prow etc.

/assign @evankanderson @navidshaikh

**Comment by navidshaikh** [comment]
> Send a PR adding entries for this repo in /peribolos/knative-sandbox.yaml

https://github.com/knative/community/pull/629

**Comment by navidshaikh** [comment]
- [x] bootstrap the Git repository see https://github.com/knative-sandbox/kn-plugin-quickstart
- [x] Set owners. Set to toc, client-writers, ux-writers
- [ ] Setup prow for new repo: see https://github.com/knative/test-infra/pull/2798

**Comment by navidshaikh** [comment]
- [x] Create a sample PR to verify Prow (e.g., edit the boilerplate README) --> see PR below
- [ ] Bootstrap your CI jobs using hack project (look at other sandbox repos for reference) --> see https://github.com/knative-sandbox/kn-plugin-quickstart/pull/1

**Comment by navidshaikh** [comment]
> (optional) Send a PR adding the repo to knobots.

@omerbensaadon @csantanapr : The plugin repo is set. The above step to enable auto-updates can be done once we've some plugin code.

/close
