### ISSUE TITLE
Add Slack integration for inclusive language

### ISSUE THREAD

**Issue by csantanapr** [knative/community#609]
Add Slack integration for inclusive language, similar to Kubernetes slack
I got a a few +1 on [#toc-steering-questions](https://knative.slack.com/archives/CU9DGL4FM/p1620910257273800) thread

@thisisnotapril  is going to take a look into this

**Comment by vaikas** [comment]
We'll make @omerbensaadon slack admin and he can take care of this as well as a few other items that he's been wanting to do (welcome bot, etc.).
@thisisnotapril will make the admin stuff happen.

**Comment by vaikas** [comment]
@omerbensaadon what's the status of this? Do you have everything from Steering you need?

**Comment by omerbensaadon** [comment]
<img width="751" alt="Screen Shot 2021-09-30 at 10 01 50 AM" src="https://user-images.githubusercontent.com/16281246/135499322-906815f6-9516-4dd2-9d71-15f726fa773d.png">

Done!
