### ISSUE TITLE
Set up VMT and disclosure list

### ISSUE THREAD

**Issue by evankanderson** [knative/community#612]
/assign @julz 

From the 18 May 2021 Security WG meeting.

**Comment by aliok** [comment]
Is this still relevant?

**Comment by davidhadas** [comment]
I suggest to drop this list, but since I did not see it described anywhere, I want to make sure we do not remove it and later find out it is required somewhere or otherwise referred to.

**Comment by davidhadas** [comment]
Duplicate of #1407
