### ISSUE TITLE
[Governance] WG leads governance rules.

### ISSUE THREAD

**Issue by devguyio** [knative/community#622]
### Description
_Note: This issue is a breakdown of #583 ._
Working group leads have an open ended term which limits the growth path of the project as well as the contributors. A healthy turnover of leadership is a long established beneficial practice in organized work.

### Suggested Changes
1. Change technical and execution WG leads to be an elected position with a limited term with the existing WG lead requirements defining the eligibility.
2. Add  an "Emeritus WG lead" state.

**Comment by evankanderson** [comment]
Question: do we imagine that there is a limit on the number of WG leads who can be elected?

I'd always assumed the answer was "no".

**Comment by vaikas** [comment]
For "Emeritus WG lead", I think we should have that for sure regardless of the first point. I think we should actually have that for TOC, Steering, TM, etc. also to ensure that folks get props that they deserve.

**Comment by devguyio** [comment]
> Question: do we imagine that there is a limit on the number of WG leads who can be elected?

@evankanderson personally, I didn't expect that if a WG has 3 tech leads, there'd be a room for more (numbers are an example) . And I'm worried that it's not clear to me how practical is that, hence unless it's strongly emphasized, it wouldn't have been my first guess. Not sure if it's just me. Can you explain more maybe why would that be useful and how can that scale? Of course having more than 1 WG lead is super useful in sharing load, responsibilities etc but not sure about having 6-7?

**Comment by vaikas** [comment]
@pmorie @devguyio just checking if there are any updates on this issue, or action items?

**Comment by vaikas** [comment]
@devguyio I'm going to close this for now, reopen if your concerns didn't get addressed properly.
