### ISSUE TITLE
Archive knative-sandbox/eventing-camel

### ISSUE THREAD

**Issue by dprotaso** [knative/community#642]
Following: https://github.com/knative/community/blob/main/REPOSITORY-GUIDELINES.md#procedure-for-removal

eventing-camel was deprecated on April 26th - https://github.com/knative-sandbox/eventing-camel/pull/97

**Comment by abrennan89** [comment]
I'm not sure, but if camel is going away from the project, is there some follow up required to remove it from docs?

It appears in the following places:

- https://dev-knative.netlify.app/development/eventing/sources/apache-camel-source/
- https://dev-knative.netlify.app/development/eventing/sources/#knative-sources
- https://dev-knative.netlify.app/development/admin/install/eventing/install-eventing-with-yaml/#install-optional-eventing-extensions
- https://dev-knative.netlify.app/development/admin/install/uninstall/#uninstalling-optional-eventing-extensions

**Comment by evankanderson** [comment]
I think the camel integration moved to the Apache Camel project proper, so this is probably a matter of updating links.

**Comment by dprotaso** [comment]
Email sent to mailing list - https://groups.google.com/g/knative-users/c/Y3uKyPOiMaw/m/wK2L5Wj9AgAJ

Archive date is June 24th

cc @nicolaferraro can you update the docs to point to the right spot?

**Comment by nicolaferraro** [comment]
Doc has been adapted to point to Kamelets. I think we can proceed with archiving it.

**Comment by dprotaso** [comment]
It's archived now
