### ISSUE TITLE
Update Feature track template to replace Docs with Dux

### ISSUE THREAD

**Issue by csantanapr** [knative/community#644]
The current [Feature track process](https://github.com/knative/community/blob/main/mechanics/FEATURE-TRACKS.md) states the use of a Google Doc [template](https://docs.google.com/document/d/1s6IIU98bi5FlRNmmBaLAn1rgoleK_ovcL746L7NHq0c/edit) 

Now that we no longer have a WG Docs, and it got merged with WG UX into a new WG Dux

It would be good to update the table for approvers to replace s/Doc/Dux

I'm the WG Technical Lead for Dux, and I can be a focal point to contact to see who can be an approver to review the doc, 
I have options based on the feature:
1. I could review and approve
2. I could delegate to another member of the Dux to review and approve
3. I might bring other members of the Dux WG to join me as additional approvers representing Dux WG.

cc @omerbensaadon  @abrennan89

/assign @evankanderson

**Comment by evankanderson** [comment]
Correction: use [this feature tracks template](https://docs.google.com/document/d/17mpOm-7Bq_S77bIQHwuGH7kVOkOoO6XiOhdQoDqqLKM/edit?usp=sharing)

I've also sent https://github.com/knative/community/pull/645 to fix the link in `knative/community`.

**Comment by evankanderson** [comment]
Updated the feature tracks doc, there were only two references to the docs WG. I left the specific references to "Documentation" as a feature track concern, as that was functional rather than organizational.

/close
