### ISSUE TITLE
PROCESS CHANGE: Add "Are you using Knative?" issue to Community, link to it, maintain an ADOPTERS.MD in community 

### ISSUE THREAD

**Issue by omerbensaadon** [knative/community#648]
Proposal: Create a "Are you using Knative?" issue in Community similar to https://github.com/dapr/dapr/issues/3169, pin it. 

Create a similar issue in each of our main repos (serving, eventing, docs), pin it, links to this issue in Community. 

See the proposed text: 
```
# Are you using Knative?

If you are using Knative, we would love to know!

## Why?
Tracking usage in OSS is hard, if you leave a comment on this issue we can better understand who our users are and deliver a better experience for YOU!

- We'd like to give your organization the opportunity to collaborate more closely with contributors (if you want to)
- We want to help promote your organization 
- We want to show off all the awesome stuff our users are doing 

## How you can help
Submit a comment in this issue to include the following information, which would then also get included into the [ADOPTERS.md]($//TODO LINK) file and (if applicable) on the Knative homepage: 

Organization/Company: 
Website: 
Country: 
Contact: (email or Twitter at least one please!)
Usage scenario: e.g. We use Knative for XYZ
Status: Development?/Production?
```

* Expected benefits. Who gains the benefits? Why will they benefit?
> We get a better understanding of who our users are, more logos for the website, more reference implementations etc. etc. 
* Expected costs. Who bears the costs? How heavy are they?
> Next to nothing 
* Timeframe for implementation / rollout.
> As soon as it is approved
* Are you willing to drive the process, or is this a request for help?
> Yes, I need someone to pin the issue in each Repo though (I believe)

**Comment by omerbensaadon** [comment]
I won't be able to attend the next 2 Steering Meetings :(

**Comment by xtreme-sameer-vohra** [comment]
Related - https://github.com/knative/docs/issues/3246

**Comment by bsnchan** [comment]
cc @knative/steering-committee 

I love this idea! I can bring it up at the next steering meeting if you can't make it :)

**Comment by bsnchan** [comment]
Steering loves this idea :) let's do it

/assign @bsnchan

**Comment by bsnchan** [comment]
Main issue created here (https://github.com/knative/community/issues/688), will update the issue once I have the ADOPTERS.MD file merged in.

**Comment by bsnchan** [comment]
Issue has been created -- I pinned it at the top of of knative/community. @omerbensaadon - were you thinking to create an issue in serving/eventing/docs as well? I'm worried that the comments may end up in different places if we were to do that. What do you think?

**Comment by vaikas** [comment]
/close

We decided to just have one instead of spreading this throughout the various repos.
