### ISSUE TITLE
Document the current process of shepherding code changes

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative/community#656]
Document `how to safely drive an accepted change to conclusion`
This includes but not limited to refreshing [Feature Tracks](https://github.com/knative/community/blob/main/mechanics/FEATURE-TRACKS.md) with changes with regards to experimental featuers.

Related to [Knative GA/Licensable Requirement](https://docs.google.com/document/d/1mC_nDpLIycqiBn5Om1tvbcY3yyAR3WUNXcHiyloEzhg/edit#heading=h.lz2n48vymqzb)

**Comment by evankanderson** [comment]
This looks like this should tie in with #681

**Comment by evankanderson** [comment]
I think https://github.com/knative/community/blob/main/CONTRIBUTING.md#design-documents actually has this information.

/close
