### ISSUE TITLE
Upgrade Slack account

### ISSUE THREAD

**Issue by bsnchan** [knative/community#68]
It would be great to have retention history for our Slack organization.

Some relevant issues here:
* https://github.com/kubernetes/community/issues/372
* https://github.com/istio/istio/issues/191

**Comment by dprotaso** [comment]
Relevant comment
https://github.com/kubernetes/community/issues/372#issuecomment-280870270

**Comment by Abd4llA** [comment]
That would be great, not just to retain the chat history (which is an invaluable feature IMHO) , but I also find the user groups feature very very handy. To be able to mention and know the Steering Committee, TOC, WG leads etc via `@sc` or `@toc` etc.

**Comment by rgregg** [comment]
Quick update, we've converted Slack over to a paid standard plan.
