### ISSUE TITLE
[1.0.Alpha] All "core" repos have README.md, CODE-OF-CONDUCT.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by omerbensaadon** [knative/community#680]
This is an Epic-Level issue which tracks issues in Other Repos. 

## README.md
- [x] [serving](https://github.com/knative/serving/blob/main/README.md)
- [x] [eventing](https://github.com/knative/eventing/blob/main/README.md) 
- [x] [docs](https://github.com/knative/docs/blob/mkdocs/README.md) 
- [x] [client](https://github.com/knative/client/blob/main/README.md)
(See below for others)
## CODE-OF-CONDUCT.md
- [x] [serving](https://github.com/knative/serving/blob/main/code-of-conduct.md)
- [x] [eventing](https://github.com/knative/eventing/blob/main/CODE_OF_CONDUCT.md) 
- [x] https://github.com/knative/docs/issues/4066
(See below for others)

## CONTRIBUTING.md
- [x] [serving](https://github.com/knative/serving/blob/main/CONTRIBUTING.md)
- [x] [eventing](https://github.com/knative/eventing/blob/main/CONTRIBUTING.md) 
- [x] [docs](https://github.com/knative/docs/blob/mkdocs/CONTRIBUTING.md) 
(See below for others)

**Comment by psschwei** [comment]
### README.md

[ ] [serving](https://github.com/knative/serving/blob/main/README.md)
[ ] [eventing](https://github.com/knative/eventing/blob/main/README.md)
[ ] [docs](https://github.com/knative/docs/blob/main/README.md)
[ ] [client](https://github.com/knative/client/blob/main/README.md)
[ ] [community](https://github.com/knative/community/blob/main/README.md)
[ ] [opereator](https://github.com/knative/operator/blob/main/README.md)
[ ] [networking](https://github.com/knative/networking/blob/main/README.md)
[ ] [ux]([https://github.com/knative/ux/blob/main/README.md)

### CODE-OF-CONDUCT.md

[ ] [serving](https://github.com/knative/serving/blob/main/code-of-conduct.md) lowercase
[ ] [eventing](https://github.com/knative/eventing/blob/main/CODE_OF_CONDUCT.md)
[ ] [docs] no file, but linked in dev docs...
[ ] [client](https://github.com/knative/client/blob/main/code-of-conduct.md) lowercase
[ ] [community](https://github.com/knative/community/blob/main/CODE-OF-CONDUCT.md)
[ ] [operator]
[ ] [networking](https://github.com/knative/networking/blob/main/code-of-conduct.md) lowercase
[ ] [ux]

### CONTRIBUTING.md

[ ] [serving](https://github.com/knative/serving/blob/main/CONTRIBUTING.md)
[ ] [eventing](https://github.com/knative/eventing/blob/main/CONTRIBUTING.md)
[ ] [docs](https://github.com/knative/docs/blob/mkdocs/CONTRIBUTING.md)
[ ] [client](https://github.com/knative/client/blob/main/CONTRIBUTING.md)
[ ] [community](https://github.com/knative/community/blob/main/CONTRIBUTING.md)
[ ] [operator]
[ ] [networking]
[ ] [ux]

**Comment by psschwei** [comment]
Summary: all repos have readmes, and there are PRs open to add the COC and/or contributor doc to the repos missing them

**Comment by evankanderson** [comment]
Just copying a comment from the operator repo:

(If these are copies of the doc in https://github.com/knative/community, it should be possible to add to https://github.com/knative-sandbox/knobots/blob/main/actions/update-community/entrypoint.sh to copy additional files to all repos.)

**Comment by psschwei** [comment]
Well, that would've made things easier :smiley:  

I'll send a PR to update knobots to copy the COC. The Contributor doc looks to have some unique elements on a repo-by-repo basis (for example, eventing has some custom text about creating docs issues), so will leave that one off for now. Though it might make sense to standardize the contributor doc also sometime down the line (after GA, definitely not proposing to do that now)

**Comment by evankanderson** [comment]
👍 

Sorry, I didn't realize someone was about to do this, and I'd had it in my head that I'd get to it when a round tuit finally showed up.

**Comment by psschwei** [comment]
No worries at all, I ended up learning more about the automation, so call it a small win :)

**Comment by evankanderson** [comment]
If you ever think "I need to PR things across all repos", definitely take a look in knobots.

(And poke me on slack if you need a further guide.)

**Comment by omerbensaadon** [comment]
@psschwei looks like this is done...?

**Comment by psschwei** [comment]
Yes, last one merged in about an hour ago.

**Comment by psschwei** [comment]
I can't edit the original checklist, but you can use my [comment above](https://github.com/knative/community/issues/680#issuecomment-926614715) to get all the details.

**Comment by omerbensaadon** [comment]
heck yeah awesome

**Comment by psschwei** [comment]
@omerbensaadon there was a problem with the COC automation job, and a few docs were updated before it could be corrected. I've opened PRs to clean those up:

* Eventing: https://github.com/knative/eventing/pull/5774
* Operator: https://github.com/knative/operator/pull/799
* Networking: https://github.com/knative/networking/pull/523

So think we might want to reopen this until those PRs merge.

**Comment by psschwei** [comment]
Not relevant for GA, but I also got PRs out to fix all of the repos (both in `knative` and `knative-sandbox`) that the incorrect COC was pushed to. Don't think those matter for GA, but more a FYI
