### ISSUE TITLE
TOC should curate where to get started

### ISSUE THREAD

**Issue by evankanderson** [knative/community#681]
If Working Groups have a common way to provide the following information to new contributors:

* Roadmap -- what projects are coming down the pipeline
* Good First Issues
* Setup / bootstrapping costs (especially when certain components are hard to contribute to)

Then the TOC can and should provide a "roll-up" view to guide contributors to places where they could have the most impact if they don't have specific interests.

**Comment by rhuss** [comment]
I think we could mandate that every WG repo includes a:

* `HOW_TO_CONTRIBUTE.md` (but I think that was already on a 1.0 criterium ?)
*  Having a `good first issue label` (we should agree on a uniform label across repos, could be that peribolos automatically create those
* Having a "Roadmap Project" with columns "Backlog", "3 Months", "6 Months", reflecting the format used in the WG update presentations. Sample  from the client -->  https://github.com/knative/client/projects/4

For more concrete tasks, in the client, the client WG starts to use a project-per-release (e.g. https://github.com/knative/client/projects/5 for 0.25). The benefit over a "Milestone" is, that you can better organize the state of such issues/prs. Not sure if this is super useful, though.

**Comment by vaikas** [comment]
#680 seems related to this?

**Comment by omerbensaadon** [comment]
https://docs.google.com/document/d/1LJjgdOKw5qaMlvRLeQw5eEHniyHrRb6lV-54VR22YXw/edit#heading=h.q5a22la9zwd8 

^ Friction Log Template

**Comment by evankanderson** [comment]
The suggestion is that we should encourage new contributors to keep a friction log... this is a way that contributors can generate a positive contribution from day 1 while they are getting up to speed on the specific areas / working groups they can contribute to.

**Comment by evankanderson** [comment]
Dave points out that slack admin and a welcome bot should be possible, but we need a consistent policy to give e.g. TOC or WG leads access to the admin rights.

**Comment by evankanderson** [comment]
Ashleigh also brought up an issue for Steering to figure out a better access control mechanism so that non-WG leads can organize meetings on the Knative calendar.

**Comment by carlisia** [comment]
Related: https://github.com/knative/community/issues/925.

**Comment by evankanderson** [comment]
We now have sometimes-curated roadmaps, but we don't have a good summary view for people new to the project.

Possible inspiration: https://gateway-api.sigs.k8s.io/contributing/

AI: Have some pages on the website specifically for new contributors to show them around the org (that's the MVP / min bar).  Replace "Blog", "About", "Contributing" with a "Community" section (figure out where to put the blog link elsewhere). Target should be folks who want to lurk, as well as folks who have decided to commit to contributing.

AI: (Dave) check with Gateway-API folks to find out how their meeting recordings --> YouTube is automated.

Challenge: discussions happen many different places, it can be hard to funnel conversations into a single discussion board / other forum for new contributor questions.

**Comment by evankanderson** [comment]
Dave will pull out meeting recordings on YouTube as a separate issue, so we don't conflate it with improving the onboarding ramp for community and contributors.

**Comment by dprotaso** [comment]
@evankanderson I saw your PR https://github.com/knative/docs/pull/5348 merged - is there anything left for this story that you're still working on?

**Comment by dprotaso** [comment]
Going to close this out - I think Evan's work is a great start and we want to surface this better on the website.

I create a separate issue for that which covered by the UX working group who are doing a website redux
