### ISSUE TITLE
Rename knative-community to something else

### ISSUE THREAD

**Issue by coryrc** [knative/community#69]
Follow-up of #23 
Because of knative/community, searching for knative-community comes up with only hits for the former and not the latter. I think a unique naming would be better and since it is so-far unused, now is the time if people agree.

Kubernetes has:

* [kubernetes-sigs](https://github.com/kubernetes-sigs)
* [kubernetes-incubator](https://github.com/kubernetes-incubator) (deprecated in favor of sigs)
* "associated repos" which are any repo that follows the guidelines and use the CLA bot

Given we don't have SIGs, closest is working groups, I think one of the following would be a better naming and all have no or sufficiently-low hits on search:

* knative-workinggroups
* knative-workgroups
* knative-wgs
* knative-adjacent
* knative-annex
* knative-supplement
* knative-incubator (does imply things will "grow-up" though)
* knative-sandbox

(Rejected -extension, -unofficial, & -contrib because of other search hits)

People who mentioned the name in the last issue:
@rgregg 
@maximilien 
@evankanderson 
@mchmarny

**Comment by maximilien** [comment]
LGTM

**Comment by coryrc** [comment]
-sandbox is currently winning: https://app.slack.com/client/T93ELUK42/CU9DGL4FM/thread/C93E33SN8-1582850486.042800

**Comment by dprotaso** [comment]
`-experimental`

**Comment by rgregg** [comment]
We voted in the Steering committee today, and decided on 'knative-sandbox'. We've renamed the org  on GitHub as well.

https://github.com/knative-sandbox
