### ISSUE TITLE
Knative contribution guidelines(community/contributing/_index.md) has bunch of empty bullets

### ISSUE THREAD

**Issue by vaikas** [knative/community#699]
If you go to this link:
https://knative.dev/community/contributing/

And scroll the "center pane" all the way down, there's a bunch of empty bullet-points there in the list. For example below 'Pull request guidelines'.

**Comment by vaikas** [comment]
@omerbensaadon (feel free to teflon to more appropriate person :) ) I created this issue from knative.dev website, and I'm not entirely clear if this is an issue in the community repo, or the docs repo, would you mind taking a peek to make sure this issue is in the right repo :)

**Comment by vaikas** [comment]
@abrennan89 @julz can you point me to where to fix this, I don't get it? :) Thanks :)

**Comment by abrennan89** [comment]
Honestly I've no idea what is going on with community docs these days. @omerbensaadon or @RichardJJG are probably better people to ask 🤷🏻‍♀️ 😂

**Comment by julz** [comment]
So the tldr is this is a painful seam of the old Hugo flow that we haven't fixed yet and that we may have a plan to just avoid in future. The longer version (and **seriously, feel free to skip this paragraph**, it's here in case you're interested!) is the knative/community repo gets copied over into the community/contributing folder of the docs repo, and then the result is copied in to a directory inside the website repo. Then a [file in the community/contributing folder of the docs repo does an include](https://github.com/knative/docs/blob/4a12addcfe8c440ac456b8f72a76c55166685268/community/contributing/_index.md)  (see the `readfile` bit) of a [file copied over from the community repo](https://github.com/knative/community/blob/4c5e26da9e75e166c51da0015b0484750f97a409/README.md). So the resulting page is an odd combo of two pages, from different repos. THEN there's then an additional TOC added to the page at the bottom via the `showlandingtoc: "true"` bit of the metadata, which is probably the bit that's going wrong, and is [defined in the website repo](https://github.com/knative/website/blob/39b28522b71121fade15595fd8a379eb3153c8f2/layouts/partials/landingtoc.html) (yes, this means the page has significant contributions from 3 repos) - I think that's the bit that needs fixing (or maybe just removing). (To be clear none of this is related to the mkdocs stuff, it's how this has always been afaict).

This is all part of the old Hugo-based flow to build the community repo as part of the main website and obviously got a little messy over the years, as things do. We could try to fix it and move things over to mkdocs in a hopefully simpler way (and in the meantime just setting "showlandingtoc: false"[ in _index.md](https://github.com/knative/docs/blob/4a12addcfe8c440ac456b8f72a76c55166685268/community/contributing/_index.md) _might_ be a simple way to fix things), but I think the general feeling in the UX working group is coalescing towards "**do we _actually_ need to build stuff in the community repo in to the website, or can we just have a simple [one-page community section like Kubernetes.io does](https://kubernetes.io/community/), and have it just _link to the GitHub view_ of the community repo in the contributing section?**", which would hopefully make the whole problem of building three repos in to one site - and this whole problem - disappear 🙏.

**Comment by RichardJJG** [comment]
I've added your comment above to [Issue 4038](https://github.com/knative/docs/issues/4038), @julz. It looks like much needed context for that one (hope you don't mind!)

**Comment by vaikas** [comment]
Thanks @julz for the context. Suffice it to say then that this issue can be closed, since the proper fix is being worked under the docs repo?
If I misunderstood something (highly likely as usual :) ) please reopen :)
