### ISSUE TITLE
New repos in knative-community

### ISSUE THREAD

**Issue by coryrc** [knative/community#70]
As part of knative/pkg#883, we use a very simple wrapper to redirect uses of klog or glog into our Zap logger. Because of the `dep` tool, these wrappers must be in their own repo (otherwise they'd simply be a directory of knative/pkg).

I have [forked](https://github.com/coryrc/klog) the [repos](https://github.com/coryrc/glog) and attempted to upstream into the Istio project repositories, but it isn't something they seem keen on supporting. I'd like to open these repos in our knative-community project.

These are very small shims and I don't anticipate more than one change every six months. The glog project is abandoned and klog's goal is to remain compatible with it, so we should not be seeing any changes.

**Comment by evankanderson** [comment]
Is this still needed?

/assign @coryrc

**Comment by mattmoor** [comment]
Sounds like Cory is out of office for a bit, let's snooze this until we can get more context (eta: mid August).

**Comment by mattmoor** [comment]
I've seen @coryrc on slack, so perhaps we could get this on the agenda for an upcoming meeting?

**Comment by coryrc** [comment]
Hmm, because we now have Go modules, I think these could actually be separate modules of knative/test-infra. I will try that and come back to you if it doesn't work.
