### ISSUE TITLE
Update / verify each WG Emeritus section

### ISSUE THREAD

**Issue by vaikas** [knative/community#709]
As per #626 we now have a process.

So, if WG leads could go and update their sections as appropriate that would be swell. Please update your WG section, and check the checkboxes once they've been done so we can close this once all the boxes have been checked. If your WG has no Emeritus members, please still check the box so I know when all WG have looked at this.

- [x] [API Core](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#api-core)
- [x] [Client](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#client)
- [x] [DUX](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#documentation--user-experience)
- [x] [Event Delivery](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#event-delivery)
- [x] [Eventing Sources](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#eventing-sources) 
- [x] [Networking](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#networking)
- [x] [Operations](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#operations)
- [x] [Productivity](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#productivity)
- [x] [Scaling](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#scaling)
- [x] [Security](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#security)

**Comment by vaikas** [comment]
@dprotaso told me to tag everybody, so here goes :)

@dprotaso
@rhuss
@navidshaikh
@omerbensaadon
@csantanapr
@lionelvillard
@matzew
@n3wscott
@nak3
@ZhiminXiang
@houshengbo
@chizhg
@markusthoemmes
@vagababov
@evankanderson
@julz

**Comment by csantanapr** [comment]
DUX WG has no Emeritus

**Comment by rhuss** [comment]
Add Client WG leads via https://github.com/knative/community/pull/712

**Comment by ZhiminXiang** [comment]
Add Networking WG leads via https://github.com/knative/community/pull/711

**Comment by dprotaso** [comment]
@vaikas what about old WG groups?

ie. Build/Observability etc.?

**Comment by vaikas** [comment]
Perhaps add those into the bottom of the page with a new section as Emeritus WG and use the same table format? WDYT? @dprotaso

**Comment by dprotaso** [comment]
ok done - https://github.com/knative/community/pull/714

**Comment by vaikas** [comment]
Actually @omerbensaadon @csantanapr since Dux is what became of the Docs WG, if you could either:

* Add an emeritus for docs just like @dprotaso did in #714 
* Add the previous WG leads (for example @abrennan89) to the Dux (with a blurp about the evolution)

I don't have a strong preference for either (or something else) but do not want their props to get lost somewhere.

**Comment by vaikas** [comment]
@csantanapr @omerbensaadon for DUX, well, actually docs to give them props.
Event Delivery will be handled in #738 
Event Sources will be handled in #732 
@houshengbo for Operations (if there's none, please just state it and check the box)
@chizhg @n3wscott for productivity
@markusthoemmes with @vagababov #722 was that it? If so, please just state it and check the box.

**Comment by markusthoemmes** [comment]
We'll want to add @josephburnett. On it.

**Comment by markusthoemmes** [comment]
Send a PR in https://github.com/knative/community/pull/741

**Comment by houshengbo** [comment]
https://github.com/knative/community/pull/752
I have sent this PR for the update.

**Comment by rhuss** [comment]
I think we are kind of complete with the updates ? @omerbensaadon @abrennan89 the only checkbox missing is for DUX, so maybe @abrennan89 could you please add an emeritus section for the retired Doc WG leads ? (guess for UX we don't need this yet ...)

**Comment by rhuss** [comment]
I think we are done now.

/close
