### ISSUE TITLE
Should we delete the gdocs migration code?

### ISSUE THREAD

**Issue by vaikas** [knative/community#728]
Is there any need for this anymore?

https://github.com/knative/community/tree/main/mechanics/tools/gdocs-migrate

If not, let's remove it so we don't have to keep maintaining it. Even if we don't maintain code, we still have to update the deps like here:
https://github.com/knative/community/pull/727

**Comment by evankanderson** [comment]
If this has a maintenance cost, let's delete it. It's no longer needed, and we have git history.
