### ISSUE TITLE
PROCESS CHANGE: New Contributor Retrospective

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative/community#775]
# Why
Solicit pain points and potentially solutions from the folks that have recently joined the community and had to onboard.
Present the findings to the larger Knative contributor community to ensure that the precious efforts expended to improve the new contributor experience are spent on the highest priority areas.

## Nice to haves
- Identify solutions
- Identify new contributors that are interested in helping in driving solutions

# What
Run a Knative New Contributor Retrospective for folks in the community covering
- what worked well
- what was confusing or didn't make sense
- what was bad

## Background:
Contributor onboarding into the Knative community was highlighted as a pain point for new members on the VMware Knative OSS team and the idea is to have a broader discussion as such challenges are likely to be experienced by all new Knative contributors.
This was raised during last week's TOC meeting and it sounded like there would be interest in doing this at the community level.

* Expected benefits. Who gains the benefits? Why will they benefit?
  _The Knative community would be the beneficiary by reducing the friction new contributors run into, it increase contributor productivity and expand the number of contributors._
* Expected costs. Who bears the costs? How heavy are they?
  _The only expected cost is contributor time. As mentioned above, onboarding as a topic was raised during the TOC meeting so its currently already on the minds of more seasoned contributors._
* Timeframe for implementation / rollout.
  _There aren't any specific deadlines that impact this activity. It would be good to solicit new folks so there is a meaningful set of new contributors that can share feedback._
* Are you willing to drive the process, or is this a request for help?
  _Yes, willing to help organize and drive the retro and present findings back to TOC/SC_

**Comment by psschwei** [comment]
I'd be willing to volunteer for the retro (I started contributing to Knative in May)

**Comment by vaikas** [comment]
Thanks @xtreme-sameer-vohra and others that ran this. There will be action items following up, but they will go to their own issues.
