### ISSUE TITLE
Knative version table is old

### ISSUE THREAD

**Issue by ZhiminXiang** [knative/community#778]
Currently the latest knative version in the version table https://github.com/knative/community/blob/main/mechanics/RELEASE-VERSIONING-PRINCIPLES.md#knative-serving-version-table is 0.25.

Currently we are releasing 0.26. We need to expand that table to include future knative version.

**Comment by dprotaso** [comment]
It's part of the release process to update that table 

see: https://github.com/knative/release#final-checks--transition-to-the-next-release-leads
