### ISSUE TITLE
Approve the proposal to move Knative test infra to be community-managed

### ISSUE THREAD

**Issue by chizhg** [knative/community#786]
[Knative test infrastructure 1.0](https://docs.google.com/document/d/1U6wybYjCslEhsKOiennrwhoKZmSVnd1NGbFI8gnnnOg/edit) is the proposal that aims at solving the below long-standing issues by moving Knative test infra to be community-managed:
- [Shift productivity infrastructure to a community managed environment](https://docs.google.com/document/d/1LwkzXVDJYLmiVElCEiJ1ITSr4TGkHfipe8ABK_7IxCQ/edit?hl=en#)
- [PROCESS CHANGE: Adopt K8s infra for gsuite mgmt](https://github.com/knative/community/issues/443)
- [Change the account for Knative prow robot](https://github.com/knative/community/issues/448)

The community has decided these should happen post-1.0. But before that, it'll be ideal to have the proposal approved first, so that we can plan on resources ahead.

Since the proposal requires changes that involve multiple parties, it needs to be approved by both Steering Committee and TOC.

**Comment by evankanderson** [comment]
@chizhg , we mostly use org-level projects which allow anyone in the org to move / add items, rather than the prow commands. (I added the TOC label for you.)

**Comment by thisisnotapril** [comment]
Issue currently assigned to me while we look at possibility of Google continuing to host on GCP, or using a crowdfunding site for oss project costs. Examples of those sites are https://lfx.linuxfoundation.org/tools/crowdfunding and https://opencollective.com/opensource

**Comment by chizhg** [comment]
The proposal has already been approved as Knative is going to be donated to CNCF. The sections in the [Knative test infrastructure 1.0proposal](https://docs.google.com/document/d/1U6wybYjCslEhsKOiennrwhoKZmSVnd1NGbFI8gnnnOg/edit) have been broken down into separate issues, which are now being tracked in https://github.com/orgs/knative/projects/40/views/11. We are actively working on these issues, and the ETA to resolve them is aligned with the finalization of CNCF donation.

Resolving this issue.
