### ISSUE TITLE
Generate annual report for 2021

### ISSUE THREAD

**Issue by vaikas** [knative/community#787]
We need to generate the annual report for Knative, just like here:
https://github.com/knative/community/tree/main/annual_reports

Just putting this on the SC radar so we don't forget :)

**Comment by csantanapr** [comment]
/assign @thisisnotapril 

@thisisnotapril will take the slide deck as input and send to a design agency to create the final flyer report pdf using the [theme from last year](https://github.com/knative/community/blob/main/annual_reports/Knative%202020%20Annual%20Report.pdf)

**Comment by csantanapr** [comment]
@vaikas here are the slides to make them into a report pdf
https://docs.google.com/presentation/d/1eWf1mgrBzErcFJD-M6WDFrUGIvHsX26Uf-9-CmNEcyo/edit?usp=sharing

**Comment by csantanapr** [comment]
Steering is going to publish the slides as PDF, create blog and send email to mailing list

**Comment by vaikas** [comment]
Email has been sent. @itsmurugappan is cranking out the blog.

**Comment by vaikas** [comment]
Yep!
