### ISSUE TITLE
Fix permissions and roles in GDrive and Slack

### ISSUE THREAD

**Issue by dprotaso** [knative/community#794]
We should do an audit to ensure steering and toc members have the appropriate roles in slack and gdrive.

ie.
1. In GDrive I'm not a content manager so I couldn't open up permissions for a recording
2. In Slack I'm not a workspace admin

Unclear if there's a way to automate this

cc @vaikas

**Comment by vaikas** [comment]
Seems related to #443 and #314

**Comment by vaikas** [comment]
We're going to take a crack at this and see what the actual effort is so we can do some planning.

**Comment by thisisnotapril** [comment]
Closing this as it's effectively covered by the decisions made in Steering today
