### ISSUE TITLE
PROCESS CHANGE: Remove most of the Community Section from the Community site, link to this Github Repo instead

### ISSUE THREAD

**Issue by omerbensaadon** [knative/community#796]
Currently, our Community site is a bit of a tarball which will be difficult to move to the MkDocs format for a few reasons: 
- There are some wonky page renderings, like https://knative.dev/community/contributing/ which is rendered in part by https://github.com/knative/docs/blob/8f742c9f4800ab88a086ba21ee814d55b7c4e952/community/contributing/_index.md AND https://github.com/knative/community/blob/4c5e26da9e75e166c51da0015b0484750f97a409/README.md
- Some of the files in the Community site really ought to be owned by Community, and the process for making changes ought to not go through the docs process
- Some of the things on the site don't make much sense as a web page, and would make far more sense as Markdown files in the Community repo (like "how to create a WG" or "Slack Guidelines") since they are not likely to change or be referenced regularly
-  Having a lightweight Community Page helps bubble up what is truly important for new Contributors (Knative Calendar, Existing WGs, how to Contribute, etc.) 

#### Expected Benefits 
- Helps us simplify our website infra 
- Allows us separate and highlight things that we know are important to new contributors 
- Lots and lots of stuff is broken on the Hugo Community site so we need to get it off of that infra ASAP 

#### Expected costs. Who bears the costs? How heavy are they?
- Not very high, just moving around some .md files   
#### Timeframe for implementation / rollout.
- As soon as this is approved
####  Are you willing to drive the process, or is this a request for help?
- As always, yes!

**Comment by julz** [comment]
+1 from me, this would let us remove the last bit of Hugo and archive the website repo, which would be nice, without needing to transfer lots of files from the community repo (which is the right place for them, imo) over to docs and without importing back the complexity and pain we previously faced in rendering cross-repo content. Tldr I think this is way less simpler and nicer and we should do it. I'm also happy to help.

**Comment by evankanderson** [comment]
It looks like https://github.com/knative/docs/issues/4394 addresses this.

Going to close this issue since we all agreed this was the right thing to do.

/close
