### ISSUE TITLE
Knative contributor guidelines(community/contributing/CONTRIBUTING.md)

### ISSUE THREAD

**Issue by matthiasgubler** [knative/community#817]
The link mentioned here https://knative.dev/community/contributing/contributing/#:~:text=Knative%20documentation%2C%20see-,DOCS-CONTRIBUTING,-.%20A%20lot%20of leading to the page https://knative.dev/community/contributing/docs/DOCS-CONTRIBUTING is dead.

There is no DOCS-CONTRIBUTING.md file in whole repo anymore and I didn't found it yet.

**Comment by evankanderson** [comment]
Fixed in https://github.com/knative/docs/pull/4544 (or earlier)

/close
