### ISSUE TITLE
Clarify K8s min version principle given the introduction of the maintenance mode

### ISSUE THREAD

**Issue by dprotaso** [knative/community#827]
K8s upstream has extended their support policy to 14 months. The last 2 months of this support window is 'maintenance mode' and [is described as](https://kubernetes.io/releases/patch-releases/#support-period):

> During the two-month maintenance mode period, Release Managers may cut additional maintenance releases to resolve:
>
> - CVEs (under the advisement of the Security Response Committee)
> - dependency issues (including base image updates)
> - critical core component issues
>
> At the end of the two-month maintenance mode period, the patch release series will be considered EOL (end of life) and cherry picks to the associated branch are to be closed soon afterwards.
>
> Note that the 28th of the month was chosen for maintenance mode and EOL target dates for simplicity (every month has it).

Our min K8s policy states we support whatever is supported upstream at the time of a Knative release. We should update the language to exclude the 'maintenance mode'

**Comment by dprotaso** [comment]
We need to update the k8s versioning principles now that K8s has a maintenance mode window.

**Comment by rhuss** [comment]
> Our min K8s policy states we support whatever is supported upstream at the time of a Knative release. We should update the language to exclude the 'maintenance mode'

Would it make sense to also include such a notion of a 'maintenance mode'? I mean, when a k8s enters maintenance mode it will be still  2 months around, which is for one future Knative version, too. I don't mind being more restrictive than k8s and that is probably the right thing to do. 

So +1 from my side but would love to hear some more opinions before merging it.

**Comment by nainaz** [comment]
I would like to see us defining such maintenance mode too. 
But, I am probably not seeing the implications for such action. 

For example: Knative enters maintenance mode with Kubernetes
