### ISSUE TITLE
New Repo: func

### ISSUE THREAD

**Issue by lance** [knative/community#844]
## Repo information

Org: knative-sandbox

Repo: func

Purpose (Description): The `kn-plugin-func` project was originally conceived as its own standalone CLI as well as a Go library. Its continued evolution has maintained this separation quite cleanly as `func` moved to knative-sandbox and became `kn-plugin-func`. We would like to formalize the separation of concerns, by extracting the Go library bits into its own GitHub repository where it can be maintained and versioned independent of its status as a plugin for `kn`.

Sponsoring WG: By the transitive property of Task Force to Working Group, the Client WG.

## Actions to fulfill

This area is used to track the [repo creation process](/mechanics/CREATING-A-SANDBOX-REPO.md).
The _requestor_ and _sponsoring WG lead_ should perform the steps listed below and cross out the checkmarks when done.
The TOC is involved only in the **TOC Gate** steps.

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review. You are responsible for moving your entry on the board to "Needs Discussion" or "In Progress" as you move forward in this checklist.

_You may not be able to use the Projects quick menu on this page. In that case, go to the project board and use the **Add cards** interface._

- [x] Send a PR adding entries for this repo in [`/peribolos/knative-sandbox.yaml`](https://github.com/knative/community/blob/main/peribolos/knative-sandbox.yaml). Please mind the alphabetical order when adding to a list.
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  - [x] Grant the sponsoring WG the `write` privilege.

**TOC Gate**: _Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [x] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/docs/pull/4160)).

- [x] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo main
  ```

- [x] Add your GitHub ID to the `OWNERS` file for your repo.

- [x] [Set up](https://github.com/knative/test-infra/blob/main/guides/prow_knative_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge) prow for a new repo

- [x] Bootstrap your CI jobs using [hack](https://github.com/knative/hack) project (look at other sandbox repos for reference)

- [x] Create a sample PR to verify Prow (e.g., edit the boilerplate README)

- [x] Verify that within 24 hours the appropriate branch protections have been applied
   requiring `tide` to pass before PRs are merged.

- [x] (optional) Send a PR adding the repo to [knobots](https://github.com/knative-sandbox/knobots).

**Comment by evankanderson** [comment]
Should this go into `client-pkg`, or do we need another repo, like `func-pkg`?

It sounds like we don't want to pollute the dependencies of `client-pkg` with all the `func` stuff, so requesting a separate repo.

**Comment by lance** [comment]
Link to Slack discussion https://knative.slack.com/archives/CUU6LEMRT/p1639076443212900

**Comment by rhuss** [comment]
As mentioned, I'd prefer a repo name like `func-pkg` to emphasize its usage as a library (and does not contain a "func" binary thing)

**Comment by evankanderson** [comment]
SGTM!

/close
