### ISSUE TITLE
Support CNCF onboarding

### ISSUE THREAD

**Issue by vaikas** [knative/community#858]
This is the umbrella issue for tying together any work that Steering Committee needs to do to support the donation process. More details to come later.

**Comment by evankanderson** [comment]
Related issue #864 (one of the items of support)

**Comment by csantanapr** [comment]
We now have to work on incubation onboarding tasks  from this issue https://github.com/cncf/toc/issues/794

**Comment by csantanapr** [comment]
@pmorie suggested that this issue is not contributing much now that we are accepted to CNCF

We are tracking the TODOs for onboarding using a github project https://github.com/orgs/knative/projects/39/views/1

/close
