### ISSUE TITLE
Fill out CNCF Due Diligence document

### ISSUE THREAD

**Issue by evankanderson** [knative/community#864]
https://docs.google.com/document/d/1qPMyIBZ1tBk6WpEMPuLtTrjA6lvbrQ7DvCZb22S0llo/edit#

See ​​https://github.com/cncf/toc/pull/762 for the CNCF side of this

**Comment by vaikas** [comment]
Let's go ahead and divvy up the work, so some of these sections are clearly owned by, say Steering, by TOC, or something else. They seem to have some natural lines of division, but I think it would be good to assign them explicitly, so we can keep track of the "sub" work.

**Comment by rhuss** [comment]
In the section "Architectural, design and feature overview" Serving and Eventing is described. Would it make sense to add an additional "Client" subsection or is this too small and we should add client aspects to the individual Serving and Eventing sections, respectively?

**Comment by evankanderson** [comment]
I think it would be fine to add the client if you want!

**Comment by evankanderson** [comment]
This is pretty much done

/close
