### ISSUE TITLE
Foster Google Summer of Code (GSOC) 2022 for Knative

### ISSUE THREAD

**Issue by csantanapr** [knative/community#867]
Steering to work with the community to promote, encourage, support GSOC 2022 for Knative

/assign

**Comment by csantanapr** [comment]
Started a [thread on Slack](https://knative.slack.com/archives/CU9DGL4FM/p1638504865072100) to see if there are interested folks on participating as mentors or admins

@evankanderson gave good feedback on proposals to be submitted to TOC to get reviewed to see if the proposal is a good thing to work on or not, or provide enhancements to the proposal
>TOC might be interested in curating the project proposals for GSoC, but I think individuals or Working Group leads should probably put together proposals or make specific requests to TOC ("I think Knative should do project X for GSOC, but I'm not in a position to organize it").

@aliok volunteer to be an admin and to register Knative as an organization to accept interns, he has prior experience as GSOC admin for JBOSS. He started a google folder and [doc](https://docs.google.com/document/d/1IwQmwHS-50P3aKH0EZxThKZTZTszPLXSXYmC9K2Ofv4/edit?usp=sharing)

I also volunteer to be an admin

**Comment by aliok** [comment]
Please note that the [doc](https://docs.google.com/document/d/1IwQmwHS-50P3aKH0EZxThKZTZTszPLXSXYmC9K2Ofv4/edit#heading=h.3ni0yukqtknn) is not complete

**Comment by aliok** [comment]
The document mentioned above is meant to give an idea to the TOC and the community about GSoC. What we are looking at, what we can accomplish, and such. It is not the idea collection document.

If the TOC is ok with participating in GSoC, then we can start reaching out to Knative community members and start gathering project ideas.

**Comment by csantanapr** [comment]
>If the TOC/SC is ok with participating in GSoC, then we can start reaching out to Knative community members and start gathering project ideas.

Sounds good @aliok I added this issue to the backlog of Steering to discuss in the next meeting and if there is an agreement to move forward to gather ideas for projects, ask working group leads to propose ideas, and ask for mentors. 
There might be people that have ideas and can't mentor a project, and there might be people that can mentor but not necessarily need to come up with the project idea.

**Comment by csantanapr** [comment]
Also added this item to Steering agenda https://docs.google.com/document/d/16Rpd2nhmLWrkFJUfpJ31Ox2PpultJ-bYIhqaiWQff_I/edit?usp=sharing

**Comment by csantanapr** [comment]
/open
This was closed by prow bot, we want to keep this issue open to track progress on GSOC and centralize any discussions on the program

**Comment by csantanapr** [comment]
we are going to participate this year in GSOC and we are going to apply under the CNCF org. Carlos and Ali Ok are the focal points and had a conversation with Chris Aniszczyk and Ihor Dvoretskyi and they recommend we apply with the CNCF org. [here](https://github.com/cncf/mentoring/blob/main/summerofcode/2021.md) are the projects from last year and Knative would wave 🏄  into the list of projects this year.

**Comment by csantanapr** [comment]
We were added officially under CNCF GSOC organization with 2 ideas here https://github.com/cncf/mentoring/blob/main/summerofcode/2022.md

I hosted a [Twitter Space](https://github.com/cncf/mentoring/blob/main/summerofcode/2022.md) promoting the CNCF projects including Knative
