### ISSUE TITLE
Transfer COC ownership from TOC to Steering

### ISSUE THREAD

**Issue by csantanapr** [knative/community#876]
The COC currently states that TOC handles responsibility and enforcement.
https://github.com/knative/community/blob/main/CODE-OF-CONDUCT.md

In today's TOC meeting it was decided by TOC they want to transfer ownership to Steering

cc @knative/technical-oversight-committee 

this issue is to update the COC document appropriately and review the email for reporting

/assign

**Comment by vaikas** [comment]
code-of-conduct@knative.team has been created and verified that it works.

**Comment by csantanapr** [comment]
Thank you @vaikas
