### ISSUE TITLE
Move Knative webpage telemetry to a community owned account

### ISSUE THREAD

**Issue by bsnchan** [knative/community#89]
# Current
Telemetry for the Knative website isn't viewable for folks outside of Google at the moment

# Proposed
Move telemetry (I believe it's Google Analytics) to a Knative shared account

**Comment by vaikas** [comment]
@RichieEscarez @omerbensaadon IIUC there were some steps that needed to be done based on your discussion. What are the blockers here and what concrete steps can be taken?

**Comment by thisisnotapril** [comment]
I'm working on this! I think the easiest thing is to just create a new Google Analytics account (or whatever is preferred to use) and have that run on the site. Checking my logic with folks and will have an update this week.

**Comment by omerbensaadon** [comment]
Oh awesome, didn't know this issue existed. 

Big +1. 

Much of the work we are doing in UX WG is reliant on some data Richie pulled for us in December and we will be tracking progress with these analytics moving forward.

**Comment by omerbensaadon** [comment]
Goes without saying BUT let me know what I can do to make this happen. 

Thanks for the support @thisisnotapril

**Comment by csantanapr** [comment]
If care and want to keep the old metrics data then this is the process
>Transfer your Google Analytics account 
To transfer your Google Analytics account to another Google Account, [add a person](https://support.google.com/analytics/answer/1009702#Add) with the "Edit" and "Manage Users" permissions to your Google Analytics account. You can then [remove your Google Account](https://support.google.com/analytics/answer/1009702#Add) from the Google Analytics account.

If we can't keep the data then is a matter of getting an analytics ID from the new Knative.team google account, then you can add some individuals like @omerbensaadon that want to analyze the data. The new ID would be configured in the website generator in hugo.

**Comment by omerbensaadon** [comment]
Following up on this one more time. 

This is a blocker for UX work beginning.

**Comment by vaikas** [comment]
@csantanapr @omerbensaadon Would you mind setting this up using your knative.team accounts?

**Comment by csantanapr** [comment]
@vaikas 

We will look on if we have enough karma to create a new analytics UID and account. then see where in the website is configure with hugo.

@vaikas Do you want to close this issue, and for us to create issues in website repo to track progress, or you want to use this issue to track progress?

**Comment by csantanapr** [comment]
From the last SC meeting, we understood from @thisisnotapril  that google will not be able to transfer the account, that we should go ahead and move forward and create a new account and start from zero collecting metrics in the new account

**Comment by vaikas** [comment]
@RichieEscarez as per the discussion here https://github.com/knative/website/pull/252 (Thanks!)
This looks like something that you know how to and can do, is that correct? If so, would you mind doing the necessary changes?

**Comment by vaikas** [comment]
@csantanapr @omerbensaadon 

I'm closing this, if there's something else that still needs to be done, please reopen and explain.

**Comment by RichieEscarez** [comment]
Fixed by https://github.com/knative/website/pull/262

**Comment by vaikas** [comment]
Thanks @RichieEscarez
