### ISSUE TITLE
Add docs around use of name and logo

### ISSUE THREAD

**Issue by duglin** [knative/community#9]
I couldn't find any docs that describe how/when people can use the Knative name and logo. We should probably say something about this.

For inspiration, see:
https://github.com/kubernetes/kubernetes/blob/master/logo/usage_guidelines.md
and
https://www.linuxfoundation.org/trademark-usage/

/cc @rgregg

**Comment by duglin** [comment]
@knative/knative-steering-committee

**Comment by rgregg** [comment]
I'm working on this.

**Comment by duglin** [comment]
Any update on this one?

**Comment by duglin** [comment]
I know there's some talk going on about this, but I wanted to raise this issue back to the top of the SC's todo list. We really need a definitive statement about this on our website so that there is a clear, concise and consistent set of rules that everyone knows they need to follow. There should not need to be off-line discussions just to know what they are. Off-line chats should only be necessary if someone has follow-on questions/concerns.

Can we please get a target date and an owner for this so that it doesn't linger?

**Comment by rgregg** [comment]
I'm assigned and working on this. As with anything involving lawyers, progress is slow. @duglin I'm looking to gather more requirements around what the community wants the guidelines to be. Are you the right contact from IBM to connect with so we can understand the asks from IBM?

**Comment by duglin** [comment]
@rgregg sure

**Comment by rgregg** [comment]
@thisisnotapril is taking on this work.

**Comment by duglin** [comment]
@thisisnotapril can we get an ETA on this? It's been almost a year since the initial request.

**Comment by thisisnotapril** [comment]
@duglin should have it this coming week!

**Comment by duglin** [comment]
@thisisnotapril any update?

**Comment by thisisnotapril** [comment]
@duglin thanks for your patience - coming very soon! I am having other Steering members review a commitment; then will add the PR.
