### ISSUE TITLE
PROCESS CHANGE: Make 2FA for Knative maintainers mandatory

### ISSUE THREAD

**Issue by rhuss** [knative/community#900]
Thanks to the engagement of the [The Great MFA Distribution Project](https://github.com/ossf/great-mfa-project) (see also https://github.com/knative/community/issues/874) we are able to get free Yubikeys that can be used for [GitHub 2FA](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/accessing-github-using-two-factor-authentication).

I propose to make 2FA GitHub authentication mandatory for all Knative maintainers, i.e. WG leads and approvers.

**Comment by rhuss** [comment]
FYI, Knative was listed as one of the [100 most critical GitHub projects](https://docs.google.com/spreadsheets/d/1sO_tJ_B7_2I-TUx23pnBoIRJIqaOm8yBnKAwqs7DwBw/edit#gid=0)

**Comment by evankanderson** [comment]
+1 from Evan, Dave, Scott

**Comment by evankanderson** [comment]
+1 from Julz

**Comment by evankanderson** [comment]
This is already enabled.
