### ISSUE TITLE
Clarifying end-user seat selection for the SC for future elections

### ISSUE THREAD

**Issue by rhuss** [knative/community#917]
First of all, great to have an end-user seat in the SC which brings in a new vendor-independent perspective ! And welcome @itsmurugappan, great to have you on board !

However, I think there are some flaws in the process of end-user seat selection/election, which slipped through and I think should be fixed for the future (we did this the first time, so errors are kind of natural):

* In https://github.com/knative/community/blob/main/mechanics/SC.md we still don't specify the criteria who can apply for an end-user seat and the wording is still forward looking:

> End-user seats are planned to enable employees of organizations that use but do not sell Knative-derived products. The mechanics of eligibility for end-user seats are still in progress; it is expected that end-user seats will add to the current Steering options to specifically include end-user perspectives in the decision-making process.

* In https://github.com/knative/community/blob/main/elections/2021-SC-EU/README.md#eligibility we say that every user from a company mentioned in https://github.com/knative/community/blob/main/ADOPTERS.MD is eligible for an end-user seat. But this file contains also vendors like Red Hat, VMware, Google Cloud, IBM, SAP, Triggermesh, ... which I consider to be _vendors_, not _end users_.

* I can't really find the place where it says, that the end-user seat is elected by the other 5 seats in the steering committee (but that could be also my inability to read docs properly ;-). Can please someone point me to the place where this is written? Maybe we can include this more prominently in the SC.md document.

cc @knative/steering-committee

**Comment by csantanapr** [comment]
Thanks for opening this @rhuss I added to the SC agenda and project backlog.

I agree we need to update SC.md to make it clear.

About selecting the end user seat we have it documented in the election [doc](https://github.com/knative/community/blob/main/elections/2021-SC-EU/README.md#background)
In 2021 we introduced one end user seat to bring more diversity into the SC representation **which is to be elected by the SC once the SC election was completed.**

We should move this wording to the SC.md like you said to make it clear.

Good catch on vendors vs end-user companies.

One way to resolve this is to update the take in ADOPTERS.MD to add a column "Vendor or EndUser"  and explanation on what is considered a vendor vs an organization end user.

**Comment by devguyio** [comment]
I believe the main value behind the differentiation between vendors  & end users is the acknowledgment of the power difference between both. A vendor is someone with more power and influence on the Knative project, whether they're directly monetizing Knative or consuming Knative and monetizing a product on top of it, if they've strong contributions to the project, if they've approvers, wg leads, ToC members etc, then they have established a power and influence position, and they're more on the vendor side IMHO (Maybe crossing a contribution threshold, having wg leads, ToC members etc should be some differentiation factor between vendors and end users).

And in that sense, the true value of the end user seat is to give voice to those who depend on Knative but don't have much power and influence on it. In that sense.

Another aspect is that IMHO there's a conflict of interests in having SC electing the end user seat member. Theoretically speaking, SC members' decision of choosing an end user is affected by two conflicting interests:
1. Choosing the end user that'll be the best representation of the majority of the end users.
1. Choosing the end user that is more in line with the vendors' plans and interests. Someone who'll play along with the rest of the SC decisions and not necessarily the best representative of the end users.

It's more or less similar to [board-level employee representation](https://en.wikipedia.org/wiki/Worker_representation_on_corporate_boards_of_directors#:~:text=Worker%20representation%20on%20corporate%20boards%20of%20directors%2C%20also%20known%20as,of%20directors%20in%20corporate%20law.&text=Together%20with%20a%20right%20to,is%20often%20called%20%22codetermination%22.) . By definition it is:
> The right of workers to vote for representatives on a board of directors in corporate law.

I think practically speaking this might be not applicable right now, but at some point when we've a good number of end users, it should be end users who are electing the SC end user seat member.

**Comment by csantanapr** [comment]
>I think practically speaking this might be not applicable right now, but at some point when we've a formalized and clear list of end users, it should be end users who are electing the SC end user seat member.

This time around we barely got candidates, only 2 applied. I think we are going to have a harder time getting all the end-users companies to send one person to represent their company to vote for an end-user. I guess this is something we can try for the next round but if there is no participation on voters per company or a tie then steering decides who is the elected person.

I was looking at how other successful projects elects an end-user seat in their steering to see if there are examples we can copy. Looking at [kubernetes steering committee elections](https://github.com/kubernetes/steering/blob/main/elections.md) they don't have an end-user seat, all seats are elected by community voting and distinction on seats.

**Comment by rhuss** [comment]
Another possible issue could be also that with the end-user seat included we have an even number of SC seats (6), which might it be impossible to get a quorum for difficult decisions.

**Comment by csantanapr** [comment]
The even (6) seat is temporary, April only staid to help drive the donation and the CNCF acceptance.

**Comment by csantanapr** [comment]
If we want to follow the t, we could update sc.md to point the seat for April from google in temporary if there is any problem reaching quorum we will call out an out arbitrator like person with CTO title for CNCF which today is Chris Aniszczyk

**Comment by csantanapr** [comment]
I was able to find that CNCF has end user seats appointed and they have a definition on end user company vs none end user company. We should take similar path for knative 

https://github.com/cncf/toc/blob/main/FAQ.md#what-is-the-definition-of-an-end-user

**Comment by csantanapr** [comment]
Steering met on [Feb 10th](https://docs.google.com/document/d/16Rpd2nhmLWrkFJUfpJ31Ox2PpultJ-bYIhqaiWQff_I) and discuss this issue.
There were three action items to address this issue.
The PR #926 covers two of them.

**Comment by csantanapr** [comment]
This is issue is solved
- End User SC Candidate Eligibility and how is appointed  are stated here https://github.com/knative/community/blob/main/mechanics/SC.md#candidate-eligibility

>End-user seats are planned to enable members of organizations which use but do not sell Knative-derived products. A person is eligible to serve in the end user seat if their organization is listed in the [ADOPTERS](https://github.com/knative/community/blob/main/mechanics/ADOPTERS.md) file.

>The end user seat is appointed by Steering Committee to serve for a 1-year term.

- Adopters file was updates to indicate which companies are end user companies https://github.com/knative/community/blob/main/ADOPTERS.MD

/close
