### ISSUE TITLE
Reconcile knative-milestone-maintainers with project roles

### ISSUE THREAD

**Issue by mattmoor** [knative/community#92]
Currently the Knative Milestone Maintainers group is used by Prow to gate access to `/milestone` commands.  I'd like guidance on how this aligns with our project roles, but it is also plausible that we should simply be more open and allow org members use this until it becomes a problem.

**Comment by thisisnotapril** [comment]
Hey @mattmoor is this still an issue?

**Comment by mattmoor** [comment]
Yes, we don't have a "milestone maintainer" role in the project, but we do in peribolos.

**Comment by vaikas** [comment]
There are couple of questions:
* If we're (as I understand) moving away from Prow for tasks as much as we can
* Therefore, do we need to have the /milestone capability or a group that can address these labels. In that case, the concern is that there's no way with the current github acls to restrict only to milestones. Is this acceptable?

**Comment by evankanderson** [comment]
It sounds like Eventing is still using the `/milestone` command. It sounds like we should figure out who needs access to the command, or open up access to `/milestone` to all org members until we have a problem. (Seems reasonable to me.)

**Comment by vaikas** [comment]
@devguyio How would you like to address this?

**Comment by vaikas** [comment]
@devguyio just a ping on this to see if there's other ways to deal with this in Eventing?

**Comment by vaikas** [comment]
@devguyio would you mind taking a look and see how Eventing might want to work around this?
