### ISSUE TITLE
Folding the Sources WG into the Eventing WG

### ISSUE THREAD

**Issue by lionelvillard** [knative/community#923]
Mostly due to the lack of activities specific to sources I propose to move all Sources WG responsibilities back to the eventing WG. 

- [x] #943 
- [x] #944

Action Items:
- [x] Audit the OWNERS files to use `eventing-writers` instead of `source-wg-leads` (so far I couldn't find any instances of it)
- [x] Update the sponsoring WG in the top-level README in each source repo.
- [x] Update the community web page.

**Comment by dprotaso** [comment]
+1

**Comment by rhuss** [comment]
+1

**Comment by dprotaso** [comment]
You'll want to update peribolos as well

**Comment by rhuss** [comment]
@lionelvillard 

> Update the sponsoring WG in the top-level README in each source repo.

Do you have an example of such an entry ? Also, do you have a list of repos to check ? (this is not evident from the repository names alone).

**Comment by lionelvillard** [comment]
I found at least one: https://github.com/knative-sandbox/eventing-gitlab. I'm fixing it.

**Comment by vaikas** [comment]
@lionelvillard any updates on this?
