### ISSUE TITLE
Reconcile TBD Eventing planning role

### ISSUE THREAD

**Issue by mattmoor** [knative/community#93]
I created this team to hold Akash, who lost privileges: https://github.com/orgs/knative/teams/tbd-group-for-triage-and-planning

His words on what he needs:
> I need permission to maintain the hygiene our issues and milestones - triage issues, fix labels, fix milestones, create new milestones etc

**Comment by mattmoor** [comment]
cc @vaikas @lionelvillard

**Comment by dprotaso** [comment]
Is that this role?

https://github.com/knative/community/blob/master/ROLES.md#working-group-execution-lead

**Comment by mattmoor** [comment]
Possibly, but I didn't want to label it as such without the typical process, which will need a PR here to codify the role :)

**Comment by grantr** [comment]
This team is now called [Eventing Triage](https://github.com/orgs/knative/teams/eventing-triage). @lberk has been participating in the weekly eventing triage meetings and needs bulk labeling permissions, so he's now a member as well.

**Comment by vaikas** [comment]
This can be closed.
The original group @mattmoor referred to no longer exists.
And as mentioned by @grantr and @lberk we are golden here.
If something else is still missing, please reopen and I'll tackle this.

**Comment by mattmoor** [comment]
The point of these issues are to reconcile roles granted privileges with ROLES.md.

Essentially: We should avoid having roles in peribolos that lack documentation on how folks enter/leave that role.

I don't think "Eventing Triage" fits this, unless everyone involved is an execution lead (in which case, shouldn't we eliminate this group)?

**Comment by lberk** [comment]
I'm not an execution lead -- but would like to still be able and help with the traige if possible.  If there is an alternate role I should work towards (which eases maintenance of the eventing bits), let me know and I can work towards that.

**Comment by vaikas** [comment]
How does serving handle the triage issue like this? For example in this particular case @lberk has been participating in the issue triage. Is there missing role that we need to create? For example we added the scribe role awhile back. I'll create an issue that's a bit more clear on what the intent of this issue is (re: peribolos comment above).

**Comment by mattmoor** [comment]
> How does serving handle the triage issue like this? 

Generally through Prow commands (if they aren't a lead).
