### ISSUE TITLE
Submit a Pull request to add your project as a sandbox project to https://landscape.cncf.io

### ISSUE THREAD

**Issue by csantanapr** [knative/community#938]
Action Item from https://github.com/cncf/toc/issues/794

**Comment by csantanapr** [comment]
PR opened https://github.com/cncf/landscape/pull/2504

**Comment by csantanapr** [comment]
Second PR open to update crunchbase and description https://github.com/cncf/landscape/pull/2505

**Comment by vaikas** [comment]
@csantanapr can we close this issue now? looks like both PRs have been merged.

**Comment by csantanapr** [comment]
yes @vaikas 
/close
