### ISSUE TITLE
Investigate alternative options for using Slack.

### ISSUE THREAD

**Issue by vaikas** [knative/community#941]
From time to time there has been questions about if we should be using Slack after the CNCF donation.

This issue tracks the alternatives considered and folks can look here and do their own due diligence as well.

**Comment by lance** [comment]
Do we know what the CNCF requirements are regarding the use of other collaboration tools? I was looking at the onboarding issue [here](https://github.com/cncf/toc/issues/794) and one of the checkboxes is this.

>  Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details)

**Comment by rhuss** [comment]
Looking at the number of channels that we have in the Knative slack (59) compared to the overall number of channels in the CNCF slack (760) a simple migration would probably not be good enough but we also would have to consolidate and boil it down to a handful (5-10) channels only. Prometheus for example has 5 channels at the CNCF slack. This e.g. would also affect e.g. our release process where we have one channel per release.

I'm open to any other chat system (discord, matrix, gitter, ...) but please not GChat, which is awful when it comes to thread handling.

**Comment by csantanapr** [comment]
Related to [INCUBATING PROJECT ONBOARDING] Knative https://github.com/cncf/toc/issues/794

**Comment by csantanapr** [comment]
I closed issue #953 and lets use this one going forward

Options:

Stay with current Slack workspace Paid tier (today's state paid by Google)
Stay with current Slack workspace Free tier
Move to channel(s) to Kubernetes Slack
Move to channel(s) to CNCF Slack

**Comment by lance** [comment]
> * Stay with current Slack workspace Paid tier (CNCF funded, currently funded by Google)

Is this actually an option? I didn't think CNCF would fund another Slack, but could of course be mistaken.

**Comment by thisisnotapril** [comment]
Per Knative Steering meeting today, we will migrate to the CNCF Slack instance. I created the Servicedesk ticket with CNCF to start this process.
