### ISSUE TITLE
Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork

### ISSUE THREAD

**Issue by csantanapr** [knative/community#947]
Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork

Related to [INCUBATING PROJECT ONBOARDING] Knative https://github.com/cncf/toc/issues/794

**Comment by csantanapr** [comment]
knative logo files are located here https://github.com/knative/docs/tree/main/docs/images/logo

**Comment by itsmurugappan** [comment]
completed

**Comment by csantanapr** [comment]
logo files added here https://github.com/cncf/artwork/tree/master/projects/knative
