### ISSUE TITLE
Trademarks: transfer any trademark name "knative" assets over to the LF

### ISSUE THREAD

**Issue by csantanapr** [knative/community#948]
Trademarks: transfer any trademark name "knative" assets over to the LF

Only the "knative" name is registered as trademark. I was not able to find that logo was registered
https://tsdr.uspto.gov/#caseNumber=88044625&caseType=SERIAL_NO&searchType=statusSearch

Related https://github.com/cncf/toc/issues/794

**Comment by csantanapr** [comment]
I asked in Slack but have not seeing a response

@spencerdillard  @thisisnotapril  
**Did Google registered the knative logo?**

I was only able to find the word “KNATIVE” nothing about the logo
Here is the report and only includes the characters nothing about colors shapes or logos
https://tsdr.uspto.gov/#caseNumber=88044625&caseType=SERIAL_NO&searchType=statusSearch
I understand there is a design search but I was not able to find it there either

**Comment by thisisnotapril** [comment]
I'll check with the legal team; everything will get transferred over.

**Comment by thisisnotapril** [comment]
confirmed with lawyercats they will transfer everything over - so all good there. i will start that thread on Monday! (Fri is a Google holiday)

**Comment by spencerdillard** [comment]
Thanks @thisisnotapril

**Comment by csantanapr** [comment]
Thank you @thisisnotapril for the update

**Comment by thisisnotapril** [comment]
Confirming this has been done - agreement signed and counter-signed by Google and LF.
