### ISSUE TITLE
Review and Understand CNCF documents (services, guidelines, processes)

### ISSUE THREAD

**Issue by csantanapr** [knative/community#950]
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
- [x] Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/

**Comment by csantanapr** [comment]
I think reviewing and understanding should be completed but both @knative/steering-committee  and @knative/technical-oversight-committee

**Comment by csantanapr** [comment]
Please @knative/steering-committee and @knative/technical-oversight-committee please comment on this Issue with `ack` when your are done reviewing and understanding all the documents

**Comment by csantanapr** [comment]
Related to [INCUBATING PROJECT ONBOARDING] Knative https://github.com/cncf/toc/issues/794

**Comment by csantanapr** [comment]
Added
- ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/

**Comment by n3wscott** [comment]
`ack`

**Comment by lance** [comment]
`ack`

**Comment by csantanapr** [comment]
Reminder for folks that have not finished, including myself 😄

**Comment by rhuss** [comment]
`ack`

Following the license allow list in https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#approved-licenses-for-allowlist , do we have already a check for our third-party dependencies that we do not include a dependency with a license that is not on the list?

**Comment by dprotaso** [comment]
ack reading the material

**Comment by dprotaso** [comment]
re: licenses 

As part of the service desk we can request to use a tool FOSSA (https://fossa.com/product/open-source-license-compliance) that should help us be compliant

**Comment by csantanapr** [comment]
ack

**Comment by itsmurugappan** [comment]
ack

**Comment by csantanapr** [comment]
@vaikas said in Slack he read the docs

**Comment by csantanapr** [comment]
@evankanderson said in Slack he read the docs

**Comment by evankanderson** [comment]
ack

(I think I missed the comment update to say that here)

**Comment by evankanderson** [comment]
> `ack`
> 
> Following the license allow list in https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#approved-licenses-for-allowlist , do we have already a check for our third-party dependencies that we do not include a dependency with a license that is not on the list?

I believe we're currently using https://github.com/google/go-licenses to enforce that we don't pick up unwanted licenses.

**Comment by pmorie** [comment]
`ack`

**Comment by csantanapr** [comment]
Everyone from Steering and TOC have review, and understand the documents
