### ISSUE TITLE
Website: Analytics transferred to amye@linuxfoundation.org

### ISSUE THREAD

**Issue by csantanapr** [knative/community#957]
Website: Analytics transferred to amye@linuxfoundation.org

Related to [INCUBATING PROJECT ONBOARDING] Knative https://github.com/cncf/toc/issues/794

**Comment by csantanapr** [comment]
Added amey email as admin to Google analytics

**Comment by csantanapr** [comment]
We need to make `amye@linuxfoundation.org` Owner not the Administrator

@vaikas or @thisisnotapril  do you have enough permission to make Amye Owner? I don't have permission only to assign the Administrator

**Comment by vaikas** [comment]
When I go to analytics.google.com signed in with knative.team, I don't see where this is configured. Can you share the link?

**Comment by csantanapr** [comment]
Hi @vaikas 
If you go to setting on the bottom left corner of UI, then Property Access Management takes you to this [URL](https://analytics.google.com/analytics/web/#/a190144112p262796325/admin/suiteusermanagement/property)

**Comment by csantanapr** [comment]
![image](https://user-images.githubusercontent.com/1094878/164310570-62f578c9-8d79-4857-8121-9d42ff47f72d.png)

**Comment by vaikas** [comment]
I don't have that, and you seem to be an admin there?

**Comment by csantanapr** [comment]
Thanks for checking @vaikas 

"Administrator" is the highest permission role same as an "owner"
![image](https://user-images.githubusercontent.com/1094878/164527350-d6496b64-7565-4d70-b86f-12f2c55132fd.png)

I sent a [message](https://github.com/cncf/toc/issues/794#issuecomment-1105599778) to @amye let's see what we hear back.

**Comment by csantanapr** [comment]
TODO is marked done now
