### ISSUE TITLE
Request access to 1 Password from CNCF

### ISSUE THREAD

**Issue by chizhg** [knative/community#966]
As part of the CNCF donation, we'd like to share the secret key for a few GitHub bot accounts (currently owned by Google) with the Knative community, and the issue is tracked at https://github.com/knative/test-infra/issues/2987

Based on the discussions in https://knative.slack.com/archives/CU9DGL4FM/p1645164373229969, we'll want to use `1 Password` to manage these secrets. This issue is for tracking the work to get the access through the CNCF service desk.

**Comment by csantanapr** [comment]
We got access today to 1Password, @chizhg please work with @dprotaso to get your credentials into the 1Password vault
