### ISSUE TITLE
Request 1Password account from cncf

### ISSUE THREAD

**Issue by csantanapr** [knative/community#987]
In Knative we have a few secrets/credentials that need to be managed by the team, some examples:

- Zoom account
- Github Bot Access Token
- Katacoda

We are under the understanding that CNCF can get us a 1Password account we can use as a team.

**Comment by csantanapr** [comment]
I opened a cncf service desk ticket today

**Comment by dprotaso** [comment]
I did this already and they directed me this repo and I made the PR

https://github.com/1Password/1password-teams-open-source/pull/496
