### ISSUE TITLE
[Steering] Update documents to clarify SC End User vacancy process

### ISSUE THREAD

**Issue by csantanapr** [knative/community#995]
The SC document has information on how to handle [vacancies](https://github.com/knative/community/blob/main/STEERING-COMMITTEE.md#vacancies) for elected members, but the end user is an appointed seat by the members of the steering committee.

>In the event of a resignation or other loss of an elected SC member, the candidate with the next most votes from the previous election will be offered the seat, provided that person otherwise qualifies to join the SC. This process will continue until the seat is filled.
In case this fails to fill the seat, a special election for that position will be held as soon as possible, unless the regular SC election is less than 7 weeks away. Eligible voters from the most recent election will vote in the special election. Eligibility will not be redetermined at the time of the special election. Any replacement SC member will serve out the remainder of the term for the person they are replacing, regardless of the length of that remainder.

We should update the document to clarify how the seat replacement for end user seat would work since "special election" is not applicable

Also to update places where we use the term "selected" or "elected" when referring to end user seat, we should use "appointed" 
like in the end user candidate [document](https://github.com/knative/community/blob/main/elections/2021-SC-EU/README.md)

cc @geekygirldawn @knative/steering-committee

**Comment by geekygirldawn** [comment]
For the vacancies section, we could add this:

> In the event of a resignation or other loss of an appointed end user SC member, the SC will appoint a new person to fill the end user SC seat.

We should also scrub the SC page to be consistent in language. In most cases, the pages say "End-User", but it really should be "end user" to be consistent with the CNCF language (ex: https://www.cncf.io/enduser/)
